*&---------------------------------------------------------------------*
*& Report  ZBCLL_COSTING_ANALY1
*&
*&---------------------------------------------------------------------*
*&
*&
*&---------------------------------------------------------------------*
REPORT ZBCLL_COSTING_ANALY1_N1 NO STANDARD PAGE HEADING LINE-SIZE 300.
TABLES : MARA,
         KONP,
         MVKE,
         TVM5T,
         MAKT,
         LFA1,T247,
         ZTP_COST11,
         pa0001.

TYPE-POOLS:  SLIS.

DATA: G_REPID     LIKE SY-REPID,
      FIELDCAT    TYPE SLIS_T_FIELDCAT_ALV,
      WA_FIELDCAT LIKE LINE OF FIELDCAT,
      SORT        TYPE SLIS_T_SORTINFO_ALV,
      WA_SORT     LIKE LINE OF SORT,
      LAYOUT      TYPE SLIS_LAYOUT_ALV.

DATA: IT_MARA          TYPE TABLE OF MARA,
      WA_MARA          TYPE MARA,
      IT_ZTP_COST11    TYPE TABLE OF ZTP_COST11,
      WA_ZTP_COST11    TYPE ZTP_COST11,
      IT_SZTP_COST11   TYPE TABLE OF ZTP_COST11,
      WA_SZTP_COST11   TYPE ZTP_COST11,
      IT_S1ZTP_COST12  TYPE TABLE OF ZTP_COST12,
      WA_S1ZTP_COST12  TYPE ZTP_COST12,
      IT_S2ZTP_COST12  TYPE TABLE OF ZTP_COST12,
      WA_S2ZTP_COST12  TYPE ZTP_COST12,
      IT_SM1ZTP_COST12 TYPE TABLE OF ZTP_COST12,
      WA_SM1ZTP_COST12 TYPE ZTP_COST12,
      IT_SM2ZTP_COST12 TYPE TABLE OF ZTP_COST12,
      WA_SM2ZTP_COST12 TYPE ZTP_COST12.
DATA: RT1 TYPE P DECIMALS 2.
DATA: SUBJECT(100) TYPE C.
DATA: COUNT TYPE I.
TYPES: BEGIN OF MAT1,
         MATNR   TYPE MARA-MATNR,
         FGLIFNR TYPE LIFNR,
       END OF MAT1.
TYPES: BEGIN OF CHECK1,
         FGLIFNR TYPE LIFNR,
       END OF CHECK1.
TYPES: BEGIN OF MAT2,
         MATNR TYPE MARA-MATNR,
         MRP   TYPE KONP-KBETR,
         PTS   TYPE KONP-KBETR,
       END OF MAT2.

TYPES: BEGIN OF SMAT2,
         MATNR TYPE MARA-MATNR,
         ZSAM  TYPE KONP-KBETR,
       END OF SMAT2.
TYPES: BEGIN OF ITAB1,
         COUNT(2) TYPE C,
         MATNR    TYPE ZTP_COST11-MATNR,
         WERKS    TYPE ZTP_COST11-WERKS,
         VBELN    TYPE ZTP_COST11-VBELN,
         GJAHR    TYPE ZTP_COST11-GJAHR,
         SVBELN   TYPE ZTP_COST11-VBELN,
         SGJAHR   TYPE ZTP_COST11-GJAHR,
         FGLIFNR  TYPE ZTP_COST11-FGLIFNR,
         MAKTX    TYPE MAKT-MAKTX,
         NAME1    TYPE LFA1-NAME1,
         VAL1     TYPE P DECIMALS 2,
*         VAL2      TYPE P DECIMALS 2,
*         VAL3      TYPE P DECIMALS 2,
*         VAL4      TYPE P DECIMALS 2,
*         VAL5      TYPE P DECIMALS 2,
*         VAL6      TYPE P DECIMALS 2,
*         MRP       TYPE KONP-KBETR,
*         PTS       TYPE KONP-KBETR,
         BEZEI    TYPE TVM5T-BEZEI,
         SAMPCODE TYPE MARA-MATNR,
         SMAKTX   TYPE MAKT-MAKTX,
         ZSAM     TYPE KONP-KBETR,
         SBEZEI   TYPE TVM5T-BEZEI,
       END OF ITAB1.

TYPES: BEGIN OF ITAB3,
         MATNR    TYPE MATNR,
         FGLIFNR  TYPE LIFNR,
         SAMPCODE TYPE MATNR,
         VBELN    TYPE ZTP_COST11-VBELN,
         GJAHR    TYPE ZTP_COST11-GJAHR,
         NVBELN   TYPE ZTP_COST11-VBELN,
         NGJAHR   TYPE ZTP_COST11-GJAHR,
         SVBELN   TYPE ZTP_COST11-VBELN,
         SGJAHR   TYPE ZTP_COST11-GJAHR,
         NSVBELN  TYPE ZTP_COST11-VBELN,
         NSGJAHR  TYPE ZTP_COST11-GJAHR,
         VAL1     TYPE P DECIMALS 2,
         SVAL1    TYPE P DECIMALS 2,
         NVAL1    TYPE P DECIMALS 2,
         NSVAL1   TYPE P DECIMALS 2,
         BEZEI    TYPE TVM5T-BEZEI,
         SBEZEI   TYPE TVM5T-BEZEI,
         RT1      TYPE P DECIMALS 2,
       END OF ITAB3.
TYPES: BEGIN OF RES1,
         MATNR  TYPE MATNR,
         VBELN  TYPE ZTP_COST11-VBELN,
         GJAHR  TYPE ZTP_COST11-GJAHR,
         NVBELN TYPE ZTP_COST11-VBELN,
         NGJAHR TYPE ZTP_COST11-GJAHR,
         IDNRK  TYPE ZTP_COST12-IDNRK,
         POSNR  TYPE ZTP_COST12-POSNR,
         NRATE  TYPE P DECIMALS 2,
         RATE   TYPE P DECIMALS 2,
         RT     TYPE P DECIMALS 2,
       END OF RES1.


DATA: IT_MAT1         TYPE TABLE OF MAT1,
      WA_MAT1         TYPE MAT1,
      IT_CHECK1       TYPE TABLE OF CHECK1,
      WA_CHECK1       TYPE CHECK1,
      IT_SMAT1        TYPE TABLE OF MAT1,
      WA_SMAT1        TYPE MAT1,
      IT_SMAT2        TYPE TABLE OF SMAT2,
      WA_SMAT2        TYPE SMAT2,
      IT_MAT2         TYPE TABLE OF MAT2,
      WA_MAT2         TYPE MAT2,
      IT_TAB1         TYPE TABLE OF ITAB1,
      WA_TAB1         TYPE ITAB1,
      IT_TAB2         TYPE TABLE OF ITAB1,
      WA_TAB2         TYPE ITAB1,
      IT_A602         TYPE TABLE OF A602,
      WA_A602         TYPE A602,
      IT_ZPRODBATCHES TYPE TABLE OF ZPRODBATCHES,
      WA_ZPRODBATCHES TYPE ZPRODBATCHES,
      IT_TAB3         TYPE TABLE OF ITAB3,
      WA_TAB3         TYPE ITAB3,
      IT_TAB4         TYPE TABLE OF ZCOST3,
      WA_TAB4         TYPE ZCOST3,
      IT_RES1         TYPE TABLE OF RES1,
      WA_RES1         TYPE RES1,
      IT_SRES1        TYPE TABLE OF RES1,
      WA_SRES1        TYPE RES1.
DATA: COUNT1 TYPE I.
DATA: VAL1 TYPE P DECIMALS 2.
DATA: GST1 TYPE P DECIMALS 2,
      VAL2 TYPE P DECIMALS 2,
      VAL3 TYPE P DECIMALS 2,
      VAL4 TYPE P DECIMALS 2,
      VAL5 TYPE P DECIMALS 2,
      VAL6 TYPE P DECIMALS 2,
      PTS  TYPE KONP-KBETR.
DATA: DATE1 TYPE SY-DATUM.
DATA: VBELN TYPE VBRK-VBELN.
DATA: GJAHR TYPE BKPF-GJAHR.
DATA : V_FM TYPE RS38L_FNAM.
DATA: NAME1 TYPE NAME1.
DATA : CONTROL  TYPE SSFCTRLOP.
DATA : W_SSFCOMPOP TYPE SSFCOMPOP.
DATA : NMONTH1(3) TYPE C,
       MON(15)    TYPE C.
data footer TYPE string.
data: name11 TYPE pa0001-ename,
      name12 TYPE pa0001-ename.
SELECTION-SCREEN BEGIN OF BLOCK MERKMALE1 WITH FRAME TITLE TEXT-001.
PARAMETERS : P1 RADIOBUTTON GROUP R1,
             P2 RADIOBUTTON GROUP R1.
SELECTION-SCREEN END OF BLOCK MERKMALE1.

SELECTION-SCREEN BEGIN OF BLOCK MERKMALE2 WITH FRAME TITLE TEXT-001.
SELECT-OPTIONS: MATNR FOR MARA-MATNR ,
                LIFNR FOR LFA1-LIFNR,
                BUDAT FOR SY-DATUM OBLIGATORY.
PARAMETERS : sub(40) TYPE c.
*PARAMETERS : FYEAR TYPE GJAHR.
SELECTION-SCREEN END OF BLOCK MERKMALE2.

INITIALIZATION.
  G_REPID = SY-REPID.

START-OF-SELECTION.

*  IF MATNR IS INITIAL AND LIFNR IS INITIAL.
*    MESSAGE 'enter Product code or FG VENDOR CODE' TYPE 'E'.
*  ENDIF.

  SELECT * FROM MARA INTO TABLE IT_MARA WHERE MATNR IN MATNR.
  SELECT * FROM ZTP_COST11 INTO TABLE IT_ZTP_COST11 WHERE MATNR IN MATNR AND FGLIFNR IN LIFNR AND CPUDT IN BUDAT.
  IF IT_ZTP_COST11 IS INITIAL.
    MESSAGE 'NO DATA FOUND' TYPE 'E'.
  ENDIF.
  LOOP AT IT_ZTP_COST11 INTO WA_ZTP_COST11.
    WA_MAT1-MATNR = WA_ZTP_COST11-MATNR.
    WA_MAT1-FGLIFNR = WA_ZTP_COST11-FGLIFNR.
    COLLECT WA_MAT1 INTO IT_MAT1.
    CLEAR WA_MAT1.

    WA_CHECK1-FGLIFNR = WA_ZTP_COST11-FGLIFNR.
    COLLECT WA_CHECK1 INTO IT_CHECK1.
    CLEAR WA_CHECK1.
  ENDLOOP.
  SORT IT_CHECK1 BY FGLIFNR.
  DELETE ADJACENT DUPLICATES FROM IT_CHECK1 COMPARING FGLIFNR.

  SORT IT_MAT1 BY MATNR FGLIFNR.
  DELETE ADJACENT DUPLICATES FROM IT_MAT1 COMPARING MATNR FGLIFNR.
  LOOP AT IT_MAT1 INTO WA_MAT1.
    PERFORM FORM1.
  ENDLOOP.
  PERFORM PRINT.


*&---------------------------------------------------------------------*
*&      Form  TOP
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
FORM TOP.

  DATA: COMMENT    TYPE SLIS_T_LISTHEADER,
        WA_COMMENT LIKE LINE OF COMMENT.

  WA_COMMENT-TYP = 'A'.
  WA_COMMENT-INFO = 'THIRD PARTY COST SHEET SUMMARY'.
*  WA_COMMENT-INFO = P_FRMDT.
  APPEND WA_COMMENT TO COMMENT.

  CALL FUNCTION 'REUSE_ALV_COMMENTARY_WRITE'
    EXPORTING
      IT_LIST_COMMENTARY = COMMENT
*     I_LOGO             = 'ENJOYSAP_LOGO'
*     I_END_OF_LIST_GRID =
*     I_ALV_FORM         =
    .

  CLEAR COMMENT.

ENDFORM.                    "TOP



*&---------------------------------------------------------------------*
*&      Form  USER_COMM
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*      -->UCOMM      text
*      -->SELFIELD   text
*----------------------------------------------------------------------*
FORM USER_COMM USING UCOMM LIKE SY-UCOMM
                     SELFIELD TYPE SLIS_SELFIELD.



  CASE SELFIELD-FIELDNAME.
    WHEN 'VBELN'.
      SET PARAMETER ID 'VF' FIELD SELFIELD-VALUE.
      CALL TRANSACTION 'VF03' AND SKIP FIRST SCREEN.
    WHEN 'VBELN1'.
      SET PARAMETER ID 'BV' FIELD SELFIELD-VALUE.
      CALL TRANSACTION 'VL03N' AND SKIP FIRST SCREEN.
    WHEN OTHERS.
  ENDCASE.
ENDFORM.                    "USER_COMM


*&---------------------------------------------------------------------*
*&      Form  MRP
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*  -->  p1        text
*  <--  p2        text
*----------------------------------------------------------------------*
FORM MRP .

  DATE1 = SY-DATUM - 180.
  IF IT_MAT1 IS NOT INITIAL.
    SELECT * FROM A602 INTO TABLE IT_A602  FOR ALL ENTRIES IN IT_MAT1 WHERE KAPPL EQ 'V' AND KSCHL EQ 'Z001' AND MATNR EQ IT_MAT1-MATNR AND
    DATAB GE DATE1 AND DATBI GE SY-DATUM.
  ENDIF.
  SORT IT_A602 DESCENDING BY KNUMH.
  LOOP AT IT_MAT1 INTO WA_MAT1.
    READ TABLE IT_A602 INTO WA_A602 WITH KEY MATNR = WA_MAT1-MATNR.
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM KONP WHERE KNUMH EQ WA_A602-KNUMH AND KBETR GT 0.
      IF SY-SUBRC EQ 0.
        CLEAR : PTS.
*        WRITE : / 'mrp',WA_MAT1-MATNR,WA_A602-CHARG,KONP-KBETR.
        PTS = ( ( 6429 / 100 ) * KONP-KBETR ) / 100.
*        WRITE : 'pts',PTS.
        WA_MAT2-MATNR = WA_MAT1-MATNR.
        WA_MAT2-MRP = KONP-KBETR.
        WA_MAT2-PTS = PTS.
        COLLECT WA_MAT2 INTO IT_MAT2.
        CLEAR WA_MAT2.
      ENDIF.
    ENDIF.

    READ TABLE IT_ZPRODBATCHES INTO WA_ZPRODBATCHES WITH KEY MATNR = WA_MAT1-MATNR.
    IF SY-SUBRC EQ 0.
      WA_SMAT1-MATNR = WA_ZPRODBATCHES-COMB_MATNR1.
      COLLECT WA_SMAT1 INTO IT_SMAT1.
      CLEAR WA_SMAT1.
    ENDIF.
  ENDLOOP.

  SORT IT_SMAT1 BY MATNR.
  DELETE ADJACENT DUPLICATES FROM IT_SMAT1 COMPARING MATNR.
  CLEAR: IT_A602,WA_A602.
  IF IT_SMAT1 IS NOT INITIAL.
    SELECT * FROM A602 INTO TABLE IT_A602  FOR ALL ENTRIES IN IT_SMAT1 WHERE KAPPL EQ 'V' AND KSCHL EQ 'ZSAM' AND MATNR EQ IT_SMAT1-MATNR AND
    DATAB GE DATE1 AND DATBI GE SY-DATUM.
  ENDIF.
  SORT IT_A602 DESCENDING BY KNUMH.

  LOOP AT IT_SMAT1 INTO WA_SMAT1.
    READ TABLE IT_A602 INTO WA_A602 WITH KEY MATNR = WA_SMAT1-MATNR.
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM KONP WHERE KNUMH EQ WA_A602-KNUMH AND KBETR GT 0.
      IF SY-SUBRC EQ 0.
        WA_SMAT2-MATNR = WA_SMAT1-MATNR.
        WA_SMAT2-ZSAM = KONP-KBETR.
        COLLECT WA_SMAT2 INTO IT_SMAT2.
        CLEAR WA_SMAT2.
      ENDIF.
    ENDIF.
  ENDLOOP.

ENDFORM.
*&---------------------------------------------------------------------*
*&      Form  SAMPRATE
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*  -->  p1        text
*  <--  p2        text
*----------------------------------------------------------------------*
FORM SAMPRATE1.



*  LOOP AT IT_MARA INTO WA_MARA WHERE .
  CLEAR : VBELN,GJAHR.
  READ TABLE IT_ZTP_COST11 INTO WA_ZTP_COST11 WITH KEY MATNR = WA_MAT1-MATNR FGLIFNR = WA_MAT1-FGLIFNR.
  IF SY-SUBRC EQ 0.
    VBELN = WA_ZTP_COST11-VBELN.
    GJAHR = WA_ZTP_COST11-GJAHR.
    WA_TAB1-COUNT = COUNT.
    WA_TAB1-MATNR = WA_ZTP_COST11-MATNR.
    WA_TAB1-WERKS = WA_ZTP_COST11-WERKS.
    WA_TAB1-VBELN = WA_ZTP_COST11-VBELN.
    WA_TAB1-GJAHR = WA_ZTP_COST11-GJAHR.
    WA_TAB1-FGLIFNR = WA_ZTP_COST11-FGLIFNR.
    SELECT SINGLE * FROM MAKT WHERE MATNR EQ WA_MAT1-MATNR AND SPRAS EQ 'EN'.
    IF SY-SUBRC EQ 0.
      WA_TAB1-MAKTX = MAKT-MAKTX.
    ENDIF.
    SELECT SINGLE * FROM LFA1 WHERE LIFNR EQ WA_ZTP_COST11-FGLIFNR.
    IF SY-SUBRC EQ 0.
      WA_TAB1-NAME1 = LFA1-NAME1.
    ENDIF.
    WA_TAB1-VAL1 = WA_ZTP_COST11-NET - WA_ZTP_COST11-GSTVAL1.
    SELECT SINGLE * FROM MVKE WHERE MATNR EQ WA_MAT1-MATNR.
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM TVM5T WHERE MVGR5 EQ MVKE-MVGR5.
      IF SY-SUBRC EQ 0.
        WA_TAB1-BEZEI = TVM5T-BEZEI.
      ENDIF.
    ENDIF.
    READ TABLE IT_ZPRODBATCHES INTO WA_ZPRODBATCHES WITH KEY MATNR = WA_MAT1-MATNR.
    IF SY-SUBRC EQ 0.
      WA_TAB1-SAMPCODE = WA_ZPRODBATCHES-COMB_MATNR1.
      SELECT SINGLE * FROM MAKT WHERE MATNR EQ WA_ZPRODBATCHES-COMB_MATNR1 AND SPRAS EQ 'EN'.
      IF SY-SUBRC EQ 0.
        WA_TAB1-SMAKTX = MAKT-MAKTX.
      ENDIF.
      READ TABLE IT_SZTP_COST11 INTO WA_SZTP_COST11 WITH KEY MATNR = WA_ZPRODBATCHES-COMB_MATNR1.
      IF SY-SUBRC EQ 0.
        WA_TAB1-ZSAM = WA_SZTP_COST11-NET - WA_SZTP_COST11-GSTVAL1.
        WA_TAB1-SVBELN = WA_SZTP_COST11-VBELN.
        WA_TAB1-SGJAHR = WA_SZTP_COST11-GJAHR.
      ENDIF.
      SELECT SINGLE * FROM MVKE WHERE MATNR EQ WA_ZPRODBATCHES-COMB_MATNR1.
      IF SY-SUBRC EQ 0.
        SELECT SINGLE * FROM TVM5T WHERE MVGR5 EQ MVKE-MVGR5.
        IF SY-SUBRC EQ 0.
          WA_TAB1-SBEZEI = TVM5T-BEZEI.
        ENDIF.
      ENDIF.
    ENDIF.
    COLLECT WA_TAB1 INTO IT_TAB1.
    DELETE IT_ZTP_COST11 WHERE VBELN EQ WA_TAB1-VBELN AND GJAHR EQ WA_TAB1-GJAHR.
    DELETE IT_SZTP_COST11 WHERE VBELN EQ WA_TAB1-SVBELN AND GJAHR EQ WA_TAB1-SGJAHR.
    CLEAR WA_TAB1.
    COUNT = COUNT + 1.
  ENDIF.

*  ENDLOOP.
ENDFORM.
*&---------------------------------------------------------------------*
*&      Form  PFORM
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*  -->  p1        text
*  <--  p2        text
*----------------------------------------------------------------------*

*&---------------------------------------------------------------------*
*&      Form  ALV
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*  -->  p1        text
*  <--  p2        text
*----------------------------------------------------------------------*
FORM ALV .



  WA_FIELDCAT-FIELDNAME = 'MATNR'.
  WA_FIELDCAT-SELTEXT_L = 'PRODUCT CODE'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'MAKTX'.
  WA_FIELDCAT-SELTEXT_L = 'PRODUCT NAME'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'FGLIFNR'.
  WA_FIELDCAT-SELTEXT_L = 'FG VENDOR'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'NAME1'.
  WA_FIELDCAT-SELTEXT_L = 'FG VENDOR NAME'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'WERKS'.
  WA_FIELDCAT-SELTEXT_L = 'PLANT'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'VBELN'.
  WA_FIELDCAT-SELTEXT_L = 'COST SHEET NO.'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'GJAHR'.
  WA_FIELDCAT-SELTEXT_L = 'CS YEAR'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'VAL1'.
  WA_FIELDCAT-SELTEXT_L = 'BASIC'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'VAL2'.
  WA_FIELDCAT-SELTEXT_L = 'GST 12%'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'VAL3'.
  WA_FIELDCAT-SELTEXT_L = 'TOTAL COST'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'VAL4'.
  WA_FIELDCAT-SELTEXT_L = 'O/H ABS (3.34%)'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'VAL2'.
  WA_FIELDCAT-SELTEXT_L = 'LESS ITC'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'VAL5'.
  WA_FIELDCAT-SELTEXT_L = 'TOTAL COG'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'VAL6'.
  WA_FIELDCAT-SELTEXT_L = 'COG %'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'MRP'.
  WA_FIELDCAT-SELTEXT_L = 'MRP'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'PTS'.
  WA_FIELDCAT-SELTEXT_L = 'PTS'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'BEZEI'.
  WA_FIELDCAT-SELTEXT_L = 'PACK'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'SAMPCODE'.
  WA_FIELDCAT-SELTEXT_L = 'SAMPLE CODE'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'SAMPBEZEI'.
  WA_FIELDCAT-SELTEXT_L = 'SAMPLE PACK'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'ZSAM'.
  WA_FIELDCAT-SELTEXT_L = 'SAMPLE COST'.
  APPEND WA_FIELDCAT TO FIELDCAT.


  LAYOUT-ZEBRA = 'X'.
  LAYOUT-COLWIDTH_OPTIMIZE = 'X'.
  LAYOUT-WINDOW_TITLEBAR  = 'THIRD PARTY COST SHEET SUMMARY'.


  CALL FUNCTION 'REUSE_ALV_GRID_DISPLAY'
    EXPORTING
*     I_INTERFACE_CHECK       = ' '
*     I_BYPASSING_BUFFER      = ' '
*     I_BUFFER_ACTIVE         = ' '
      I_CALLBACK_PROGRAM      = G_REPID
*     I_CALLBACK_PF_STATUS_SET          = ' '
      I_CALLBACK_USER_COMMAND = 'USER_COMM'
      I_CALLBACK_TOP_OF_PAGE  = 'TOP'
*     I_CALLBACK_HTML_TOP_OF_PAGE       = ' '
*     I_CALLBACK_HTML_END_OF_LIST       = ' '
*     I_STRUCTURE_NAME        =
*     I_BACKGROUND_ID         = ' '
*     I_GRID_TITLE            =
*     I_GRID_SETTINGS         =
      IS_LAYOUT               = LAYOUT
      IT_FIELDCAT             = FIELDCAT
*     IT_EXCLUDING            =
*     IT_SPECIAL_GROUPS       =
*     IT_SORT                 =
*     IT_FILTER               =
*     IS_SEL_HIDE             =
*     I_DEFAULT               = 'X'
      I_SAVE                  = 'A'
*     IS_VARIANT              =
*     IT_EVENTS               =
*     IT_EVENT_EXIT           =
*     IS_PRINT                =
*     IS_REPREP_ID            =
*     I_SCREEN_START_COLUMN   = 0
*     I_SCREEN_START_LINE     = 0
*     I_SCREEN_END_COLUMN     = 0
*     I_SCREEN_END_LINE       = 0
*     I_HTML_HEIGHT_TOP       = 0
*     I_HTML_HEIGHT_END       = 0
*     IT_ALV_GRAPHICS         =
*     IT_HYPERLINK            =
*     IT_ADD_FIELDCAT         =
*     IT_EXCEPT_QINFO         =
*     IR_SALV_FULLSCREEN_ADAPTER        =
* IMPORTING
*     E_EXIT_CAUSED_BY_CALLER =
*     ES_EXIT_CAUSED_BY_USER  =
    TABLES
      T_OUTTAB                = IT_TAB1
    EXCEPTIONS
      PROGRAM_ERROR           = 1
      OTHERS                  = 2.
  IF SY-SUBRC <> 0.
* MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO
*         WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4.
  ENDIF.

*ENDFORM.                    "SUMMARY
ENDFORM.
*&---------------------------------------------------------------------*
*&      Form  SAMPRATE2
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*  -->  p1        text
*  <--  p2        text
*----------------------------------------------------------------------*
*&---------------------------------------------------------------------*
*&      Form  SAMPRATE2
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*  -->  p1        text
*  <--  p2        text
*----------------------------------------------------------------------*
FORM SAMPRATE2 .
*  LOOP AT IT_MARA INTO WA_MARA.
  CLEAR : VBELN,GJAHR.
  READ TABLE IT_ZTP_COST11 INTO WA_ZTP_COST11 WITH KEY MATNR = WA_MAT1-MATNR FGLIFNR = WA_MAT1-FGLIFNR.
  IF SY-SUBRC EQ 0.
    VBELN = WA_ZTP_COST11-VBELN.
    GJAHR = WA_ZTP_COST11-GJAHR.
    WA_TAB2-COUNT = COUNT.
    WA_TAB2-MATNR = WA_ZTP_COST11-MATNR.
    WA_TAB2-WERKS = WA_ZTP_COST11-WERKS.
    WA_TAB2-VBELN = WA_ZTP_COST11-VBELN.
    WA_TAB2-GJAHR = WA_ZTP_COST11-GJAHR.
    WA_TAB2-FGLIFNR = WA_ZTP_COST11-FGLIFNR.
    SELECT SINGLE * FROM MAKT WHERE MATNR EQ WA_MAT1-MATNR AND SPRAS EQ 'EN'.
    IF SY-SUBRC EQ 0.
      WA_TAB2-MAKTX = MAKT-MAKTX.
    ENDIF.
    SELECT SINGLE * FROM LFA1 WHERE LIFNR EQ WA_ZTP_COST11-FGLIFNR.
    IF SY-SUBRC EQ 0.
      WA_TAB2-NAME1 = LFA1-NAME1.
    ENDIF.
    WA_TAB2-VAL1 = WA_ZTP_COST11-NET - WA_ZTP_COST11-GSTVAL1.
    SELECT SINGLE * FROM MVKE WHERE MATNR EQ WA_MAT1-MATNR.
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM TVM5T WHERE MVGR5 EQ MVKE-MVGR5.
      IF SY-SUBRC EQ 0.
        WA_TAB2-BEZEI = TVM5T-BEZEI.
      ENDIF.
    ENDIF.
    READ TABLE IT_ZPRODBATCHES INTO WA_ZPRODBATCHES WITH KEY MATNR = WA_MAT1-MATNR.
    IF SY-SUBRC EQ 0.
      WA_TAB2-SAMPCODE = WA_ZPRODBATCHES-COMB_MATNR1.
      SELECT SINGLE * FROM MAKT WHERE MATNR EQ WA_ZPRODBATCHES-COMB_MATNR1 AND SPRAS EQ 'EN'.
      IF SY-SUBRC EQ 0.
        WA_TAB2-SMAKTX = MAKT-MAKTX.
      ENDIF.
      READ TABLE IT_SZTP_COST11 INTO WA_SZTP_COST11 WITH KEY MATNR = WA_ZPRODBATCHES-COMB_MATNR1.
      IF SY-SUBRC EQ 0.
        WA_TAB2-ZSAM = WA_SZTP_COST11-NET - WA_SZTP_COST11-GSTVAL1.
        WA_TAB2-SVBELN = WA_SZTP_COST11-VBELN.
        WA_TAB2-SGJAHR = WA_SZTP_COST11-GJAHR.
      ENDIF.
      SELECT SINGLE * FROM MVKE WHERE MATNR EQ WA_ZPRODBATCHES-COMB_MATNR1.
      IF SY-SUBRC EQ 0.
        SELECT SINGLE * FROM TVM5T WHERE MVGR5 EQ MVKE-MVGR5.
        IF SY-SUBRC EQ 0.
          WA_TAB2-SBEZEI = TVM5T-BEZEI.
        ENDIF.
      ENDIF.
    ENDIF.
    COLLECT WA_TAB2 INTO IT_TAB2.
    DELETE IT_ZTP_COST11 WHERE VBELN EQ WA_TAB2-VBELN AND GJAHR EQ WA_TAB2-GJAHR.
    DELETE IT_SZTP_COST11 WHERE VBELN EQ WA_TAB2-SVBELN AND GJAHR EQ WA_TAB2-SGJAHR.
    CLEAR WA_TAB2.
    COUNT = COUNT + 1.
  ENDIF.

*  ENDLOOP.
ENDFORM.
*&---------------------------------------------------------------------*
*&      Form  BASERATE
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*  -->  p1        text
*  <--  p2        text
*----------------------------------------------------------------------*

*&---------------------------------------------------------------------*
*&      Form  FORM1
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*  -->  p1        text
*  <--  p2        text
*----------------------------------------------------------------------*
FORM FORM1 .
  CLEAR: IT_ZPRODBATCHES,WA_ZPRODBATCHES,IT_SZTP_COST11,WA_SZTP_COST11.
*  IF IT_MAT1 IS NOT INITIAL.
  SELECT * FROM ZPRODBATCHES INTO TABLE IT_ZPRODBATCHES WHERE MATNR EQ WA_MAT1-MATNR AND ENDDA GE SY-DATUM.
  SORT IT_ZPRODBATCHES DESCENDING BY BEGDA.
  IF IT_ZPRODBATCHES IS NOT INITIAL.
    SELECT * FROM ZTP_COST11 INTO TABLE IT_SZTP_COST11 FOR ALL ENTRIES IN IT_ZPRODBATCHES WHERE MATNR EQ IT_ZPRODBATCHES-COMB_MATNR1 AND
      FGLIFNR EQ WA_MAT1-FGLIFNR.
  ENDIF.
  SORT IT_ZTP_COST11 DESCENDING BY GJAHR VBELN.
  READ TABLE IT_ZTP_COST11 INTO DATA(wa) INDEX 1.
  SELECT SINGLE * from ZTP_COST14 INTO @DATA(wa_COST4) WHERE vbeln = @wa-VBELN and GJAHR = @wa-GJAHR.
    SHIFT wa_COST4-VBELN LEFT DELETING LEADING '0'.
*   footer = |CS no.{ wa_COST4-VBELN }/{ wa_COST4-GJAHR } ACC APR: { wa_COST4-ACCAPPROVER } Dt.{ wa_COST4-ACCTDT } TM.{ wa_COST4-ACCTTM } |
*                                  && |PUR APR: { wa_COST4-PURAPPROVER } Dt.{ wa_COST4-PURDT } TM.{ wa_COST4-PURTM }|.
   CLEAR: name11,name12.
    SELECT SINGLE * FROM pa0001 WHERE pernr eq wa_COST4-prod.
      if sy-subrc eq 0.
        name11 = pa0001-ename.
      endif.
      SELECT SINGLE * FROM pa0001 WHERE pernr eq wa_COST4-pur.
      if sy-subrc eq 0.
        name12 = pa0001-ename.
      endif.
      footer = |CS no.{ wa_COST4-VBELN }/{ wa_COST4-GJAHR } ACC APR: { name11 } Dt.{ wa_COST4-prodDT } TM.{ wa_COST4-prodTM } |
                                  && |PUR APR: { name12 } Dt.{ wa_COST4-PURDT } TM.{ wa_COST4-PURTM }|.
  SORT IT_SZTP_COST11 DESCENDING BY GJAHR VBELN.

*  PERFORM MRP.
  COUNT = 1.
*  DO 2 TIMES.
  CLEAR : IT_TAB1,WA_TAB1,IT_TAB2,WA_TAB2.
  PERFORM SAMPRATE1. "SALE
  PERFORM SAMPRATE2.  "SAMPLE
  CLEAR : IT_S1ZTP_COST12,WA_S1ZTP_COST12,IT_S2ZTP_COST12,WA_S2ZTP_COST12,IT_SM1ZTP_COST12,WA_SM1ZTP_COST12,IT_SM2ZTP_COST12,WA_SM2ZTP_COST12.
  SELECT * FROM ZTP_COST12 INTO TABLE IT_S1ZTP_COST12 FOR ALL ENTRIES IN IT_TAB1 WHERE GJAHR EQ IT_TAB1-GJAHR AND VBELN EQ IT_TAB1-VBELN.
  SELECT * FROM ZTP_COST12 INTO TABLE IT_S2ZTP_COST12 FOR ALL ENTRIES IN IT_TAB2 WHERE GJAHR EQ IT_TAB2-GJAHR AND VBELN EQ IT_TAB2-VBELN.
  SELECT * FROM ZTP_COST12 INTO TABLE IT_SM1ZTP_COST12 FOR ALL ENTRIES IN IT_TAB1 WHERE GJAHR EQ IT_TAB1-SGJAHR AND VBELN EQ IT_TAB1-SVBELN.
  SELECT * FROM ZTP_COST12 INTO TABLE IT_SM2ZTP_COST12 FOR ALL ENTRIES IN IT_TAB2 WHERE GJAHR EQ IT_TAB2-SGJAHR AND VBELN EQ IT_TAB2-SVBELN.
*  WRITE : / 'EXISITNG APPROVED RATES',60 'NEW RATES'.
  LOOP AT IT_TAB1 INTO WA_TAB1.
*    FORMAT COLOR 1.
*    WRITE : / 'INVOCE'.
    WA_TAB3-MATNR = WA_TAB1-MATNR.
    WA_TAB3-FGLIFNR = WA_TAB1-FGLIFNR.
    WA_TAB3-SAMPCODE = WA_TAB1-SAMPCODE.
    READ TABLE IT_TAB2 INTO WA_TAB2 WITH KEY MATNR = WA_TAB1-MATNR.
    IF SY-SUBRC EQ 0.
      WA_TAB3-VBELN = WA_TAB2-VBELN.
      WA_TAB3-SVBELN = WA_TAB2-SVBELN.
      WA_TAB3-GJAHR = WA_TAB2-GJAHR.
      WA_TAB3-SGJAHR = WA_TAB2-SGJAHR.
      WA_TAB3-VAL1 = WA_TAB2-VAL1.
      WA_TAB3-SVAL1 = WA_TAB2-ZSAM.
    ENDIF.
    WA_TAB3-NVBELN = WA_TAB1-VBELN.
    WA_TAB3-NSVBELN = WA_TAB1-SVBELN.
    WA_TAB3-NGJAHR = WA_TAB1-GJAHR.
    WA_TAB3-NSGJAHR = WA_TAB1-SGJAHR.
    WA_TAB3-NVAL1 = WA_TAB1-VAL1.
    WA_TAB3-NSVAL1 = WA_TAB1-ZSAM.
    WA_TAB3-BEZEI = WA_TAB1-BEZEI.
    WA_TAB3-SBEZEI = WA_TAB1-SBEZEI.
    CLEAR : RT1.
    IF  WA_TAB3-VAL1 GT 0.
      RT1 =  ( ( WA_TAB3-NVAL1 -  WA_TAB3-VAL1 ) /  WA_TAB3-VAL1 ) * 100.
    ENDIF.
    WA_TAB3-RT1 = RT1.

    COLLECT WA_TAB3 INTO IT_TAB3.
    CLEAR WA_TAB3.
  ENDLOOP.

*  SKIP.
*  ULINE.
*  FORMAT   COLOR 3.
*  WRITE : / 'REASON FOR CHANGE IN RATE'.
*  SKIP.
*  WRITE : / 'SALE COSTSHEET COMPARISION'.
*  FORMAT COLOR 1.
  LOOP AT IT_TAB1 INTO WA_TAB1.
    LOOP AT IT_S1ZTP_COST12 INTO WA_S1ZTP_COST12 WHERE GJAHR = WA_TAB1-GJAHR AND VBELN EQ WA_TAB1-VBELN.
      READ TABLE IT_S2ZTP_COST12 INTO WA_S2ZTP_COST12 WITH KEY POSNR = WA_S1ZTP_COST12-POSNR IDNRK = WA_S1ZTP_COST12-IDNRK.
      IF SY-SUBRC EQ 0.
        IF WA_S1ZTP_COST12-V2 NE WA_S2ZTP_COST12-V2.
*          WRITE : / WA_S2ZTP_COST12-IDNRK,WA_S2ZTP_COST12-RATE,WA_S2ZTP_COST12-V2,60 WA_S1ZTP_COST12-RATE LEFT-JUSTIFIED,WA_S1ZTP_COST12-V2.
          CLEAR : RT1.
*          RT1 =  ( ( WA_S1ZTP_COST12-RATE -  WA_S2ZTP_COST12-RATE ) /  WA_S2ZTP_COST12-RATE ) * 100.
          RT1 =  ( ( ( WA_S2ZTP_COST12-RATE -  WA_S1ZTP_COST12-RATE ) /  WA_S1ZTP_COST12-RATE ) * 100 ) * -1.
*          WRITE : rt1.
          IF RT1 NE 0.
            WA_RES1-MATNR = WA_TAB1-MATNR.
            WA_RES1-NVBELN = WA_TAB1-VBELN.
            WA_RES1-NGJAHR = WA_TAB1-GJAHR.
            WA_RES1-VBELN = WA_S2ZTP_COST12-VBELN.
            WA_RES1-GJAHR = WA_S2ZTP_COST12-GJAHR.
            WA_RES1-IDNRK = WA_S2ZTP_COST12-IDNRK.
            WA_RES1-POSNR = WA_S2ZTP_COST12-POSNR.
            WA_RES1-NRATE = WA_S1ZTP_COST12-RATE.
            WA_RES1-RATE = WA_S2ZTP_COST12-RATE.
            WA_RES1-RT = RT1.
            COLLECT WA_RES1 INTO IT_RES1.
            CLEAR WA_RES1.
          ENDIF.
        ENDIF.
      ENDIF.
    ENDLOOP.
  ENDLOOP.
*  SKIP.
*  ULINE.

*  FORMAT   COLOR 3.
*  WRITE : / 'SAMPLE COSTSHEET COMPARISION'.
*  FORMAT COLOR  4.
  LOOP AT IT_TAB1 INTO WA_TAB1.
    LOOP AT IT_SM1ZTP_COST12 INTO WA_SM1ZTP_COST12 WHERE GJAHR = WA_TAB1-SGJAHR AND VBELN EQ WA_TAB1-SVBELN.
      READ TABLE IT_SM2ZTP_COST12 INTO WA_SM2ZTP_COST12 WITH KEY POSNR = WA_SM1ZTP_COST12-POSNR IDNRK = WA_SM1ZTP_COST12-IDNRK.
      IF SY-SUBRC EQ 0.
        IF WA_SM1ZTP_COST12-V2 NE WA_SM2ZTP_COST12-V2.
*          WRITE : / WA_SM2ZTP_COST12-IDNRK,WA_SM2ZTP_COST12-RATE,WA_SM2ZTP_COST12-V2,60 WA_SM1ZTP_COST12-RATE LEFT-JUSTIFIED,WA_SM1ZTP_COST12-V2.
          CLEAR : RT1.
*          RT1 = ( ( WA_SM1ZTP_COST12-RATE - WA_SM2ZTP_COST12-RATE ) / WA_SM2ZTP_COST12-RATE ) * 100.
          RT1 = ( ( WA_SM1ZTP_COST12-RATE -  WA_SM2ZTP_COST12-RATE ) / WA_SM1ZTP_COST12-RATE ) * 100.
*          WRITE : rt1.
          IF RT1 NE 0.
            WA_SRES1-MATNR = WA_TAB1-SAMPCODE.
            WA_SRES1-NVBELN = WA_TAB1-SVBELN.
            WA_SRES1-NGJAHR = WA_TAB1-SGJAHR.
            WA_SRES1-VBELN = WA_SM2ZTP_COST12-VBELN.
            WA_SRES1-GJAHR = WA_SM2ZTP_COST12-GJAHR.
            WA_SRES1-IDNRK = WA_SM2ZTP_COST12-IDNRK.
            WA_SRES1-RATE = WA_SM2ZTP_COST12-RATE.
            WA_SRES1-NRATE = WA_SM1ZTP_COST12-RATE.
            WA_SRES1-RT = RT1.
            COLLECT WA_SRES1 INTO IT_SRES1.
            CLEAR WA_SRES1.
          ENDIF.
        ENDIF.
      ENDIF.
    ENDLOOP.
  ENDLOOP.


ENDFORM.
*&---------------------------------------------------------------------*
*&      Form  PRINT
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*  -->  p1        text
*  <--  p2        text
*----------------------------------------------------------------------*
FORM PRINT .
*  LOOP AT IT_TAB3 INTO WA_TAB3.
*    WRITE : / WA_TAB3-FGLIFNR,WA_TAB3-MATNR,WA_TAB3-RT1,WA_TAB3-VBELN,WA_TAB3-VAL1,WA_TAB3-NVBELN,WA_TAB3-NVAL1,
*                            WA_TAB3-SAMPCODE,WA_TAB3-SVBELN,WA_TAB3-SVAL1,WA_TAB3-NSVBELN,WA_TAB3-NSVAL1.
*    LOOP AT IT_RES1 INTO WA_RES1 WHERE MATNR = WA_TAB3-MATNR.
*      WRITE : /'sale', WA_RES1-IDNRK,WA_RES1-NRATE,WA_RES1-RATE,WA_RES1-RT.
*    ENDLOOP.
*    LOOP AT IT_SRES1 INTO WA_SRES1 WHERE MATNR = WA_TAB3-SAMPCODE.
*      WRITE : /'samp', WA_SRES1-IDNRK,WA_SRES1-NRATE,WA_SRES1-RATE,WA_SRES1-RT.
*    ENDLOOP.
*  ENDLOOP.

*  LOOP AT IT_TAB3 INTO WA_TAB3.
*    WRITE : / WA_TAB3-MATNR,WA_TAB3-VAL1,WA_TAB3-SVAL1,WA_TAB3-NVAL1,WA_TAB3-NSVAL1,WA_TAB3-RT1.
*
*    LOOP AT IT_RES1 INTO WA_RES1 WHERE MATNR = WA_TAB3-MATNR.
*      WRITE : /'sale', WA_RES1-IDNRK,WA_RES1-NRATE,WA_RES1-RATE,WA_RES1-RT.
*    ENDLOOP.
*    LOOP AT IT_SRES1 INTO WA_SRES1 WHERE MATNR = WA_TAB3-SAMPCODE.
*      WRITE : /'samp', WA_SRES1-IDNRK,WA_SRES1-NRATE,WA_SRES1-RATE,WA_SRES1-RT.
*    ENDLOOP.
*  ENDLOOP.

  SELECT SINGLE * FROM T247 WHERE SPRAS EQ 'EN' AND MNR EQ BUDAT-high+4(2).
  IF SY-SUBRC EQ 0.
    NMONTH1 = T247-KTX.
    CONCATENATE T247-LTX '''' BUDAT-high+0(4) INTO MON.
  ENDIF.

  IF P1 EQ 'X'.
    PERFORM PFORM1.
  ELSEIF P2 EQ 'X'.
    PERFORM PFORM2.
  ENDIF.


ENDFORM.
*&---------------------------------------------------------------------*
*&      Form  DATA1
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*  -->  p1        text
*  <--  p2        text
*----------------------------------------------------------------------*
FORM DATA1 .
  CLEAR : IT_TAB4,WA_TAB4.
  CLEAR : COUNT1.
  COUNT1 = 1.
  LOOP AT IT_TAB3 INTO WA_TAB3 WHERE FGLIFNR EQ WA_CHECK1-FGLIFNR.

*    WRITE : / COUNT1,WA_TAB3-MATNR,WA_TAB3-VAL1,WA_TAB3-SVAL1,WA_TAB3-NVAL1,WA_TAB3-NSVAL1,WA_TAB3-RT1.
    WA_TAB4-COUNT = COUNT1.
    WA_TAB4-MATNR = WA_TAB3-MATNR.
    SELECT SINGLE * FROM MAKT WHERE MATNR EQ WA_TAB3-MATNR AND SPRAS EQ 'EN'.
    IF SY-SUBRC EQ 0.
      WA_TAB4-MAKTX = MAKT-MAKTX.
    ENDIF.
    WA_TAB4-VAL1 = WA_TAB3-VAL1.
    WA_TAB4-SVAL1 = WA_TAB3-SVAL1.
    WA_TAB4-NVAL1 = WA_TAB3-NVAL1.
    WA_TAB4-NSVAL1 = WA_TAB3-NSVAL1.
    WA_TAB4-SLRT1 = WA_TAB3-RT1.
    IF WA_TAB3-RT1 GT 0.
      WA_TAB4-COL = 'R1'.
    ELSEIF WA_TAB3-RT1 LT 0.
      WA_TAB4-COL = 'G1'.
    ENDIF.
    CONDENSE : WA_TAB4-COUNT,WA_TAB4-MATNR,WA_TAB4-MAKTX,WA_TAB4-VAL1,WA_TAB4-SVAL1,WA_TAB4-NVAL1,WA_TAB4-NSVAL1,WA_TAB4-SLRT1.
    APPEND WA_TAB4 TO IT_TAB4.

    LOOP AT IT_RES1 INTO WA_RES1 WHERE MATNR = WA_TAB3-MATNR.
      WA_TAB4-COUNT = SPACE.
      WA_TAB4-MATNR = SPACE.
      WA_TAB4-MAKTX = SPACE.
      WA_TAB4-VAL1 = SPACE.
      WA_TAB4-SVAL1 = SPACE.
      WA_TAB4-NVAL1 = SPACE.
      WA_TAB4-NSVAL1 = SPACE.
      WA_TAB4-SLRT1 = SPACE.
      WA_TAB4-COL = SPACE.


*      WRITE : /'sale', WA_RES1-IDNRK,WA_RES1-NRATE,WA_RES1-RATE,WA_RES1-RT.
      WA_TAB4-IDNRK = WA_RES1-IDNRK.
      SELECT SINGLE * FROM MAKT WHERE MATNR EQ WA_RES1-IDNRK AND SPRAS EQ 'EN'.
      IF SY-SUBRC EQ 0.
        WA_TAB4-MAKTX1 = MAKT-MAKTX.
      ENDIF.
      WA_TAB4-NRATE = WA_RES1-NRATE.
      WA_TAB4-RATE = WA_RES1-RATE.
      WA_TAB4-RT1 = WA_RES1-RT.

      IF WA_RES1-RT GT 0.
        WA_TAB4-COL = 'R2'.
      ELSEIF WA_RES1-RT LT 0.
        WA_TAB4-COL = 'G2'.
      ENDIF.

      CONDENSE : WA_TAB4-COUNT,WA_TAB4-MATNR,WA_TAB4-MAKTX,WA_TAB4-VAL1,WA_TAB4-SVAL1,WA_TAB4-NVAL1,WA_TAB4-NSVAL1,WA_TAB4-SLRT1.
      CONDENSE: WA_TAB4-IDNRK,WA_TAB4-MAKTX1,WA_TAB4-NRATE,WA_TAB4-RATE,WA_TAB4-RT1.
      APPEND WA_TAB4 TO IT_TAB4.
    ENDLOOP.
    LOOP AT IT_SRES1 INTO WA_SRES1 WHERE MATNR = WA_TAB3-SAMPCODE.
      WA_TAB4-COUNT = SPACE.
      WA_TAB4-MATNR = SPACE.
      WA_TAB4-MAKTX = SPACE.
      WA_TAB4-VAL1 = SPACE.
      WA_TAB4-SVAL1 = SPACE.
      WA_TAB4-NVAL1 = SPACE.
      WA_TAB4-NSVAL1 = SPACE.
      WA_TAB4-SLRT1 = SPACE.
      WA_TAB4-COL = SPACE.

*      WRITE : /'samp', WA_SRES1-IDNRK,WA_SRES1-NRATE,WA_SRES1-RATE,WA_SRES1-RT.
      WA_TAB4-IDNRK = WA_SRES1-IDNRK.
      SELECT SINGLE * FROM MAKT WHERE MATNR EQ WA_SRES1-IDNRK AND SPRAS EQ 'EN'.
      IF SY-SUBRC EQ 0.
        CONCATENATE 'PS' MAKT-MAKTX INTO WA_TAB4-MAKTX1 SEPARATED BY SPACE.
      ENDIF.

      WA_TAB4-NRATE = WA_SRES1-NRATE.
      WA_TAB4-RATE = WA_SRES1-RATE.
      WA_TAB4-RT1 = WA_SRES1-RT.

      IF WA_SRES1-RT GT 0.
        WA_TAB4-COL = 'R2'.
      ELSEIF WA_SRES1-RT LT 0.
        WA_TAB4-COL = 'G2'.
      ENDIF.

      CONDENSE : WA_TAB4-COUNT,WA_TAB4-MATNR,WA_TAB4-MAKTX,WA_TAB4-VAL1,WA_TAB4-SVAL1,WA_TAB4-NVAL1,WA_TAB4-NSVAL1,WA_TAB4-SLRT1.
      CONDENSE: WA_TAB4-IDNRK,WA_TAB4-MAKTX1,WA_TAB4-NRATE,WA_TAB4-RATE,WA_TAB4-RT1.
      APPEND WA_TAB4 TO IT_TAB4.
    ENDLOOP.
    CLEAR WA_TAB4.
    COUNT1 = COUNT1 + 1.
  ENDLOOP.

ENDFORM.
*&---------------------------------------------------------------------*
*&      Form  PFORM1
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*  -->  p1        text
*  <--  p2        text
*----------------------------------------------------------------------*
FORM PFORM1 .
  CALL FUNCTION 'SSF_FUNCTION_MODULE_NAME'
    EXPORTING
*     formname           = 'ZCOST1'
*     FORMNAME           = 'ZCOST2'
      FORMNAME           = 'ZCOST7'
*     VARIANT            = ' '
*     DIRECT_CALL        = ' '
    IMPORTING
      FM_NAME            = V_FM
    EXCEPTIONS
      NO_FORM            = 1
      NO_FUNCTION_MODULE = 2
      OTHERS             = 3.

  CONTROL-NO_OPEN   = 'X'.
  CONTROL-NO_CLOSE  = 'X'.

  CALL FUNCTION 'SSF_OPEN'
    EXPORTING
      CONTROL_PARAMETERS = CONTROL.

  LOOP AT IT_CHECK1 INTO WA_CHECK1.
    SELECT SINGLE * FROM LFA1 WHERE LIFNR EQ WA_CHECK1-FGLIFNR.
    IF SY-SUBRC EQ 0.
      NAME1 = LFA1-NAME1.
    ENDIF.
    PERFORM DATA1.

    CALL FUNCTION V_FM
      EXPORTING
        CONTROL_PARAMETERS = CONTROL
        USER_SETTINGS      = 'X'
        OUTPUT_OPTIONS     = W_SSFCOMPOP
        NAME1              = NAME1
        MON                = MON
        sub = sub
*       MAKTX              = MAKTX
        footer = footer
      TABLES
        IT_TAB1            = IT_TAB4
      EXCEPTIONS
        FORMATTING_ERROR   = 1
        INTERNAL_ERROR     = 2
        SEND_ERROR         = 3
        USER_CANCELED      = 4
        OTHERS             = 5.
  ENDLOOP.

  CALL FUNCTION 'SSF_CLOSE'.
ENDFORM.
*&---------------------------------------------------------------------*
*&      Form  PFORM2
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*  -->  p1        text
*  <--  p2        text
*----------------------------------------------------------------------*
FORM PFORM2 .
  CALL FUNCTION 'SSF_FUNCTION_MODULE_NAME'
    EXPORTING
*     formname           = 'ZCOST1'
*     FORMNAME           = 'ZCOST2'
      FORMNAME           = 'ZCOST8'
*     VARIANT            = ' '
*     DIRECT_CALL        = ' '
    IMPORTING
      FM_NAME            = V_FM
    EXCEPTIONS
      NO_FORM            = 1
      NO_FUNCTION_MODULE = 2
      OTHERS             = 3.

  CONTROL-NO_OPEN   = 'X'.
  CONTROL-NO_CLOSE  = 'X'.

  CALL FUNCTION 'SSF_OPEN'
    EXPORTING
      CONTROL_PARAMETERS = CONTROL.

  LOOP AT IT_CHECK1 INTO WA_CHECK1.
    SELECT SINGLE * FROM LFA1 WHERE LIFNR EQ WA_CHECK1-FGLIFNR.
    IF SY-SUBRC EQ 0.
      NAME1 = LFA1-NAME1.
    ENDIF.

    PERFORM DATA2.

    CALL FUNCTION V_FM
      EXPORTING
        CONTROL_PARAMETERS = CONTROL
        USER_SETTINGS      = 'X'
        OUTPUT_OPTIONS     = W_SSFCOMPOP
        NAME1              = NAME1
        MON                = MON
        sub = sub
*       MAKTX              = MAKTX
             footer = footer
      TABLES
        IT_TAB1            = IT_TAB4
      EXCEPTIONS
        FORMATTING_ERROR   = 1
        INTERNAL_ERROR     = 2
        SEND_ERROR         = 3
        USER_CANCELED      = 4
        OTHERS             = 5.
  ENDLOOP.

  CALL FUNCTION 'SSF_CLOSE'.
ENDFORM.
*&---------------------------------------------------------------------*
*&      Form  DATA2
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*  -->  p1        text
*  <--  p2        text
*----------------------------------------------------------------------*
FORM DATA2 .
  CLEAR : IT_TAB4,WA_TAB4.
  CLEAR : COUNT1.
  COUNT1 = 1.
  LOOP AT IT_TAB3 INTO WA_TAB3 WHERE FGLIFNR EQ WA_CHECK1-FGLIFNR.
    IF WA_TAB3-MATNR GT 0.
      ON CHANGE OF WA_TAB3-MATNR.
*    CLEAR : SUBJECT.
        SELECT SINGLE * FROM ZTP_COST11 WHERE GJAHR = WA_TAB3-NGJAHR AND VBELN = WA_TAB3-NVBELN.
        IF SY-SUBRC EQ 0.
*        WA_ZTP_COST11-SUBJECT to WA_TAB4-SUBJECT.
          WA_TAB4-SUBJECT = ZTP_COST11-SUBJECT.
          CONDENSE WA_TAB4-SUBJECT.
        ENDIF.
        PACK WA_TAB3-VBELN TO WA_TAB3-VBELN.
        PACK WA_TAB3-SVBELN TO WA_TAB3-SVBELN.
        PACK WA_TAB3-NVBELN TO WA_TAB3-NVBELN.
        PACK WA_TAB3-NSVBELN TO WA_TAB3-NSVBELN.
        CONDENSE : WA_TAB3-VBELN,WA_TAB3-SVBELN,WA_TAB3-NVBELN,WA_TAB3-NSVBELN.
        CONCATENATE WA_TAB3-VBELN '/' WA_TAB3-GJAHR INTO WA_TAB4-CS.
        CONCATENATE WA_TAB3-SVBELN '/' WA_TAB3-SGJAHR INTO WA_TAB4-SCS.
        CONCATENATE WA_TAB3-NVBELN '/' WA_TAB3-NGJAHR INTO WA_TAB4-NCS.
        CONCATENATE WA_TAB3-NSVBELN '/' WA_TAB3-NSGJAHR INTO WA_TAB4-NSCS.
        WA_TAB4-COL = 'H1'.
        CONDENSE:  WA_TAB4-CS,WA_TAB4-SCS,WA_TAB4-NCS,WA_TAB4-NSCS.
        APPEND WA_TAB4 TO IT_TAB4.
      ENDON.
    ENDIF.
*    WRITE : / COUNT1,WA_TAB3-MATNR,WA_TAB3-VAL1,WA_TAB3-SVAL1,WA_TAB3-NVAL1,WA_TAB3-NSVAL1,WA_TAB3-RT1.
    WA_TAB4-COUNT = COUNT1.
    WA_TAB4-MATNR = WA_TAB3-MATNR.
    SELECT SINGLE * FROM MAKT WHERE MATNR EQ WA_TAB3-MATNR AND SPRAS EQ 'EN'.
    IF SY-SUBRC EQ 0.
      WA_TAB4-MAKTX = MAKT-MAKTX.
    ENDIF.
    WA_TAB4-VAL1 = WA_TAB3-VAL1.
    WA_TAB4-SVAL1 = WA_TAB3-SVAL1.
    WA_TAB4-NVAL1 = WA_TAB3-NVAL1.
    WA_TAB4-NSVAL1 = WA_TAB3-NSVAL1.
    WA_TAB4-SLRT1 = WA_TAB3-RT1.
    IF WA_TAB3-RT1 GT 0.
      WA_TAB4-COL = 'R1'.
    ELSEIF WA_TAB3-RT1 LT 0.
      WA_TAB4-COL = 'G1'.
    ELSE.
      WA_TAB4-COL = SPACE.
    ENDIF.
    CONDENSE : WA_TAB4-COUNT,WA_TAB4-MATNR,WA_TAB4-MAKTX,WA_TAB4-VAL1,WA_TAB4-SVAL1,WA_TAB4-NVAL1,WA_TAB4-NSVAL1,WA_TAB4-SLRT1.
    APPEND WA_TAB4 TO IT_TAB4.

    LOOP AT IT_RES1 INTO WA_RES1 WHERE MATNR = WA_TAB3-MATNR.
      WA_TAB4-COUNT = SPACE.
      WA_TAB4-MATNR = SPACE.
      WA_TAB4-MAKTX = SPACE.
      WA_TAB4-VAL1 = SPACE.
      WA_TAB4-SVAL1 = SPACE.
      WA_TAB4-NVAL1 = SPACE.
      WA_TAB4-NSVAL1 = SPACE.
      WA_TAB4-SLRT1 = SPACE.
      WA_TAB4-COL = SPACE.


*      WRITE : /'sale', WA_RES1-IDNRK,WA_RES1-NRATE,WA_RES1-RATE,WA_RES1-RT.
      WA_TAB4-IDNRK = WA_RES1-IDNRK.
      SELECT SINGLE * FROM MAKT WHERE MATNR EQ WA_RES1-IDNRK AND SPRAS EQ 'EN'.
      IF SY-SUBRC EQ 0.
        WA_TAB4-MAKTX1 = MAKT-MAKTX.
      ENDIF.
      WA_TAB4-NRATE = WA_RES1-NRATE.
      WA_TAB4-RATE = WA_RES1-RATE.
      WA_TAB4-RT1 = WA_RES1-RT.

      IF WA_RES1-RT GT 0.
        WA_TAB4-COL = 'R2'.
      ELSEIF WA_RES1-RT LT 0.
        WA_TAB4-COL = 'G2'.
      ELSE.
        WA_TAB4-COL = SPACE.
      ENDIF.

      CONDENSE : WA_TAB4-COUNT,WA_TAB4-MATNR,WA_TAB4-MAKTX,WA_TAB4-VAL1,WA_TAB4-SVAL1,WA_TAB4-NVAL1,WA_TAB4-NSVAL1,WA_TAB4-SLRT1.
      CONDENSE: WA_TAB4-IDNRK,WA_TAB4-MAKTX1,WA_TAB4-NRATE,WA_TAB4-RATE,WA_TAB4-RT1.
      APPEND WA_TAB4 TO IT_TAB4.
    ENDLOOP.
    LOOP AT IT_SRES1 INTO WA_SRES1 WHERE MATNR = WA_TAB3-SAMPCODE.
      WA_TAB4-COUNT = SPACE.
      WA_TAB4-MATNR = SPACE.
      WA_TAB4-MAKTX = SPACE.
      WA_TAB4-VAL1 = SPACE.
      WA_TAB4-SVAL1 = SPACE.
      WA_TAB4-NVAL1 = SPACE.
      WA_TAB4-NSVAL1 = SPACE.
      WA_TAB4-SLRT1 = SPACE.
      WA_TAB4-COL = SPACE.

*      WRITE : /'samp', WA_SRES1-IDNRK,WA_SRES1-NRATE,WA_SRES1-RATE,WA_SRES1-RT.
      WA_TAB4-IDNRK = WA_SRES1-IDNRK.
      SELECT SINGLE * FROM MAKT WHERE MATNR EQ WA_SRES1-IDNRK AND SPRAS EQ 'EN'.
      IF SY-SUBRC EQ 0.
        CONCATENATE 'PS' MAKT-MAKTX INTO WA_TAB4-MAKTX1 SEPARATED BY SPACE.
      ENDIF.

      WA_TAB4-NRATE = WA_SRES1-NRATE.
      WA_TAB4-RATE = WA_SRES1-RATE.
      WA_TAB4-RT1 = WA_SRES1-RT.

      IF WA_SRES1-RT GT 0.
        WA_TAB4-COL = 'R2'.
      ELSEIF WA_SRES1-RT LT 0.
        WA_TAB4-COL = 'G2'.
      ELSE.
        WA_TAB4-COL = SPACE.
      ENDIF.

      CONDENSE : WA_TAB4-COUNT,WA_TAB4-MATNR,WA_TAB4-MAKTX,WA_TAB4-VAL1,WA_TAB4-SVAL1,WA_TAB4-NVAL1,WA_TAB4-NSVAL1,WA_TAB4-SLRT1.
      CONDENSE: WA_TAB4-IDNRK,WA_TAB4-MAKTX1,WA_TAB4-NRATE,WA_TAB4-RATE,WA_TAB4-RT1.
      APPEND WA_TAB4 TO IT_TAB4.
    ENDLOOP.
    CLEAR WA_TAB4.
    COUNT1 = COUNT1 + 1.
  ENDLOOP.

*  BREAK-POINT .
ENDFORM.
