PROCESS BEFORE OUTPUT.
*&SPWIZARD: PBO FLOW LOGIC FOR TABLECONTROL 'TBC_9007'
  MODULE TBC_9007_CHANGE_TC_ATTR.
*&SPWIZARD: MODULE TBC_9007_CHANGE_COL_ATTR.
  LOOP AT   IT_EXTDEPT1
       INTO WA_EXTDEPT1
       WITH CONTROL TBC_9007
       CURSOR TBC_9007-CURRENT_LINE.
    MODULE TBC_9007_GET_LINES.
*&SPWIZARD:   MODULE TBC_9007_CHANGE_FIELD_ATTR
  ENDLOOP.






 MODULE STATUS_9007.
*
PROCESS AFTER INPUT.
*&SPWIZARD: PAI FLOW LOGIC FOR TABLECONTROL 'TBC_9007'
  LOOP AT IT_EXTDEPT1.
    CHAIN.
      FIELD WA_EXTDEPT1-MJAHR.
      FIELD WA_EXTDEPT1-MBLNR.
      FIELD WA_EXTDEPT1-DEPT.
      FIELD WA_EXTDEPT1-ENAME.
      FIELD WA_EXTDEPT1-DEPTNAME.
      FIELD WA_EXTDEPT1-APPROVE.
      FIELD WA_EXTDEPT1-ACCEPTNAME.
      FIELD WA_EXTDEPT1-ACCEPTDT.
      MODULE TBC_9007_MODIFY ON CHAIN-REQUEST.
    endchain.
    FIELD WA_EXTDEPT1-TICK
      MODULE TBC_9007_MARK ON REQUEST.
  ENDLOOP.
  MODULE TBC_9007_USER_COMMAND.
*&SPWIZARD: MODULE TBC_9007_CHANGE_TC_ATTR.
*&SPWIZARD: MODULE TBC_9007_CHANGE_COL_ATTR.




 MODULE USER_COMMAND_9007.
