*&---------------------------------------------------------------------*
*& Report  ZCUSTOMER_MAT_REP1
*& DEVELOPED BY JYOTSNA 03/2015
*&---------------------------------------------------------------------*
*& Date : 22.04.2024 / shraddhaP
*& TR - BCDK934886
*& Change - Add new div.70
*&---------------------------------------------------------------------*

REPORT  ZCUSTOMER_MAT_UPLOAD_1.
*,NO STANDARD PAGE HEADING LINE-SIZE 300.

TABLES : VBRK,
         VBRP,
         ZLOGUPD,
         MARA,
         YSD_INV_PER.

TYPES : BEGIN OF TYP_KONV,
          KNUMV TYPE prcd_elements-KNUMV,
          KPOSN TYPE prcd_elements-KPOSN,
          KSCHL TYPE prcd_elements-KSCHL,
          KWERT TYPE prcd_elements-KWERT,
        END OF TYP_KONV.

DATA : IT_VBRK    TYPE TABLE OF VBRK,
       WA_VBRK    TYPE VBRK,
       IT_VBRP    TYPE TABLE OF VBRP,
       WA_VBRP    TYPE VBRP,
       IT_KONV    TYPE TABLE OF TYP_KONV,
       WA_KONV    TYPE TYP_KONV,

       IT_VBRK1   TYPE TABLE OF VBRK,
       WA_VBRK1   TYPE VBRK,
       IT_VBRP1   TYPE TABLE OF VBRP,
       WA_VBRP1   TYPE VBRP,
       IT_KONV1   TYPE TABLE OF TYP_KONV,
       WA_KONV1   TYPE TYP_KONV,
       IT_KONV_C  TYPE TABLE OF TYP_KONV,
       WA_KONV_C  TYPE TYP_KONV,

       IT_VBRK_C  TYPE TABLE OF VBRK,
       WA_VBRK_C  TYPE VBRK,
       IT_VBRP_C  TYPE TABLE OF VBRP,
       WA_VBRP_C  TYPE VBRP,
       IT_VBRK_D  TYPE TABLE OF VBRK,
       WA_VBRK_D  TYPE VBRK,
       IT_VBRP_D  TYPE TABLE OF VBRP,
       WA_VBRP_D  TYPE VBRP,
       IT_MARC    TYPE TABLE OF MARC,
       WA_MARC    TYPE MARC,

       IT_ZLOGUPD TYPE TABLE OF ZLOGUPD,
       WA_ZLOGUPD TYPE ZLOGUPD.

TYPES : BEGIN OF ITAB1,
          KUNAG     TYPE VBRK-KUNAG,
          MATNR     TYPE VBRP-MATNR,
          FKIMG     TYPE VBRP-FKIMG,
          ED_RATE   TYPE prcd_elements-KWERT,
          ZPED_RATE TYPE prcd_elements-KWERT,
          ZGRP_RATE TYPE prcd_elements-KWERT,
        END OF ITAB1.

TYPES : BEGIN OF ITAB2,
          KUNAG TYPE VBRK-KUNAG,
          MATNR TYPE VBRP-MATNR,
          FKIMG TYPE VBRP-FKIMG,
          PTS   TYPE prcd_elements-KWERT,
*          INVCNT TYPE I,
        END OF ITAB2.

TYPES : BEGIN OF ITAC1,
          KUNAG TYPE VBRK-KUNAG,
          MATNR TYPE VBRP-MATNR,
          FKIMG TYPE VBRP-FKIMG,
          PTS   TYPE prcd_elements-KWERT,
          PTS1  TYPE prcd_elements-KWERT,
        END OF ITAC1.

TYPES : BEGIN OF IUPD1,
*          MONTH(2) TYPE C,
*          YEAR(4)  TYPE C,
          KUNAG  TYPE VBRK-KUNAG,
          MATNR  TYPE VBRP-MATNR,
          S_QTY  TYPE P,
          S_VAL  TYPE P,
          C_QTY  TYPE P,
          C_VAL  TYPE P,
          C_VAL1 TYPE P,
          D_QTY  TYPE P,
          D_VAL  TYPE P,
          INVCNT TYPE I,
        END OF IUPD1.

DATA : IT_TAB1 TYPE TABLE OF ITAB1,
       WA_TAB1 TYPE ITAB1,
       IT_NEP1 TYPE TABLE OF ITAB1,
       WA_NEP1 TYPE ITAB1,
       IT_TAB2 TYPE TABLE OF ITAB2,
       WA_TAB2 TYPE ITAB2,
       IT_TAC1 TYPE TABLE OF ITAC1,
       WA_TAC1 TYPE ITAC1,
       IT_TAD1 TYPE TABLE OF ITAC1,
       WA_TAD1 TYPE ITAC1,
       IT_UPD1 TYPE TABLE OF IUPD1,
       WA_UPD1 TYPE IUPD1.
TYPES: BEGIN OF SL1,
         KUNAG  TYPE VBRK-KUNAG,
         COUNT  TYPE I,
         NCOUNT TYPE I,
       END OF SL1.
DATA: IT_SL1 TYPE TABLE OF SL1,
      WA_SL1 TYPE SL1.

DATA : CNDT TYPE SY-DATUM.
DATA : ZSPD TYPE VBRP-NETWR,
       ZGRP TYPE VBRP-NETWR.

DATA : DATE1 TYPE SY-DATUM,
       DATE2 TYPE SY-DATUM,
       PTS   TYPE P.

DATA : ZLOGUPD_WA TYPE ZLOGUPD.
DATA: ZSTKSALE_WA TYPE ZSTKSALE.
DATA: ZSTKSALE1_WA TYPE ZSTKSALE1.

DATA: IT_ZDIST_SALE       TYPE TABLE OF ZDIST_SALE,
      WA_ZDIST_SALE       TYPE ZDIST_SALE,
      IT_YSD_CUS_DIV_DIS1 TYPE TABLE OF YSD_CUS_DIV_DIS,
      WA_YSD_CUS_DIV_DIS1 TYPE YSD_CUS_DIV_DIS.

TYPES : BEGIN OF DIST1,
          KUNAG TYPE ZDIST_SALE-KUNAG,
          MATNR TYPE ZDIST_SALE-MATNR,
          SPART TYPE MARA-SPART,
          NETWR TYPE ZDIST_SALE-NETWR,
          FKIMG TYPE P,
        END OF DIST1.

TYPES : BEGIN OF DIST2,
          KUNAG TYPE YSD_CUS_DIV_DIS-KUNNR,
          MATNR TYPE ZDIST_SALE-MATNR,
          SPART TYPE MARA-SPART,
          NETWR TYPE ZDIST_SALE-NETWR,
          FKIMG TYPE P,
        END OF DIST2.

TYPES : BEGIN OF DIST3,
          KUNAG TYPE YSD_CUS_DIV_DIS-KUNNR,
          MATNR TYPE ZDIST_SALE-MATNR,
          SPART TYPE MARA-SPART,
          S_VAL TYPE ZDIST_SALE-NETWR,
          S_QTY TYPE P,
        END OF DIST3.

DATA : IT_DIST1 TYPE TABLE OF DIST1,
       WA_DIST1 TYPE DIST1,
       IT_DIST2 TYPE TABLE OF DIST2,
       WA_DIST2 TYPE DIST2,
       IT_DIST3 TYPE TABLE OF DIST3,
       WA_DIST3 TYPE DIST3.

DATA : DISTVAL TYPE P DECIMALS 2,
       DISTQTY TYPE P.

DATA : COUNT TYPE ZLOGUPD-ZCOUNT.
DATA : TERM     LIKE USR41-TERMINAL,
       ZYEAR(4) TYPE C.

DATA: MONTH   TYPE ZCUMPSOW-ZMONTH,
      YEAR(4) TYPE C.

PARAMETERS : FROM_DT LIKE SY-DATUM,
             TO_DT   LIKE SY-DATUM.
*parameters : month   type zcumpsow-zmonth,
*             year(4) type c.

AT SELECTION-SCREEN OUTPUT.

  FROM_DT = SY-DATUM.
  FROM_DT+6(2) = '01'.
*  FROM_DT+4(2) = '03'.

  TO_DT = SY-DATUM.
*  TO_DT+6(2) = '31'.
*  TO_DT+4(2) = '03'.
*  TO_DT+0(4) = SY-DATUM+0(4).


  LOOP AT SCREEN.
    IF screen-name CP 'FROM_DT'.
      screen-active = 1.
      screen-input = 0.
      MODIFY SCREEN.
    ENDIF.
  ENDLOOP.

  LOOP AT SCREEN.
    IF screen-name CP 'TO_DT'.
      screen-active = 1.
      screen-input = 0.
      MODIFY SCREEN.
    ENDIF.
  ENDLOOP.

START-OF-SELECTION.

*  IF FROM_DT+6(2) NE '01'.
*    MESSAGE 'ENTER START DATE OF THE MONTH' TYPE 'E'.
*  ENDIF.
*  IF FROM_DT+4(2) NE SY-DATUM+4(2).
*    MESSAGE 'ENTER CURRENT MONTH' TYPE 'E'.
*  ENDIF.
*  IF FROM_DT+0(4) NE SY-DATUM+0(4).
*    MESSAGE 'ENTER CURRENT YEAR' TYPE 'E'.
*  ENDIF.
*  IF TO_DT NE SY-DATUM.
*    MESSAGE 'ENTER TODAYS DATE' TYPE 'E'.
*  ENDIF.


*  CALL FUNCTION 'TERMINAL_ID_GET'
*    IMPORTING
*      TERMINAL = TERM.

*  DATE1+6(2) = '01'.
*  DATE1+4(2) = MONTH.
*  DATE1+0(4) = YEAR.
*
*  CALL FUNCTION 'HR_JP_MONTH_BEGIN_END_DATE'
*    EXPORTING
*      IV_DATE           = DATE1
*    IMPORTING
**     EV_MONTH_BEGIN_DATE       =
*      EV_MONTH_END_DATE = DATE2.
*
*  WRITE : /'DATA UPLOADATION FORM ',DATE1,'TO',DATE2.
  DATE1 = FROM_DT.
  DATE2 = TO_DT.

  PERFORM SALE.
  PERFORM ZDISTSALE.  "added on 31.10.22
  PERFORM NEP_SALE.
  PERFORM CN.
  PERFORM DN.


  DELETE FROM ZSTKSALE.
  DELETE FROM ZSTKSALE1.

  LOOP AT IT_TAB2 INTO WA_TAB2.
*  WRITE : / WA_TAB2-KUNAG,WA_TAB2-MATNR,WA_TAB2-FKIMG,WA_TAB2-PTS.
*    WA_UPD1-MONTH = MONTH.
*    WA_UPD1-YEAR = YEAR.
    WA_UPD1-KUNAG = WA_TAB2-KUNAG.
    WA_UPD1-MATNR = WA_TAB2-MATNR.
    WA_UPD1-S_QTY = WA_TAB2-FKIMG.
    WA_UPD1-S_VAL = WA_TAB2-PTS.

    COLLECT WA_UPD1 INTO IT_UPD1.
    CLEAR WA_UPD1.
  ENDLOOP.

  LOOP AT IT_DIST3 INTO WA_DIST3.
*  WRITE : / WA_TAB2-KUNAG,WA_TAB2-MATNR,WA_TAB2-FKIMG,WA_TAB2-PTS.
*    WA_UPD1-MONTH = MONTH.
*    WA_UPD1-YEAR = YEAR.
    WA_UPD1-KUNAG = WA_DIST3-KUNAG.
    WA_UPD1-MATNR = WA_DIST3-MATNR.
    WA_UPD1-S_QTY = WA_DIST3-S_QTY.
    WA_UPD1-S_VAL = WA_DIST3-S_VAL.

    COLLECT WA_UPD1 INTO IT_UPD1.
    CLEAR WA_UPD1.
  ENDLOOP.

  LOOP AT IT_TAC1 INTO WA_TAC1.
*  WRITE : / 'cn',wa_tac1-kunag,wa_tac1-matnr,wa_tac1-fkimg,wa_tac1-pts.
*    WA_UPD1-MONTH = MONTH.
*    WA_UPD1-YEAR = YEAR.
    WA_UPD1-KUNAG = WA_TAC1-KUNAG.
    WA_UPD1-MATNR = WA_TAC1-MATNR.
    WA_UPD1-C_QTY = WA_TAC1-FKIMG.
    WA_UPD1-C_VAL = WA_TAC1-PTS.
    WA_UPD1-C_VAL1 = WA_TAC1-PTS1.

    COLLECT WA_UPD1 INTO IT_UPD1.
    CLEAR WA_UPD1.
  ENDLOOP.

  LOOP AT IT_TAD1 INTO WA_TAD1.
*  WRITE : / 'cn',wa_tac1-kunag,wa_tac1-matnr,wa_tac1-fkimg,wa_tac1-pts.
*    WA_UPD1-MONTH = MONTH.
*    WA_UPD1-YEAR = YEAR.
    WA_UPD1-KUNAG = WA_TAD1-KUNAG.
    WA_UPD1-MATNR = WA_TAD1-MATNR.
    WA_UPD1-D_QTY = WA_TAD1-FKIMG.
    WA_UPD1-D_VAL = WA_TAD1-PTS.

    COLLECT WA_UPD1 INTO IT_UPD1.
    CLEAR WA_UPD1.
  ENDLOOP.

  LOOP AT IT_UPD1 INTO WA_UPD1.
*    WRITE : / wa_upd1-kunag LEFT-JUSTIFIED,
*    wa_upd1-s_val LEFT-JUSTIFIED,   wa_upd1-s_qty LEFT-JUSTIFIED,
*     wa_upd1-c_val LEFT-JUSTIFIED,   wa_upd1-c_val1 LEFT-JUSTIFIED,  wa_upd1-c_qty LEFT-JUSTIFIED,
*    wa_upd1-d_val LEFT-JUSTIFIED,  wa_upd1-d_qty LEFT-JUSTIFIED.


    ZSTKSALE_WA-KUNAG = WA_UPD1-KUNAG.
    ZSTKSALE_WA-MATNR = WA_UPD1-MATNR.
    SELECT SINGLE * FROM MARA WHERE MATNR EQ WA_UPD1-MATNR.
    IF SY-SUBRC EQ 0.
      ZSTKSALE_WA-SPART = MARA-SPART.
    ENDIF.
    ZSTKSALE_WA-S_VAL = WA_UPD1-S_VAL.
    ZSTKSALE_WA-S_QTY = WA_UPD1-S_QTY.
    ZSTKSALE_WA-C_VAL = WA_UPD1-C_VAL.
    ZSTKSALE_WA-C_VAL1 = WA_UPD1-C_VAL1.
    ZSTKSALE_WA-C_QTY = WA_UPD1-C_QTY.
    ZSTKSALE_WA-D_VAL = WA_UPD1-D_VAL.
    ZSTKSALE_WA-D_QTY = WA_UPD1-D_QTY.

    ZSTKSALE_WA-CPUDT = SY-DATUM.
    ZSTKSALE_WA-CPUTM = SY-UZEIT.
    ZSTKSALE_WA-UNAME = SY-UNAME.

    MODIFY ZSTKSALE FROM ZSTKSALE_WA.
*    IF sy-subrc <> 0.
*      WRITE : /1 wa_upd1-kunag , 'not updated'.
*    ENDIF.
    CLEAR ZSTKSALE_WA.
    COMMIT WORK AND WAIT.
  ENDLOOP.

  SORT IT_SL1 BY KUNAG.
  LOOP AT IT_SL1 INTO WA_SL1.
    ZSTKSALE1_WA-KUNAG = WA_SL1-KUNAG.
    ZSTKSALE1_WA-INVNO = WA_SL1-COUNT.
    ZSTKSALE1_WA-NINVNO = WA_SL1-NCOUNT.
    ZSTKSALE1_WA-CPUDT = SY-DATUM.
    ZSTKSALE1_WA-CPUTM = SY-UZEIT.
    ZSTKSALE1_WA-UNAME = SY-UNAME.
    MODIFY ZSTKSALE1 FROM ZSTKSALE1_WA.
    CLEAR ZSTKSALE1_WA.
    COMMIT WORK AND WAIT.
  ENDLOOP.


***********update log in zlog_upd*********

*  IF sy-datum+4(2) GE '04'.
*    zyear = sy-datum+0(4).
*  ELSE.
*    zyear = sy-datum+0(4) - 1.
*  ENDIF.
*  CLEAR : count.
*
*  SELECT * FROM zlogupd INTO TABLE it_zlogupd WHERE zcyear EQ zyear.
*  SORT it_zlogupd BY zcount DESCENDING.
*  IF it_zlogupd IS NOT INITIAL.
*    READ TABLE it_zlogupd INTO wa_zlogupd WITH KEY zcyear = zyear.
*    IF sy-subrc EQ 0.
*      count = wa_zlogupd-zcount.
*      count = count + 1.
*    ELSE.
*      count = 1.
*    ENDIF.
*  ENDIF.
*  zlogupd_wa-zcyear = zyear.
*  zlogupd_wa-zcount = count.
*  zlogupd_wa-zmonth = month.
*  zlogupd_wa-zyear = year.
*  zlogupd_wa-tcode =  'ZSTKSALE'.
*  zlogupd_wa-ztable =  'ZSTKSALE'.
*  zlogupd_wa-entry_date = sy-datum.
*  zlogupd_wa-usnam = sy-uname.
*  zlogupd_wa-cputm =  sy-uzeit.
*  zlogupd_wa-hostaddr = term.
*  INSERT INTO  zlogupd VALUES  zlogupd_wa.
*  CLEAR zlogupd_wa.
*
*  IF sy-subrc EQ 0.
*    MESSAGE 'DATA UPDATED' TYPE 'I'.
*  ENDIF.
*  LEAVE TO SCREEN 0.

***************************************************

***TOP-OF-PAGE.
***  WRITE : /1 'CUSTOMER',33 'SALE_VAL',45 'SALE_QTY',
***  57 'CREDIT_VAL',69 'CREDIT_QTY',81 'DEBIT_VAL',93 'DEBIT_QTY'.
***  WRITE : /1 sy-uline(110).

*WRITE : / 'DATA UPLOADED IN TABLE zstkprd'.

*&---------------------------------------------------------------------*
*&      Form  sale
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
FORM SALE.
  SELECT * FROM VBRK INTO TABLE IT_VBRK WHERE FKDAT GE DATE1 AND FKDAT LE DATE2 AND FKART IN ('ZBDF','ZCDF') AND FKSTO NE 'X'.
  IF SY-SUBRC EQ 0.
*  select vbeln posnr fkimg matnr arktx charg pstyv werks lgort kzwi2 from vbrp into table it_vbrp for all entries in it_vbrk
    SELECT * FROM VBRP INTO TABLE IT_VBRP FOR ALL ENTRIES IN IT_VBRK WHERE  VBELN = IT_VBRK-VBELN AND FKIMG NE 0 AND PSTYV EQ 'ZAN'.
    IF SY-SUBRC NE 0.
      EXIT.
    ENDIF.
  ENDIF.
*
  IF IT_VBRK IS NOT INITIAL.
    SELECT KNUMV KPOSN KSCHL KWERT  FROM prcd_elements INTO TABLE IT_KONV FOR ALL ENTRIES IN IT_VBRK WHERE KNUMV = IT_VBRK-KNUMV AND KSCHL IN ('ZPED', 'ZEX4', 'ZGRP').
  ENDIF.

  SORT IT_KONV BY KNUMV KPOSN KSCHL.
  SORT IT_VBRP BY VBELN.
  DELETE IT_VBRP WHERE FKIMG EQ 0.
  IF IT_VBRK IS INITIAL.
    EXIT.
  ENDIF.
*
  IF IT_VBRP IS NOT INITIAL.
    LOOP AT IT_VBRP INTO WA_VBRP WHERE PSTYV = 'ZAN'.
      READ TABLE IT_VBRK INTO WA_VBRK WITH KEY VBELN = WA_VBRP-VBELN.
      IF SY-SUBRC EQ 0.
        WA_TAB1-KUNAG = WA_VBRK-KUNAG.
        WA_TAB1-MATNR = WA_VBRP-MATNR.
        WA_TAB1-FKIMG = WA_VBRP-FKIMG.
*        WA_TAB1-ZPED_RATE = WA_VBRP-NETWR + WA_VBRP-MWSBP.
        READ TABLE IT_KONV INTO WA_KONV WITH KEY KNUMV = WA_VBRK-KNUMV KPOSN = WA_VBRP-POSNR KSCHL = 'ZEX4' BINARY SEARCH.
        IF SY-SUBRC EQ 0.
          WA_TAB1-ED_RATE = WA_KONV-KWERT.
        ENDIF.
        READ TABLE IT_KONV INTO WA_KONV WITH KEY KNUMV = WA_VBRK-KNUMV KPOSN = WA_VBRP-POSNR KSCHL = 'ZPED' BINARY SEARCH.
        IF SY-SUBRC EQ 0.
          WA_TAB1-ZPED_RATE = WA_KONV-KWERT.
        ENDIF.
        READ TABLE IT_KONV INTO WA_KONV WITH KEY KNUMV = WA_VBRK-KNUMV KPOSN = WA_VBRP-POSNR KSCHL = 'ZGRP' BINARY SEARCH.
        IF SY-SUBRC EQ 0.
          WA_TAB1-ZGRP_RATE = WA_KONV-KWERT.
        ENDIF.
        COLLECT WA_TAB1 INTO IT_TAB1.
        CLEAR WA_TAB1.
      ENDIF.
    ENDLOOP.
  ENDIF.
  SORT IT_TAB1 BY KUNAG MATNR.

  CLEAR : IT_SL1,WA_SL1.
  CLEAR : COUNT.
  SORT IT_VBRK BY KUNAG.
  LOOP AT IT_VBRK INTO WA_VBRK.
    ON CHANGE OF WA_VBRK-KUNAG.
      COUNT = 0.
    ENDON.
    COUNT = COUNT + 1.
    AT END OF KUNAG.
      WA_SL1-KUNAG = WA_VBRK-KUNAG.
      WA_SL1-COUNT = COUNT.
      WA_SL1-NCOUNT = 0.
      COLLECT WA_SL1 INTO IT_SL1.
      CLEAR WA_SL1.
      COUNT = 0.
    ENDAT.
  ENDLOOP.

  LOOP AT IT_TAB1 INTO WA_TAB1.
    CLEAR PTS.
    WA_TAB2-KUNAG = WA_TAB1-KUNAG.
    WA_TAB2-MATNR = WA_TAB1-MATNR.
    WA_TAB2-FKIMG = WA_TAB1-FKIMG.
    CLEAR: PTS.
    PTS = WA_TAB1-ED_RATE + WA_TAB1-ZPED_RATE + WA_TAB1-ZGRP_RATE.
    WA_TAB2-PTS = PTS.
    COLLECT WA_TAB2 INTO IT_TAB2.
    CLEAR WA_TAB2.
  ENDLOOP.

*  LOOP AT IT_TAB2 INTO WA_TAB2.
*    READ TABLE IT_SL1 INTO WA_SL1 WITH KEY KUNAG = WA_TAB2-KUNAG.
*    IF SY-SUBRC EQ 0.
*      WA_TAB2-INVCNT = WA_SL1-COUNT.
*      MODIFY IT_TAB2 FROM WA_TAB2 TRANSPORTING INVCNT.
*      CLEAR WA_TAB2.
*    ENDIF.
*  ENDLOOP.
ENDFORM.                    "sale

FORM NEP_SALE.
  SELECT * FROM VBRK INTO TABLE IT_VBRK1 WHERE FKDAT GE DATE1 AND FKDAT LE DATE2 AND VBTYP EQ 'M' AND VKORG EQ '2000' AND  VTWEG EQ '20'
        AND KALSM EQ 'ZEXPNP' AND FKSTO NE 'X'.
  IF SY-SUBRC EQ 0.
    SELECT * FROM VBRP INTO TABLE IT_VBRP1 FOR ALL ENTRIES IN IT_VBRK1 WHERE VBELN EQ IT_VBRK1-VBELN AND FKIMG NE 0 AND PSTYV EQ 'TAN'.
  ENDIF.
  IF IT_VBRK1 IS NOT INITIAL.

    SELECT KNUMV KPOSN KSCHL KWERT FROM prcd_elements INTO TABLE IT_KONV1 FOR ALL ENTRIES IN IT_VBRK1 WHERE KNUMV = IT_VBRK1-KNUMV
      AND KSCHL EQ 'ZCIN'.
*      'JIN6','ZTOT','JIN1','ZC02','JIN5','ZCST','ZDIT','ZSPD','SKTV','Z004').
  ENDIF.


  LOOP AT IT_VBRP1 INTO WA_VBRP1.
    READ TABLE IT_VBRK1 INTO WA_VBRK1 WITH KEY VBELN = WA_VBRP1-VBELN.
    IF SY-SUBRC EQ 0.
*    WA_TAB1-VBELN = WA_VBRP-VBELN.
      WA_NEP1-KUNAG = '30004'.
      WA_NEP1-MATNR = WA_VBRP1-MATNR.
      WA_NEP1-MATNR+10(3) = '000'.
*      wa_NEP1-werks = wa_vbrp1-werks.
      IF WA_VBRP1-PSTYV EQ 'TAN'.
        WA_NEP1-FKIMG = WA_VBRP1-FKIMG.
        READ TABLE IT_KONV1 INTO WA_KONV1 WITH KEY KNUMV = WA_VBRK1-KNUMV KPOSN = WA_VBRP1-POSNR KSCHL = 'ZCIN'.
        IF SY-SUBRC EQ 0.
          WA_NEP1-ZPED_RATE = WA_KONV1-KWERT.
        ENDIF.
      ENDIF.
      WA_NEP1-FKIMG = WA_VBRP1-FKIMG.
      COLLECT WA_NEP1 INTO IT_NEP1.
      CLEAR WA_NEP1.
    ENDIF.
  ENDLOOP.


  CLEAR : COUNT.
  SORT IT_VBRK1 BY KUNAG.
  LOOP AT IT_VBRK1 INTO WA_VBRK1.
    ON CHANGE OF WA_VBRK1-KUNAG.
      COUNT = 0.
    ENDON.
    COUNT = COUNT + 1.
    AT END OF KUNAG.
      WA_SL1-KUNAG = WA_VBRK1-KUNAG.
      WA_SL1-COUNT = 0.
      WA_SL1-NCOUNT = COUNT.
      COLLECT WA_SL1 INTO IT_SL1.
      CLEAR WA_SL1.
      COUNT = 0.
    ENDAT.
  ENDLOOP.

  SORT IT_NEP1 BY KUNAG.
  LOOP AT IT_NEP1 INTO WA_NEP1.
    CLEAR : PTS.
    WA_TAB2-KUNAG = WA_NEP1-KUNAG.
    WA_TAB2-MATNR = WA_NEP1-MATNR.
    WA_TAB2-FKIMG = WA_NEP1-FKIMG.
    PTS =  WA_NEP1-ZPED_RATE.
    WA_TAB2-PTS = PTS.
    COLLECT WA_TAB2 INTO IT_TAB2.
    CLEAR WA_TAB2.
  ENDLOOP.

*  LOOP AT IT_TAB2 INTO WA_TAB2.
*    READ TABLE IT_SL1 INTO WA_SL1 WITH KEY KUNAG = WA_TAB2-KUNAG.
*    IF SY-SUBRC EQ 0.
*      WA_TAB2-INVCNT = WA_SL1-COUNT.
*      MODIFY IT_TAB2 FROM WA_TAB2 TRANSPORTING INVCNT.
*      CLEAR WA_TAB2.
*    ENDIF.
*  ENDLOOP.

****************

ENDFORM.                    "NEP_sale
*&---------------------------------------------------------------------*
*&      Form  cn
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
FORM CN.

  CNDT+0(4) = '2019'.
  CNDT+6(2) = '01'.
  CNDT+4(2) = '04'.

  SELECT * FROM VBRK INTO TABLE IT_VBRK_C WHERE FKDAT GE DATE1 AND FKDAT LE DATE2 AND FKSTO NE 'X' AND FKART
     IN ('ZG2','ZBD','ZRS','ZG3','RE','ZC04','ZQC','ZRRE','ZRRS','ZC08' ).
  IF SY-SUBRC EQ 0.
    SELECT * FROM VBRP INTO TABLE IT_VBRP_C FOR ALL ENTRIES IN IT_VBRK_C WHERE  VBELN = IT_VBRK_C-VBELN.
    IF SY-SUBRC EQ 0.
      SELECT * FROM MARC INTO TABLE IT_MARC FOR ALL ENTRIES IN IT_VBRP_C WHERE MATNR EQ IT_VBRP_C-MATNR
        AND WERKS EQ IT_VBRP_C-WERKS.
    ENDIF.
  ENDIF.
  IF IT_VBRK_C IS NOT INITIAL.
    SELECT KNUMV KPOSN KSCHL KWERT FROM KONV INTO TABLE IT_KONV_C FOR ALL ENTRIES IN IT_VBRK_C WHERE KNUMV = IT_VBRK_C-KNUMV
      AND KSCHL IN ('ZPED','ZSPD','ZGRP').
  ENDIF.
  SORT IT_KONV_C BY KNUMV KPOSN KSCHL.

  LOOP AT IT_VBRP_C INTO WA_VBRP_C.
    CLEAR : ZSPD, ZGRP.
    READ TABLE  IT_VBRK_C INTO WA_VBRK_C WITH KEY VBELN = WA_VBRP_C-VBELN.
    IF SY-SUBRC EQ 0.
      WA_TAC1-KUNAG = WA_VBRK_C-KUNAG.
      WA_TAC1-MATNR = WA_VBRP_C-MATNR.
      IF WA_VBRP_C-PSTYV EQ 'REN' OR WA_VBRP_C-PSTYV EQ 'G2N'.
        WA_TAC1-FKIMG = WA_VBRP_C-FKIMG.
      ENDIF.
*******************************************
      IF DATE1 LT CNDT.
        WA_TAC1-PTS = WA_VBRP_C-NETWR .
      ELSE.
        IF WA_VBRK_C-FKART EQ 'ZG2' OR WA_VBRK_C-FKART EQ 'ZBD'.
          READ TABLE IT_KONV_C INTO WA_KONV_C WITH KEY KNUMV = WA_VBRK_C-KNUMV KPOSN = WA_VBRP_C-POSNR KSCHL = 'ZSPD' BINARY SEARCH.
          IF SY-SUBRC EQ 0.
            ZSPD = WA_KONV_C-KWERT.
          ENDIF.
          READ TABLE IT_KONV_C INTO WA_KONV_C WITH KEY KNUMV = WA_VBRK_C-KNUMV KPOSN = WA_VBRP_C-POSNR KSCHL = 'ZGRP' BINARY SEARCH.
          IF SY-SUBRC EQ 0.
            ZGRP = WA_KONV_C-KWERT.
          ENDIF.
          WA_TAC1-PTS = ZGRP - ZSPD.
        ELSE.
          WA_TAC1-PTS = WA_VBRP_C-NETWR.
          IF WA_VBRK_C-FKART EQ 'ZC08'.
            WA_TAC1-PTS = 0.
          ENDIF.
        ENDIF.
      ENDIF.
*************************************debited cn****
      SELECT SINGLE * FROM YSD_INV_PER WHERE FKART EQ WA_VBRK_C-FKART AND ENDDA GE SY-DATUM.
      IF SY-SUBRC EQ 0.
        WA_TAC1-PTS1 = WA_TAC1-PTS * ( YSD_INV_PER-PERCNT / 100 ).
      ENDIF.

*      WA_TAC1-PTS = WA_VBRP_C-NETWR.
      COLLECT WA_TAC1 INTO IT_TAC1.
    ENDIF.
    CLEAR WA_TAC1.
  ENDLOOP.
  SORT IT_TAC1 BY KUNAG MATNR .
ENDFORM.                    "cn

*&---------------------------------------------------------------------*
*&      Form  dn
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
FORM DN.
  SELECT * FROM VBRK INTO TABLE IT_VBRK_D WHERE FKDAT GE DATE1 AND FKDAT LE DATE2 AND FKSTO NE 'X' AND
     FKART IN ( 'ZQD','ZDRA' ).
  IF SY-SUBRC EQ 0.
    SELECT * FROM VBRP INTO TABLE IT_VBRP_D FOR ALL ENTRIES IN IT_VBRK_D WHERE  VBELN = IT_VBRK_D-VBELN.
    IF SY-SUBRC EQ 0.
      SELECT * FROM MARC INTO TABLE IT_MARC FOR ALL ENTRIES IN IT_VBRP_D WHERE MATNR EQ IT_VBRP_D-MATNR
        AND WERKS EQ IT_VBRP_D-WERKS.
    ENDIF.
  ENDIF.
  LOOP AT IT_VBRP_D INTO WA_VBRP_D.
    READ TABLE  IT_VBRK_D INTO WA_VBRK_D WITH KEY VBELN = WA_VBRP_D-VBELN.
    IF SY-SUBRC EQ 0.
      WA_TAD1-KUNAG = WA_VBRK_D-KUNAG.
      WA_TAD1-MATNR = WA_VBRP_D-MATNR.
      IF WA_VBRP_D-PSTYV EQ 'L2N'.
        WA_TAD1-FKIMG = WA_VBRP_D-FKIMG.
      ENDIF.
      WA_TAD1-PTS = WA_VBRP_D-NETWR.
      COLLECT WA_TAD1 INTO IT_TAD1.
    ENDIF.
    CLEAR WA_TAD1.
  ENDLOOP.
  SORT IT_TAD1 BY KUNAG MATNR.
ENDFORM.                    "dn
*&---------------------------------------------------------------------*
*&      Form  ZDISTSALE
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*  -->  p1        text
*  <--  p2        text
*----------------------------------------------------------------------*
FORM ZDISTSALE .
  CLEAR :IT_ZDIST_SALE.
  CLEAR : IT_DIST1,WA_DIST1,IT_DIST2,WA_DIST2.
  SELECT * FROM ZDIST_SALE INTO TABLE IT_ZDIST_SALE WHERE FKDAT GE DATE1 AND FKDAT LE DATE2.
*     and flag eq space.
  IF IT_ZDIST_SALE IS NOT INITIAL.
    LOOP AT IT_ZDIST_SALE INTO WA_ZDIST_SALE.
      SELECT SINGLE * FROM MARA WHERE MATNR EQ WA_ZDIST_SALE-MATNR AND SPART IN ( '50','60','70' ).
      IF SY-SUBRC EQ 0.
*    wa_tab1-kunrg = wa_zdist_sale-kunrg.
        WA_DIST1-KUNAG = WA_ZDIST_SALE-KUNAG.
        WA_DIST1-MATNR = WA_ZDIST_SALE-MATNR.
        WA_DIST1-SPART = MARA-SPART.
        WA_DIST1-NETWR =   WA_ZDIST_SALE-NETWR.
        WA_DIST1-FKIMG =   WA_ZDIST_SALE-FKIMG.
        COLLECT WA_DIST1 INTO IT_DIST1.
        CLEAR WA_DIST1.
      ENDIF.
    ENDLOOP.
  ENDIF.

  CLEAR : IT_YSD_CUS_DIV_DIS1,WA_YSD_CUS_DIV_DIS1.
  IF IT_DIST1 IS NOT INITIAL.
    SELECT * FROM YSD_CUS_DIV_DIS INTO TABLE IT_YSD_CUS_DIV_DIS1 FOR ALL ENTRIES IN IT_DIST1 WHERE KUNNR EQ IT_DIST1-KUNAG AND SPART EQ IT_DIST1-SPART
      AND BEGDA GE DATE1 AND ENDDA LE DATE2.
  ENDIF.
  IF IT_YSD_CUS_DIV_DIS1 IS NOT INITIAL.
    LOOP AT IT_YSD_CUS_DIV_DIS1 INTO WA_YSD_CUS_DIV_DIS1.
      LOOP AT IT_DIST1 INTO WA_DIST1 WHERE KUNAG = WA_YSD_CUS_DIV_DIS1-KUNNR AND SPART = WA_YSD_CUS_DIV_DIS1-SPART.
        WA_DIST2-KUNAG  = WA_YSD_CUS_DIV_DIS1-KUNNR.
        WA_DIST2-MATNR = WA_DIST1-MATNR.
        CLEAR : DISTVAL,DISTQTY.
        DISTVAL = ( WA_DIST1-NETWR * ( WA_YSD_CUS_DIV_DIS1-PERCNT / 100 ) ).
        DISTQTY = ( WA_DIST1-FKIMG * ( WA_YSD_CUS_DIV_DIS1-PERCNT / 100 ) ).
        WA_DIST2-NETWR = DISTVAL.
        WA_DIST2-FKIMG = DISTQTY.
        COLLECT WA_DIST2 INTO IT_DIST2.
        CLEAR WA_DIST2.
      ENDLOOP.
    ENDLOOP.
  ENDIF.
  CLEAR : IT_DIST3,WA_DIST3.
  LOOP AT IT_DIST2 INTO WA_DIST2.
    WA_DIST3-KUNAG =  WA_DIST2-KUNAG.
    WA_DIST3-MATNR =  WA_DIST2-MATNR.
    WA_DIST3-S_VAL =  WA_DIST2-NETWR.
    WA_DIST3-S_QTY =  WA_DIST2-FKIMG.
    COLLECT WA_DIST3 INTO IT_DIST3.
    CLEAR WA_DIST3.
  ENDLOOP.



ENDFORM.
