PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZDEV1 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZDEV1-MBLNR .
    FIELD ZDEV1-MJAHR .
    FIELD ZDEV1-WERKS .
    FIELD ZDEV1-PERNR .
    FIELD ZDEV1-IBTRTL .
    FIELD ZDEV1-BUDAT .
    FIELD ZDEV1-UZEIT .
    FIELD ZDEV1-UNAME .
    FIELD ZDEV1-OCCDT .
    FIELD ZDEV1-PL .
    FIELD ZDEV1-UPL .
    FIELD ZDEV1-D1 .
    FIELD ZDEV1-D2 .
    FIELD ZDEV1-D3 .
    FIELD ZDEV1-D4 .
    FIELD ZDEV1-D5 .
    FIELD ZDEV1-D6 .
    FIELD ZDEV1-D7 .
    FIELD ZDEV1-D8 .
    FIELD ZDEV1-D9 .
    FIELD ZDEV1-DTEXT .
    FIELD ZDEV1-DEV1 .
    FIELD ZDEV1-DEV2 .
    FIELD ZDEV1-DEV3 .
    FIELD ZDEV1-DEV4 .
    FIELD ZDEV1-DEV5 .
    FIELD ZDEV1-DEV6 .
    FIELD ZDEV1-DEV7 .
    FIELD ZDEV1-DEV8 .
    FIELD ZDEV1-DEV9 .
    FIELD ZDEV1-DEV10 .
    FIELD ZDEV1-DSP1 .
    FIELD ZDEV1-DSP2 .
    FIELD ZDEV1-DSP3 .
    FIELD ZDEV1-DSP4 .
    FIELD ZDEV1-DSP5 .
    FIELD ZDEV1-RIC1 .
    FIELD ZDEV1-RIC2 .
    FIELD ZDEV1-RIC3 .
    FIELD ZDEV1-RIC4 .
    FIELD ZDEV1-RIC5 .
    FIELD ZDEV1-PID1 .
    FIELD ZDEV1-PID2 .
    FIELD ZDEV1-PID3 .
    FIELD ZDEV1-PID4 .
    FIELD ZDEV1-PID5 .
    FIELD ZDEV1-PID6 .
    FIELD ZDEV1-PID7 .
    FIELD ZDEV1-PID8 .
    FIELD ZDEV1-PID9 .
    FIELD ZDEV1-PID10 .
    FIELD ZDEV1-IRC1 .
    FIELD ZDEV1-IRC2 .
    FIELD ZDEV1-IRC3 .
    FIELD ZDEV1-IRC4 .
    FIELD ZDEV1-IRC5 .
    FIELD ZDEV1-IRC6 .
    FIELD ZDEV1-IRC7 .
    FIELD ZDEV1-IRC8 .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZDEV1-MBLNR .
    FIELD ZDEV1-MJAHR .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
