"Name: \PR:SAPLCSDI\FO:OKCODE_BEARBEITEN\SE:BEGIN\EI
ENHANCEMENT 0 ZDMS_GOS_CS01.


IF sy-tcode = 'CS01' OR sy-tcode = 'CS02' OR sy-tcode = 'CS03'.

DATA: Lo_GOS_MANAGER TYPE REF TO CL_GOS_MANAGER,
      LS_BORIDENT TYPE BORIDENT,
      lv_matnr TYPE matnr.

DATA: LT_SEL TYPE TGOS_SELS,
        LS_SEL TYPE SGOS_SELS.

LS_SEL-SIGN = 'I'.
    LS_SEL-OPTION = 'EQ'.
    LS_SEL-LOW = 'ARL_LINK'.
    LS_SEL-HIGH = 'ARL_LINK'.
    APPEND LS_SEL TO LT_SEL.
    CLEAR LS_SEL.
 LS_SEL-SIGN = 'I'.
    LS_SEL-OPTION = 'EQ'.
    LS_SEL-LOW = 'VIEW_ATTA'.
    LS_SEL-HIGH = 'VIEW_ATTA'.
    APPEND LS_SEL TO LT_SEL.
    CLEAR LS_SEL.

lv_matnr = RC29N-matnr.

CALL FUNCTION 'CONVERSION_EXIT_ALPHA_OUTPUT'
  EXPORTING
    INPUT         = lv_matnr
 IMPORTING
   OUTPUT        = lv_matnr.

CONCATENATE lv_matnr rc29n-WERKS rc29n-STLAN INTO LS_BORIDENT-OBJKEY.
CONDENSE LS_BORIDENT-OBJKEY.
LS_BORIDENT-OBJTYPE = 'BUS1080'.
CREATE OBJECT Lo_GOS_MANAGER
EXPORTING
IS_OBJECT = LS_BORIDENT
IT_SERVICE_SELECTION = LT_SEL
IP_NO_COMMIT = ' '
EXCEPTIONS
OBJECT_INVALID = 1.

ENDIF.

ENDENHANCEMENT.
