"Name: \PR:SAPLCHRG\FO:GET_CUSTOM_TAB\SE:BEGIN\EI
ENHANCEMENT 0 ZDMS_GOS_MSC1N.


IF sy-tcode = 'MSC1N' OR sy-tcode = 'MSC2N' OR sy-tcode = 'MSC3N'.

DATA: Lo_GOS_MANAGER TYPE REF TO CL_GOS_MANAGER,
      LS_BORIDENT TYPE BORIDENT,
      lv_matnr TYPE matnr.

DATA: LT_SEL TYPE TGOS_SELS,
        LS_SEL TYPE SGOS_SELS.

LS_SEL-SIGN = 'I'.
    LS_SEL-OPTION = 'EQ'.
    LS_SEL-LOW = 'ARL_LINK'.
    LS_SEL-HIGH = 'ARL_LINK'.
    APPEND LS_SEL TO LT_SEL.
    CLEAR LS_SEL.
 LS_SEL-SIGN = 'I'.
    LS_SEL-OPTION = 'EQ'.
    LS_SEL-LOW = 'VIEW_ATTA'.
    LS_SEL-HIGH = 'VIEW_ATTA'.
    APPEND LS_SEL TO LT_SEL.
    CLEAR LS_SEL.

lv_matnr = DFBATCH-MATNR.

CALL FUNCTION 'CONVERSION_EXIT_ALPHA_OUTPUT'
  EXPORTING
    INPUT         = lv_matnr
 IMPORTING
   OUTPUT        = lv_matnr.

     CONDENSE lv_matnr.
     CONCATENATE lv_matnr DFBATCH-WERKS DFBATCH-CHARG
     INTO LS_BORIDENT-OBJKEY.

 LS_BORIDENT-objtype = 'BUS1001002'.

CREATE OBJECT Lo_GOS_MANAGER
EXPORTING
        IS_OBJECT = LS_BORIDENT
*        IP_NO_COMMIT = 'R'
IT_SERVICE_SELECTION = LT_SEL
        IP_NO_COMMIT = 'X'

EXCEPTIONS
OBJECT_INVALID = 1.

ENDIF.

ENDENHANCEMENT.
