PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZDMS_GOS CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZDMS_GOS-DOC_KEY .
    FIELD ZDMS_GOS-DOKNR .
    FIELD ZDMS_GOS-ZFILE_NAME .
    FIELD ZDMS_GOS-ZUSERID .
    FIELD ZDMS_GOS-ZDATE .
    FIELD ZDMS_GOS-ZTIME .
    FIELD ZDMS_GOS-KEYVALUE .
    FIELD ZDMS_GOS-PERNR .
    FIELD ZDMS_GOS-ENAME .
    FIELD ZDMS_GOS-BTEXT .
    FIELD ZDMS_GOS-STAGE .
    FIELD ZDMS_GOS-FILENAME .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZDMS_GOS-DOC_KEY .
    FIELD ZDMS_GOS-DOKNR .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
