FUNCTION ZFM_JOURNALENTRYCREATE.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     VALUE(IP_JOURNALENTRY) TYPE  FINS_JOURNAL_ENTRY_CREATE_RE10
*"       OPTIONAL
*"     VALUE(IV_ENDPOINT) TYPE  STRING OPTIONAL
*"     VALUE(IV_USERNAME) TYPE  STRING OPTIONAL
*"     VALUE(IV_PASSWORD) TYPE  STRING OPTIONAL
*"     VALUE(IV_SOAP_ENVELOPE) TYPE  STRING OPTIONAL
*"     VALUE(V_SOAP_ACTION) TYPE  STRING OPTIONAL
*"  EXPORTING
*"     VALUE(EV_HTTP_STATUS) TYPE  I
*"     VALUE(EV_RESPONSE_RAW) TYPE  STRING
*"     VALUE(EV_ACCOUNTING_DOC) TYPE  BELNR_D
*"     VALUE(EV_COMP_CODE) TYPE  BUKRS
*"----------------------------------------------------------------------








ENDFUNCTION.
