DATA : UNIT2 TYPE STRING.
CLEAR: UNIT.
CLEAR :LW_T001W,LW_ADRC,GW_REG_ADR.
** -- SOC BY Snehal on 30.01.2025  **----
"Print 'ZD' partner Address

SELECT SINGLE VGBEL FROM VBRP INTO @DATA(LV_DEL_NO)
  WHERE  VBELN = @IS_HDREF-BIL_NUMBER.
  IF SY-SUBRC <> 0.
    CLEAR LV_DEL_NO.
    ELSE.
      SELECT SINGLE vbelv FROM lips INTO @DATA(lv_so_no)
        WHERE vbeln = @lv_del_no.
        if sy-subrc <> 0.
        clear lv_so_no.
        else.
      SELECT SINGLE ADRNR FROM VBPA INTO @DATA(LV_ADRNR1)
        WHERE VBELN = @LV_SO_NO
        AND PARVW = 'ZD'.
        IF SY-SUBRC <> 0.
          CLEAR LV_ADRNR1.
          ENDIF.
          endif.
    ENDIF.
** -- EOC BY Snehal on 30.01.2025  **----
SELECT SINGLE WERKS FROM VBRP INTO WERKS
  WHERE VBELN = IS_HDREF-BIL_NUMBER.
IF WERKS IS NOT INITIAL.

  SELECT SINGLE * FROM T001W
                INTO LW_T001W
                WHERE WERKS = WERKS.
  IF SY-SUBRC EQ 0.
    IF LV_ADRNR1 IS NOT INITIAL.
        SELECT SINGLE * FROM ADRC
             INTO LW_ADRC
             WHERE ADDRNUMBER = LV_ADRNR1.
      ELSE.
    SELECT SINGLE * FROM ADRC
             INTO LW_ADRC
             WHERE ADDRNUMBER = LW_T001W-ADRNR.
      ENDIF.
    IF SY-SUBRC EQ 0.
      DATA:LW_T005S TYPE T005U,
           LW_NAME  TYPE T005T-LANDX.
      SELECT SINGLE * FROM T005U
                      INTO LW_T005S
                      WHERE SPRAS = SY-LANGU
                      AND  LAND1 = LW_ADRC-COUNTRY
                      AND   BLAND = LW_ADRC-REGION.
      SELECT SINGLE LANDX FROM T005T
                    INTO LW_NAME
                    WHERE SPRAS = SY-LANGU
                    AND LAND1 = LW_ADRC-COUNTRY.
  CONCATENATE LW_ADRC-STR_SUPPL1 LW_ADRC-STR_SUPPL2
  LW_ADRC-POST_CODE1 INTO UNIT
  SEPARATED BY SPACE."
*GW_REG_ADR.

*  CONCATENATE GW_REG_ADR LW_T005S-BEZEI LW_NAME INTO GW_REG_ADR.
*  CONCATENATE unit LW_T005S-BEZEI LW_NAME 'T'
*  LW_ADRC-TEL_NUMBER 'F' LW_ADRC-FAX_NUMBER INTO unit
*   SEPARATED BY SPACE.
  CONCATENATE UNIT LW_T005S-BEZEI LW_NAME 'T'
  LW_ADRC-TEL_NUMBER  INTO UNIT
   SEPARATED BY SPACE.
*  CONCATENATE GW_REG_ADR 'T' LW_ADRC-TEL_NUMBER 'F'
*              TEL_NUMBER-FAX_NUMBER INTO GW_REG_ADR.

    ENDIF.

  ENDIF.
ENDIF.
SELECT SINGLE GSTIN FROM J_1BBRANCH INTO GSTIN
WHERE BRANCH = WERKS.
DATA : DEL TYPE LIKP-VBELN, UNIT1 TYPE STRING.
  SELECT SINGLE VGBEL FROM VBRP INTO DEL
    WHERE VBELN = IS_HDREF-BIL_NUMBER.
  SELECT SINGLE LGORT FROM LIPS INTO SLOC WHERE VBELN = DEL.
  IF SLOC = '1231'.
  UNIT = 'Plot No. 72, Mahul Village, Trombay, Chembur,' .
UNIT1 = 'Mumbai 400013, India'.
  CONCATENATE UNIT UNIT1 INTO UNIT SEPARATED BY SPACE.
  ENDIF.
IF SLOC = '1277' OR SLOC = '2210' OR SLOC = '2211' OR SLOC = '2266'.
  UNIT = 'A-22/2/1, MIDC, Mahad, 402309 Maharashtra' .
  UNIT1 = 'India T +91 2145 232548 F 02145-232208'.
  CONCATENATE UNIT UNIT1 INTO UNIT SEPARATED BY SPACE.
  ENDIF.

IF SLOC = '5002'.
*UNIT = 'Warehouse No I2,' .
*UNIT1 = 'Sai Dhara Warehousing Complex,NH3,'.
*UNIT2 = 'Bhoirgaon, Bhiwandi, Thane 421302, MH India'.
UNIT = 'BLR Logistics Ltd,'.
UNIT1 = 'Sumit Logistics & Industrial Park, Kuksa Borivali Village,'.
UNIT2 = 'Bhiwandi, Thane - 421302'.
  CONCATENATE UNIT UNIT1 UNIT2 INTO UNIT SEPARATED BY SPACE.
  ENDIF.
IF SLOC = '1904'.
UNIT1 = 'Plot No.72, Mahul Village, Trombay,'.
UNIT2 = 'Chembur East, Mumbai, Maharashtra, 400074'.
  CONCATENATE UNIT1 UNIT2 INTO UNIT SEPARATED BY SPACE.
ENDIF.


"Added by Arun m on 09.10.2024

      TYPES : BEGIN OF TY_VBRP,
              VBELN TYPE VBRP-VBELN,
              WERKS TYPE VBRP-WERKS,
              LGORT TYPE VBRP-LGORT,
              END OF TY_VBRP.

      DATA : IT_VBRP TYPE TABLE OF TY_VBRP,
             WA_VBRP TYPE  TY_VBRP.

      TYPES : BEGIN OF TY_TWLAD,
              WERKS TYPE TWLAD-WERKS,
              LGORT TYPE TWLAD-LGORT,
              ADRNR TYPE TWLAD-ADRNR,
              END OF TY_TWLAD.

     DATA : IT_TWLAD TYPE TABLE OF TY_TWLAD,
            WA_TWLAD TYPE TY_TWLAD.

     TYPES : BEGIN OF TY_ADRC,
             ADDRNUMBER TYPE ADRC-ADDRNUMBER,
             CITY1 TYPE ADRC-CITY1,
             POST_CODE1 TYPE ADRC-POST_CODE1,
             STREET TYPE ADRC-STREET,
             STR_SUPPL1 TYPE ADRC-STR_SUPPL1,
         STR_SUPPL2 TYPE ADRC-STR_SUPPL2,
         REGION TYPE ADRC-REGION,
         COUNTRY TYPE ADRC-COUNTRY,
         END OF TY_ADRC.

         TYPES : BEGIN OF TY_T005U,
               SPRAS TYPE T005U-SPRAS,
               LAND1 TYPE T005U-LAND1,
               BLAND TYPE T005U-BLAND,
               BEZEI TYPE T005U-BEZEI,
                END OF TY_T005U.

    DATA : IT_ADRC TYPE TABLE OF TY_ADRC,
           WA_ADRC TYPE          TY_ADRC.

    DATA : IT_BEZ TYPE TABLE OF TY_T005U,
           WA_BEZ TYPE TY_T005U.

    DATA : LV_WERKS TYPE VBRP-WERKS,
           LV_LGORT TYPE VBRP-LGORT,
           LV_ADRNR TYPE TWLAD-ADRNR,
           LV_STREET2 TYPE ADRC-STR_SUPPL1,
           LV_STREET3 TYPE  ADRC-STR_SUPPL2,
           LV_REG TYPE ADRC-REGION,
           LV_CONT TYPE ADRC-COUNTRY,
           LV_BEZ TYPE T005U-BEZEI.

 CLEAR : LV_CITY1,LV_POST_CODE1,LV_STREET.
*BREAK SALES.
IF WERKS = '1900' OR WERKS = '2001'.
*BREAK SALES.
    SELECT VBELN
           WERKS
           LGORT
           FROM VBRP
           INTO TABLE IT_VBRP
           WHERE VBELN = IS_HDREF-BIL_NUMBER
           AND   WERKS IN ('1900' , '2001').

 READ TABLE IT_VBRP INTO WA_VBRP WITH KEY VBELN = IS_HDREF-BIL_NUMBER.
 IF SY-SUBRC = 0.
    LV_WERKS = WA_VBRP-WERKS.
    LV_LGORT = WA_VBRP-LGORT.
ENDIF.

   SELECT WERKS
          LGORT
          ADRNR
          FROM TWLAD
          INTO TABLE IT_TWLAD
          WHERE WERKS = WA_VBRP-WERKS
          AND   LGORT = WA_VBRP-LGORT.

 READ TABLE IT_TWLAD INTO WA_TWLAD WITH KEY WERKS = WA_VBRP-WERKS
                                            LGORT = WA_VBRP-LGORT.
 IF SY-SUBRC = 0.

  LV_ADRNR = WA_TWLAD-ADRNR.

 ENDIF.

  SELECT ADDRNUMBER
         CITY1
         POST_CODE1
         STREET
         STR_SUPPL1
         STR_SUPPL2
         REGION
         COUNTRY
         FROM ADRC
         INTO TABLE IT_ADRC
         WHERE ADDRNUMBER = WA_TWLAD-ADRNR.





READ TABLE IT_ADRC INTO WA_ADRC WITH KEY ADDRNUMBER = WA_TWLAD-ADRNR.

 SELECT SPRAS LAND1 BLAND BEZEI  FROM T005U INTO TABLE IT_BEZ
      WHERE SPRAS = 'EN' AND
            LAND1 = WA_ADRC-COUNTRY AND
            BLAND = WA_ADRC-REGION.

READ TABLE IT_BEZ INTO WA_BEZ WITH KEY SPRAS = 'EN'
                                       LAND1 =  WA_ADRC-COUNTRY
                                       BLAND = WA_ADRC-REGION.

IF SY-SUBRC = 0.

 LV_CITY1 = WA_ADRC-CITY1.
 LV_POST_CODE1 = WA_ADRC-POST_CODE1.
 LV_STREET    = WA_ADRC-STREET.
 LV_STREET2 = WA_ADRC-STR_SUPPL1.
 LV_STREET3 = WA_ADRC-STR_SUPPL2.
 LV_REG = WA_ADRC-REGION.
 LV_CONT = WA_ADRC-COUNTRY.
 LV_BEZ = WA_BEZ-BEZEI.






CONCATENATE LV_STREET ',' LV_STREET3 ',' LV_CITY1 ','
LV_POST_CODE1 ','  LV_BEZ ',' LW_NAME
INTO UNIT SEPARATED BY SPACE.

ENDIF.
ENDIF.
"Ended by Arun m on 09.10.2024
