
CLEAR :LW_T001W,LW_ADRC,GW_REG_ADR.
*SELECT SINGLE WERKS FROM VBRP INTO WERKS
*WHERE VBELN = '1200'."IS_HDREF-BIL_NUMBER.
*IF WERKS IS NOT INITIAL.
  SELECT SINGLE * FROM T001W
  INTO LW_T001W
  WHERE WERKS = '1200'.
  IF SY-SUBRC EQ 0.
    SELECT SINGLE * FROM ADRC
    INTO LW_ADRC
    WHERE ADDRNUMBER = LW_T001W-ADRNR.
    IF SY-SUBRC EQ 0.
      DATA:LW_T005S TYPE T005U,
            LW_NAME  TYPE T005T-LANDX.
      SELECT SINGLE * FROM T005U
      INTO LW_T005S
      WHERE SPRAS = SY-LANGU
      AND  LAND1 = LW_ADRC-COUNTRY
      AND   BLAND = LW_ADRC-REGION.
    IF sy-subrc eq 0.
      STATE = LW_T005S-BEZEI.
    ENDIF.
      SELECT SINGLE LANDX FROM T005T
      INTO LW_NAME
      WHERE SPRAS = SY-LANGU
      AND LAND1 = LW_ADRC-COUNTRY.
      CONCATENATE LW_ADRC-STR_SUPPL1 LW_ADRC-STR_SUPPL2
      lw_adrc-POST_CODE1 INTO GW_REG_ADR.

 CONCATENATE GW_REG_ADR LW_T005S-BEZEI LW_NAME INTO GW_REG_ADR
      SEPARATED BY SPACE.
 CONCATENATE GW_REG_ADR 'T' LW_ADRC-TEL_NUMBER INTO GW_REG_ADR
       SEPARATED BY SPACE.
 CONCATENATE GW_REG_ADR 'F' LW_ADRC-FAX_NUMBER INTO GW_REG_ADR
      SEPARATED BY SPACE.
    ENDIF.

  ENDIF.
*ENDIF.

*GW_REG_ADR = 'ABSGC123'.


