
DATA:GS_VBRK TYPE VBRK,
     gs_KNVP TYPE KNVP,
     GS_KNA1 TYPE KNA1,
     GS_REGIO TYPE KNA1-REGIO,
*gs_KSCHL TYPE PRCD_ELEMENTS-KSCHL,
GS_LAND1 TYPE KNA1-LAND1,
     gs_J_1IMOCOMP TYPE J_1IMOCOMP,
     GS_T005U TYPE T005U.

SELECT SINGLE * FROM VBRK
INTO GS_VBRK
WHERE VBELN = GS_VBRP-VBELN.
IF SY-SUBRC EQ 0.

  SELECT SINGLE KSCHL FROM PRCD_ELEMENTS
  INTO  gs_KSCHL
  WHERE KNUMV = GS_VBRK-KNUMV
  and KSCHL = 'ZFR0'.

SELECT SINGLE LAND1 REGIO FROM KNA1
              INTO (GS_LAND1,GS_REGIO)
  WHERE KUNNR = GS_VBRK-KUNAG.
  IF SY-SUBRC EQ 0.
  if GS_VBRK-FKART = 'ZST1' or GS_VBRK-FKART = 'ZST2'.
    "soc sk
* SELECT SINGLE * FROM T005U
*               INTO GS_T005U
*  WHERE SPRAS = SY-LANGU
*  AND LAND1 = GS_LAND1
*  AND BLAND = GS_REGIO.
*    IF SY-SUBRC EQ 0.
*      CONCATENATE GS_T005U-BEZEI '(' GS_REGIO ')'
*      INTO EMPST SEPARATED BY SPACE.
*    ENDIF.
  " sk

 SELECT SINGLE * from vbfa INTO @data(wa_vbfa) WHERE VBELN =
@GS_VBRP-VBELN and VBTYP_V = 'J'.
   SELECT SINGLE * from lips INTO @data(wa_lips) WHERE VBELN =
@wa_vbfa-VBELV .
     SELECT single * from vbpa into @data(wa_vbpa) WHERE
 VBELN = @wa_lips-VBELN. "and PARVW = 'SP'.

SELECT SINGLE * FROM KNA1 INTO @DATA(WA_KUNNR) WHERE KUNNR =
@wa_vbpa-KUNNR.

SELECT SINGLE * FROM T005T INTO @DATA(WA_T005T)
  WHERE LAND1 = @WA_KUNNR-LAND1 AND SPRAS = @SY-LANGU.
  IF SY-SUBRC EQ 0.
 EMPST = WA_T005T-LANDX.
    ENDIF.








    ENDIF.
  ENDIF.
  IS_J_1IEXCHDR-EXDAT = GS_VBRK-ERDAT.
  IS_J_1IEXCHDR-CPUTM = GS_VBRK-ERZET.

  SELECT SINGLE * FROM VBRP
           INTO GS_VBrP
           WHERE VBELN = GS_VBRK-VBELN.
IF sy-subrc eq 0.

  SELECT SINGLE * FROM J_1IMOCOMP
                  INTO gs_J_1IMOCOMP
                  WHERE BUKRS = '1000'
                  AND  WERKS = GS_VBrP-werks.
IF sy-subrc eq 0.
 lw_J_1IPANNO = gs_J_1IMOCOMP-J_1IPANNO.
  ENDIF.
  ENDIF.



CLEAR gs_KNVP.
SELECT SINGLE * FROM KNVP
                into gs_KNVP
  WHERE KUNNR = GS_VBRK-KUNRG
  AND  VKORG = GS_VBRK-VKORG
  AND  VTWEG = GS_VBRK-VTWEG
  and  PARVW = 'AG'.
  IF sy-subrc eq 0.
    CLEAR GS_KNA1.
    SELECT SINGLE * FROM KNA1
           INTO GS_KNA1
  WHERE KUNNR = gs_KNVP-KUNN2.
    IF SY-SUBRC EQ 0.
*    LW_AG_PAN = GS_KNA1-J_1IPANNO.
*LW_WE_PAN

    ENDIF.
    ENDIF.

  SELECT SINGLE * FROM KNVP
  INTO gs_KNVP
  WHERE KUNNR = GS_VBRK-KUNRG
  AND  VKORG = GS_VBRK-VKORG
  AND  VTWEG = GS_VBRK-VTWEG
  AND  PARVW = 'WE'.
  IF sy-subrc EQ 0.
    SELECT SINGLE * FROM KNA1
    INTO GS_KNA1
    WHERE KUNNR = gs_KNVP-KUNN2.
    IF SY-SUBRC EQ 0.
*      LW_WE_PAN = GS_KNA1-J_1IPANNO.
    ENDIF.
  ENDIF.
ENDIF.
