*DATA : tt TYPE vbak-ZPAYMENT_TERMS_DES.
*CLEAR : V_DATE,WA_VTEXT.
*DATA : REGIO TYPE KNA1-REGIO.
*DATA : LAND1 TYPE KNA1-LAND1.
*DATA : WA_ZTERM TYPE VBKD-ZTERM,
*       WA_VALDT TYPE VBKD-VALDT.
*
*SELECT SINGLE VALDT ZTERM  FROM VBKD INTO (WA_VALDT, WA_ZTERM)
*     WHERE VBELN = IS_HDREF-ORDER_NUMB.
*
*SELECT SINGLE ZPAYMENT_TERMS_DES FROM VBAK INTO
*  tt WHERE VBELN = IS_HDREF-ORDER_NUMB.
*
*  SELECT SINGLE VTEXT FROM TVZBT INTO WA_VTEXT
*    WHERE ZTERM = WA_ZTERM
*     AND  SPRAS = 'EN'.
*
*IF tt = 'ACCR' OR TT = 'AICR'.
*  CONCATENATE WA_VTEXT 'Against L/C'
*  INTO WA_VTEXT SEPARATED BY SPACE.
*ENDIF.
*
*SELECT SINGLE FKDAT FROM VBRK INTO V_DATE
*    WHERE VBELN = IS_HDGEN-BIL_NUMBER .
*
*
*SELECT SINGLE ZTAG1 INTO DAYS FROM T052 WHERE ZTERM = WA_ZTERM  .
*
*IF SY-SUBRC <> 0 OR DAYS <= 0.
*  DAYS = '00'."gs_likp-wadat.
*ENDIF.
*
**SELECT SINGLE VALDT FROM VBKD
**  INTO  GS_VBKD-VALDT
**  WHERE VBELN = GS_VBRP-AUBEL AND POSNR = GS_VBRP-POSNR
**    AND VALDT NE SPACE.
**
**IF SY-SUBRC NE 0.
**  SELECT SINGLE VALDT FROM VBKD
**INTO  GS_VBKD-VALDT
**WHERE VBELN = GS_VBRP-AUBEL AND VALDT NE SPACE.
**ENDIF.
**  AND POSNR = GS_VBRP-posnr.
*IF WA_VALDT IS NOT INITIAL.
*  DUEDATE = WA_VALDT + DAYS.
*ELSE.
*  DUEDATE = V_DATE + DAYS.
**BREAK-POINT.
*ENDIF.
*IF GV_FKART = 'ZST1' OR GV_FKART = 'ZST2' OR GV_FKART = 'ZST3'.
*  PONO = IS_HDREF-PURCH_NO.
*SELECT SINGLE VBELV FROM VBFA INTO SONO WHERE VBELN = PONO.
*SELECT SINGLE AEDAT FROM EKKO INTO PODATE WHERE EBELN = PONO.
*SELECT SINGLE ERDAT FROM VBAK INTO SODATE WHERE VBELN = SONO.
*
*ENDIF.
*DATA : SOLDTO TYPE KNA1-KUNNR.
*DATA : SHIPTO TYPE KNA1-KUNNR.
*DATA : VKORG TYPE VBAK-VKORG, T TYPE VBKD-EMPST.
*DATA : IT_KNVP TYPE TABLE OF KNVP WITH HEADER LINE.
*DATA : IT_KNVP1 TYPE TABLE OF KNVP WITH HEADER LINE.
*DATA : GSTCODE TYPE ZSTATE_GST-GSTCODE.
*DATA : ZDESC TYPE ZSTATE_GST-ZDESC.
*IF GV_FKART NE 'ZST1'  AND GV_FKART NE 'ZST2' AND GV_FKART NE 'ZST3'.
*SELECT SINGLE KUNNR FROM VBPA INTO SOLDTO
*  WHERE VBELN = IS_HDREF-ORDER_NUMB AND PARVW = 'AG'.
*SELECT SINGLE KUNNR FROM VBPA INTO SHIPTO
*  WHERE VBELN = IS_HDREF-ORDER_NUMB AND PARVW = 'WE'.
*SELECT SINGLE EMPST FROM VBKD INTO T WHERE
*  VBELN = IS_HDREF-ORDER_NUMB AND POSNR NE ''.
*SELECT SINGLE GSTCODE ZDESC INTO (GSTCODE, ZDESC)
*  FROM ZSTATE_GST WHERE ZREGIO = T.
*IF SY-SUBRC = 0.
*CONCATENATE ZDESC '(' GSTCODE ')'
*INTO EMPST SEPARATED BY SPACE.
*ELSE.
*EMPST = T.
*ENDIF.
*ELSE.
*  SELECT SINGLE KUNNR FROM VBPA INTO SOLDTO
*  WHERE VBELN = SONO AND PARVW = 'AG'.
*SELECT SINGLE KUNNR FROM VBPA INTO SHIPTO
*  WHERE VBELN = SONO AND PARVW = 'WE'.
*SELECT SINGLE EMPST FROM VBKD INTO T WHERE
*  VBELN = SONO AND POSNR NE ''.
*SELECT SINGLE GSTCODE ZDESC INTO (GSTCODE, ZDESC)
*  FROM ZSTATE_GST WHERE ZREGIO = T.
*IF SY-SUBRC = 0.
*CONCATENATE ZDESC '(' GSTCODE ')'
*INTO EMPST SEPARATED BY SPACE.
*ELSE.
*EMPST = T.
*ENDIF.
*ENDIF.
*
*SELECT SINGLE STCD3 J_1IPANNO REGIO LAND1 FROM KNA1 INTO
*  (SOLDGST , LW_AG_PAN , REGIO , LAND1) WHERE
*  KUNNR = SOLDTO.
*SELECT SINGLE STCD3 J_1IPANNO
*   FROM KNA1 INTO (SHIPGST , LW_WE_PAN) WHERE
*  KUNNR = SHIPTO.
*DATA : GS_T005U TYPE T005U.
*SELECT SINGLE * FROM T005U
*               INTO GS_T005U
*  WHERE SPRAS = SY-LANGU
*  AND LAND1 = LAND1
*  AND BLAND = REGIO.
*    IF SY-SUBRC EQ 0.
*      CONCATENATE GS_T005U-BEZEI '(' REGIO ')'
*      INTO EMPST SEPARATED BY SPACE.
*    ENDIF.
*
**BREAK BASIS.
*DATA: IT_K TYPE TABLE OF KONV WITH HEADER LINE.
*DATA: KNUMV TYPE KONV-KNUMV.
*IF IS_HDREF-ORDER_NUMB IS NOT INITIAL.
*SELECT SINGLE KNUMV INTO KNUMV FROM VBAK
*  WHERE VBELN = IS_HDREF-ORDER_NUMB.
* SELECT * FROM KONV INTO CORRESPONDING FIELDS OF TABLE IT_K
* WHERE KNUMV = KNUMV AND KSCHL IN ('ZFRI' , 'ZPCH')
*   AND KBETR NE ''.
*ELSE.
*  SELECT SINGLE KNUMV INTO KNUMV FROM VBAK
*  WHERE VBELN = SONO.
* SELECT * FROM KONV INTO CORRESPONDING FIELDS OF TABLE IT_K
* WHERE KNUMV = KNUMV AND KSCHL IN ('ZFRI' , 'ZPCH')
*   AND KBETR NE ''.
*ENDIF.
*
*DATA : F TYPE C, P TYPE C.
*
*LOOP AT IT_K.
*CASE IT_K-KSCHL.
*  WHEN 'ZFRI'.
*    F = 'X'.
*  WHEN 'ZPCH'.
*    P = 'X'.
**  WHEN OTHERS.
*ENDCASE.
*ENDLOOP.
*DATA : F_DEC1 TYPE string ,F_DEC2 TYPE string..
*IF F = 'X' AND P = ''.
*F_DEC = 'We hereby declare that Basic Price Inclusive with Freight'.
*ELSEIF F = '' AND P = 'X'.
*F_DEC1 = 'We hereby declare that Basic Price Inclusive with'.
*f_dec2 = 'Packing Charges'.
*CONCATENATE F_DEC1 F_DEC2 INTO F_DEC SEPARATED BY SPACE.
*ELSEIF F = 'X' AND P = 'X'.
*F_DEC1 = 'We hereby declare that Basic Price Inclusive with'.
*F_DEC2 = 'Freight and Packing Charges'.
*CONCATENATE F_DEC1 F_DEC2 INTO F_DEC SEPARATED BY SPACE.
*ENDIF.
*DATA : ZM TYPE VBAK-ZMASK , m TYPE mara-matnr.
*if sono IS NOT INITIAL.
*SELECT SINGLE zmask INTO zm FROM vbak WHERE VBELN = sono.
*  IF zm = 'X'.
*    SELECT SINGLE matnr FROM vbap INTO m WHERE VBELN = sono.
*    SELECT SINGLE ZMAKTX INTO zmask FROM ZMASK_NAME WHERE ZMATNR = m.
*  ENDIF.
*endif.
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
