*&---------------------------------------------------------------------*
*& Report  ZLLM_FG_REGISTER_INV1
*&
*&---------------------------------------------------------------------*
*&
*&
*&---------------------------------------------------------------------*
REPORT ZLLM_FG_REGISTER_INV4 NO STANDARD PAGE HEADING LINE-SIZE 500.
TABLES : MSEG,
         MAKT,
         T001W,
         LFA1,
         MVKE,
         TVM5T.

TYPE-POOLS:  SLIS.

DATA: G_REPID     LIKE SY-REPID,
      FIELDCAT    TYPE SLIS_T_FIELDCAT_ALV,
      WA_FIELDCAT LIKE LINE OF FIELDCAT,
      SORT        TYPE SLIS_T_SORTINFO_ALV,
      WA_SORT     LIKE LINE OF SORT,
      LAYOUT      TYPE SLIS_LAYOUT_ALV.

DATA: IT_VBRK TYPE TABLE OF VBRK,
      WA_VBRK TYPE VBRK,
      IT_VBRP TYPE TABLE OF VBRP,
      WA_VBRP TYPE VBRP,
      IT_MKPF TYPE TABLE OF MKPF,
      WA_MKPF TYPE MKPF,
      IT_MSEG TYPE TABLE OF MSEG,
      WA_MSEG TYPE MSEG.
TYPES: BEGIN OF GRN1,
         MATNR TYPE MSEG-MATNR,
         CHARG TYPE MSEG-CHARG,
         MENGE TYPE MSEG-MENGE,
       END OF GRN1.
TYPES: BEGIN OF ITAB1,
         WERKS   TYPE VBRP-WERKS,
         FKART   TYPE VBRK-FKART,
         VBELN   TYPE VBRP-VBELN,
         FKDAT   TYPE VBRK-FKDAT,
         MATNR   TYPE VBRP-MATNR,
         CHARG   TYPE VBRP-CHARG,
         NETWR   TYPE VBRP-NETWR,
         MWSBP   TYPE VBRP-MWSBP,
         TWERKS  TYPE  T001W-WERKS,
         MAKTX   TYPE MAKT-MAKTX,
         OPQTY1  TYPE P,
         FKIMG   TYPE VBRP-FKIMG,
         REMQTY1 TYPE P,
         MBLNR   TYPE MSEG-MBLNR,
         LIFNR   TYPE MSEG-LIFNR,
         NAME1   TYPE LFA1-NAME1,
         EBELN   TYPE MSEG-EBELN,
         BEZEI   TYPE TVM5T-BEZEI,

       END OF ITAB1.
DATA: IT_GRN1 TYPE TABLE OF GRN1,
      WA_GRN1 TYPE GRN1,
      IT_TAB1 TYPE TABLE OF ITAB1,
      WA_TAB1 TYPE ITAB1.

DATA: LDATE1 TYPE SY-DATUM.
DATA: OPQTY1  TYPE P,
      REMQTY1 TYPE P,
      GRNQTY1 TYPE P,
      REMQTY2 TYPE P.
DATA: MBLNR TYPE MSEG-MBLNR.

SELECTION-SCREEN BEGIN OF BLOCK MERKMALE2 WITH FRAME TITLE TEXT-001.
PARAMETERS : R1 RADIOBUTTON GROUP R1,
             R2 RADIOBUTTON GROUP R1.
SELECTION-SCREEN END OF BLOCK MERKMALE2.

SELECTION-SCREEN BEGIN OF BLOCK MERKMALE1 WITH FRAME TITLE TEXT-001.
SELECT-OPTIONS : MATERIAL FOR MSEG-MATNR,
                 DATE1 FOR SY-DATUM,
                 PLANT FOR MSEG-WERKS.
PARAMETERS : VEN LIKE MSEG-LIFNR OBLIGATORY.
*                 MTART FOR MARA-MTART.
SELECTION-SCREEN END OF BLOCK MERKMALE1.

INITIALIZATION.
  G_REPID = SY-REPID.

START-OF-SELECTION.

  SELECT * FROM VBRK INTO TABLE IT_VBRK WHERE FKDAT IN DATE1 AND FKART IN ( 'ZSTO','ZSTI' ) AND FKSTO NE 'X'.
  IF SY-SUBRC EQ 0.
    SELECT * FROM VBRP INTO TABLE IT_VBRP FOR ALL ENTRIES IN IT_VBRK WHERE VBELN EQ IT_VBRK-VBELN AND WERKS IN PLANT AND MATNR IN MATERIAL.
  ENDIF.

  LDATE1 = DATE1-LOW - 360.

  SELECT * FROM MKPF INTO TABLE IT_MKPF WHERE VGART EQ 'WE' AND BUDAT GE LDATE1 AND BUDAT LE DATE1-HIGH.
  IF SY-SUBRC EQ 0.
    SELECT * FROM MSEG INTO TABLE IT_MSEG FOR ALL ENTRIES IN IT_MKPF WHERE MBLNR EQ IT_MKPF-MBLNR AND MJAHR EQ IT_MKPF-MJAHR AND BWART IN ('101','102')
      AND MATNR IN MATERIAL AND WERKS IN PLANT AND LIFNR EQ VEN .
    IF SY-SUBRC NE 0.
      MESSAGE 'NO DATA FOUND' TYPE 'I'.
    ENDIF.
  ENDIF.
  SORT IT_MSEG BY BUDAT_MKPF.
  SORT IT_VBRP BY MATNR CHARG.

  IF R2 EQ 'X'.

    PERFORM DETAILS.
  ELSE.

    PERFORM GRNDATA.
*    WRITE : /1 'PLANT', 6 'INV_DATE', 18 'INVOICE', 30 'PRODUCT_CODE',50 'BATCH',62 'TAXABLE_VAL',82 'TAX',100 'TO_PLANT',115 'PRODUCT_NAME',
*    150 'OP_BAL',170 'INV_QTY', 190 'BAL_QTY',210 'GRN_NO',222 'VENDOR_CODE',235 'VENDOR_NAME',250 'PO'.
*    ULINE.
    FORMAT COLOR 1.
    LOOP AT IT_VBRP INTO WA_VBRP.
      READ TABLE IT_VBRK INTO WA_VBRK WITH KEY VBELN = WA_VBRP-VBELN.
      IF SY-SUBRC EQ 0.
        WRITE : /1 WA_VBRP-WERKS,6 WA_VBRK-FKART,18 WA_VBRP-VBELN,30 WA_VBRK-FKDAT,45 WA_VBRP-MATNR LEFT-JUSTIFIED,55 WA_VBRP-CHARG,67 WA_VBRP-NETWR LEFT-JUSTIFIED,
        82 WA_VBRP-MWSBP LEFT-JUSTIFIED.
        WA_TAB1-WERKS = WA_VBRP-WERKS.
        WA_TAB1-FKART = WA_VBRK-FKART.
        WA_TAB1-VBELN = WA_VBRP-VBELN.
        WA_TAB1-FKDAT = WA_VBRK-FKDAT.
        WA_TAB1-MATNR = WA_VBRP-MATNR.
        WA_TAB1-CHARG = WA_VBRP-CHARG.
        WA_TAB1-NETWR = WA_VBRP-NETWR.
        WA_TAB1-MWSBP = WA_VBRP-MWSBP.
        SELECT SINGLE * FROM T001W WHERE KUNNR EQ WA_VBRK-KUNAG.
        IF SY-SUBRC EQ 0.
          WRITE : 100 T001W-WERKS.
          WA_TAB1-TWERKS = T001W-WERKS.
        ENDIF.
        SELECT SINGLE * FROM MAKT WHERE MATNR EQ WA_VBRP-MATNR AND SPRAS EQ 'EN'.
        IF SY-SUBRC EQ 0.
          WRITE : 106 MAKT-MAKTX.
          WA_TAB1-MAKTX = MAKT-MAKTX.
        ENDIF.
        ON CHANGE OF WA_VBRP-CHARG.
          CLEAR: REMQTY1,OPQTY1.
        ENDON.
        ON CHANGE OF WA_VBRP-CHARG.
          READ TABLE IT_GRN1 INTO WA_GRN1 WITH KEY MATNR = WA_VBRP-MATNR CHARG = WA_VBRP-CHARG.
          IF SY-SUBRC EQ 0.
*          WRITE : 'grn',WA_GRN1-MENGE.
            OPQTY1 = WA_GRN1-MENGE.
          ENDIF.
        ENDON.

        WRITE : 150 OPQTY1 LEFT-JUSTIFIED,170  WA_VBRP-FKIMG LEFT-JUSTIFIED.
        WA_TAB1-OPQTY1 = OPQTY1.
        WA_TAB1-FKIMG = WA_VBRP-FKIMG.
        REMQTY1 = OPQTY1 - WA_VBRP-FKIMG.
        WRITE : 190 REMQTY1 LEFT-JUSTIFIED.
        WA_TAB1-REMQTY1 = REMQTY1.
        OPQTY1 = REMQTY1.
        READ TABLE IT_MSEG INTO WA_MSEG WITH KEY MATNR = WA_VBRP-MATNR CHARG = WA_VBRP-CHARG BWART = '101'.
        IF SY-SUBRC EQ 0.
          WRITE : 210 WA_MSEG-MBLNR,222 WA_MSEG-LIFNR.
          WA_TAB1-MBLNR = WA_MSEG-MBLNR.
          WA_TAB1-LIFNR = WA_MSEG-LIFNR.
          SELECT SINGLE * FROM LFA1 WHERE LIFNR EQ WA_MSEG-LIFNR.
          IF SY-SUBRC EQ 0.
            WRITE : 235 LFA1-NAME1.
            WA_TAB1-NAME1 = LFA1-NAME1.
          ENDIF.
          WRITE : 275 WA_MSEG-EBELN.
          WA_TAB1-EBELN = WA_MSEG-EBELN.
        ENDIF.
        SELECT SINGLE * FROM MVKE WHERE MATNR EQ WA_TAB1-MATNR.
        IF SY-SUBRC EQ 0.
          SELECT SINGLE * FROM TVM5T WHERE SPRAS EQ 'EN' AND MVGR5 EQ MVKE-MVGR5.
          IF SY-SUBRC EQ 0.
            WA_TAB1-BEZEI = TVM5T-BEZEI.
          ENDIF.
        ENDIF.

        COLLECT WA_TAB1 INTO IT_TAB1.
        CLEAR WA_TAB1.
      ENDIF.
    ENDLOOP.

    PERFORM ALV.

  ENDIF.
*&---------------------------------------------------------------------*
*&      Form  GRNDATA
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*  -->  p1        text
*  <--  p2        text
*----------------------------------------------------------------------*
FORM GRNDATA .
*  IF IT_VBRP IS NOT INITIAL.
*    LOOP AT IT_VBRP INTO WA_VBRP.
*      READ TABLE IT_VBRK INTO WA_VBRK WITH KEY VBELN = WA_VBRP-VBELN.
*      IF SY-SUBRC EQ 0.
  LOOP AT IT_MSEG INTO WA_MSEG .
*          WHERE MATNR = WA_VBRP-MATNR AND CHARG = WA_VBRP-CHARG AND BUDAT_MKPF LE WA_VBRK-FKDAT.
    IF WA_MSEG-BWART EQ '102'.
      WA_MSEG-MENGE = WA_MSEG-MENGE * ( - 1 ).
    ENDIF.
    WA_GRN1-MATNR = WA_MSEG-MATNR.
    WA_GRN1-CHARG = WA_MSEG-CHARG.
    WA_GRN1-MENGE = WA_MSEG-MENGE.
    COLLECT WA_GRN1 INTO IT_GRN1.
    CLEAR WA_GRN1.
  ENDLOOP.
*      ENDIF.
*    ENDLOOP.
*  ENDIF.
ENDFORM.
*&---------------------------------------------------------------------*
*&      Form  DETAILS
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*  -->  p1        text
*  <--  p2        text
*----------------------------------------------------------------------*
FORM DETAILS .
  LOOP AT IT_VBRP INTO WA_VBRP.
    READ TABLE IT_VBRK INTO WA_VBRK WITH KEY VBELN = WA_VBRP-VBELN.
    IF SY-SUBRC EQ 0.
      FORMAT COLOR 1.
      WRITE : / WA_VBRP-VBELN,WA_VBRP-MATNR,WA_VBRP-CHARG.
      LOOP AT IT_MSEG INTO WA_MSEG WHERE MATNR EQ WA_VBRP-MATNR AND CHARG = WA_VBRP-CHARG.
        IF WA_MSEG-BWART EQ '102'.
          WA_MSEG-MENGE = WA_MSEG-MENGE * ( - 1 ).
        ENDIF.
        FORMAT COLOR 2.
        WRITE : / 'GRN',WA_MSEG-MBLNR,WA_MSEG-BWART,WA_MSEG-MATNR,WA_MSEG-CHARG,WA_MSEG-MENGE.
      ENDLOOP.
    ENDIF.
  ENDLOOP.


ENDFORM.

TOP-OF-PAGE.
  FORMAT COLOR 3.
  WRITE : /1 'PLANT', 6 'INV_TYP', 18 'INVOICE', 30 'INV_DATE', 45 'PR_CODE',55 'BATCH',67 'TAXABLE_VAL',82 'TAX',100 'TO_PLANT',115 'PRODUCT_NAME',
    150 'OP_BAL',170 'INV_QTY', 190 'BAL_QTY',210 'GRN_NO',222 'VENDOR_CODE',235 'VENDOR_NAME',275 'PO'.
  ULINE.
*&---------------------------------------------------------------------*
*&      Form  ALV
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*  -->  p1        text
*  <--  p2        text
*----------------------------------------------------------------------*
FORM ALV .


  WA_FIELDCAT-FIELDNAME = 'WERKS'.
  WA_FIELDCAT-SELTEXT_L = 'FROM_PLANT'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'FKART'.
  WA_FIELDCAT-SELTEXT_L = 'INV TYPE'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'VBELN'.
  WA_FIELDCAT-SELTEXT_L = 'INVOICE'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'FKDAT'.
  WA_FIELDCAT-SELTEXT_L = 'INV DATE'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'MATNR'.
  WA_FIELDCAT-SELTEXT_L = 'PRODUCT CODE'.
  APPEND WA_FIELDCAT TO FIELDCAT.

   WA_FIELDCAT-FIELDNAME = 'BEZEI'.
  WA_FIELDCAT-SELTEXT_L = 'PACK SIZE'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'CHARG'.
  WA_FIELDCAT-SELTEXT_L = 'BATCH'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'NETWR'.
  WA_FIELDCAT-SELTEXT_L = 'PTS VALUE'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'MWSBP'.
  WA_FIELDCAT-SELTEXT_L = 'TAX VALUE'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'TWERKS'.
  WA_FIELDCAT-SELTEXT_L = 'TO PLANT'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'MAKTX'.
  WA_FIELDCAT-SELTEXT_L = 'PRODUCT NAME'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'OPQTY1'.
  WA_FIELDCAT-SELTEXT_L = 'OPENING QTY'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'FKIMG'.
  WA_FIELDCAT-SELTEXT_L = 'INV QTY'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'REMQTY1'.
  WA_FIELDCAT-SELTEXT_L = 'REMAINING QTY'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'MBLNR'.
  WA_FIELDCAT-SELTEXT_L = 'GRN NO.'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'LIFNR'.
  WA_FIELDCAT-SELTEXT_L = 'VENDOR CODE'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'NAME1'.
  WA_FIELDCAT-SELTEXT_L = 'VENDOR NAME'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'EBELN'.
  WA_FIELDCAT-SELTEXT_L = 'PO NO.'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  LAYOUT-ZEBRA = 'X'.
  LAYOUT-COLWIDTH_OPTIMIZE = 'X'.
  LAYOUT-WINDOW_TITLEBAR  = 'LLM INVOICE DETAILS'.


  CALL FUNCTION 'REUSE_ALV_GRID_DISPLAY'
    EXPORTING
*     I_INTERFACE_CHECK       = ' '
*     I_BYPASSING_BUFFER      = ' '
*     I_BUFFER_ACTIVE         = ' '
      I_CALLBACK_PROGRAM      = G_REPID
*     I_CALLBACK_PF_STATUS_SET          = ' '
      I_CALLBACK_USER_COMMAND = 'USER_COMM'
      I_CALLBACK_TOP_OF_PAGE  = 'TOP'
*     I_CALLBACK_HTML_TOP_OF_PAGE       = ' '
*     I_CALLBACK_HTML_END_OF_LIST       = ' '
*     I_STRUCTURE_NAME        =
*     I_BACKGROUND_ID         = ' '
*     I_GRID_TITLE            =
*     I_GRID_SETTINGS         =
      IS_LAYOUT               = LAYOUT
      IT_FIELDCAT             = FIELDCAT
*     IT_EXCLUDING            =
*     IT_SPECIAL_GROUPS       =
*     IT_SORT                 =
*     IT_FILTER               =
*     IS_SEL_HIDE             =
*     I_DEFAULT               = 'X'
      I_SAVE                  = 'A'
*     IS_VARIANT              =
*     IT_EVENTS               =
*     IT_EVENT_EXIT           =
*     IS_PRINT                =
*     IS_REPREP_ID            =
*     I_SCREEN_START_COLUMN   = 0
*     I_SCREEN_START_LINE     = 0
*     I_SCREEN_END_COLUMN     = 0
*     I_SCREEN_END_LINE       = 0
*     I_HTML_HEIGHT_TOP       = 0
*     I_HTML_HEIGHT_END       = 0
*     IT_ALV_GRAPHICS         =
*     IT_HYPERLINK            =
*     IT_ADD_FIELDCAT         =
*     IT_EXCEPT_QINFO         =
*     IR_SALV_FULLSCREEN_ADAPTER        =
* IMPORTING
*     E_EXIT_CAUSED_BY_CALLER =
*     ES_EXIT_CAUSED_BY_USER  =
    TABLES
      T_OUTTAB                = IT_TAB1
    EXCEPTIONS
      PROGRAM_ERROR           = 1
      OTHERS                  = 2.
  IF SY-SUBRC <> 0.
* MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO
*         WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4.
  ENDIF.
ENDFORM.

FORM TOP.

  DATA: COMMENT    TYPE SLIS_T_LISTHEADER,
        WA_COMMENT LIKE LINE OF COMMENT.

  WA_COMMENT-TYP = 'A'.
  WA_COMMENT-INFO = 'LLM INVOICE DETAILS'.
*  WA_COMMENT-INFO = P_FRMDT.
  APPEND WA_COMMENT TO COMMENT.

  CALL FUNCTION 'REUSE_ALV_COMMENTARY_WRITE'
    EXPORTING
      IT_LIST_COMMENTARY = COMMENT
*     I_LOGO             = 'ENJOYSAP_LOGO'
*     I_END_OF_LIST_GRID =
*     I_ALV_FORM         =
    .

  CLEAR COMMENT.

ENDFORM.                    "TOP



*&---------------------------------------------------------------------*
*&      Form  USER_COMM
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*      -->UCOMM      text
*      -->SELFIELD   text
*----------------------------------------------------------------------*
FORM USER_COMM USING UCOMM LIKE SY-UCOMM
                     SELFIELD TYPE SLIS_SELFIELD.



  CASE SELFIELD-FIELDNAME.
    WHEN 'VBELN'.
      SET PARAMETER ID 'VF' FIELD SELFIELD-VALUE.
      CALL TRANSACTION 'VF03' AND SKIP FIRST SCREEN.
    WHEN 'VBELN1'.
      SET PARAMETER ID 'BV' FIELD SELFIELD-VALUE.
      CALL TRANSACTION 'VL03N' AND SKIP FIRST SCREEN.
    WHEN OTHERS.
  ENDCASE.
ENDFORM.                    "USER_COMM
