*
PROCESS BEFORE OUTPUT.
  MODULE MODIFY_SUBSCREEN.
  MODULE MODULE_PBO_0001.
  MODULE HIDDEN_DATA_SUBSCREEN.
*
PROCESS AFTER INPUT.
  CHAIN.
    FIELD P0001-ZZ_HQCODE.
    MODULE INPUT_STATUS_SUBSCREEN ON CHAIN-REQUEST.
  ENDCHAIN.
*   infotype specific checks etc.:
  MODULE MODULE_PAI_0001.
