PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZPMS_ART_TABLE CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZPMS_ART_TABLE-MATNR .
    FIELD ZPMS_ART_TABLE-FROM_DT .
    FIELD ZPMS_ART_TABLE-TO_DT .
    FIELD ZPMS_ART_TABLE-PMS_NO .
    FIELD ZPMS_ART_TABLE-ART_NO .
    FIELD ZPMS_ART_TABLE-REMARK .
    FIELD ZPMS_ART_TABLE-USNAM .
    FIELD ZPMS_ART_TABLE-CPUDT .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZPMS_ART_TABLE-MATNR .
    FIELD ZPMS_ART_TABLE-FROM_DT .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
