PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZPO_GATE CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZPO_GATE-VBELN .
    FIELD ZPO_GATE-MJAHR .
    FIELD ZPO_GATE-WERKS .
    FIELD ZPO_GATE-NUM .
    FIELD ZPO_GATE-EBELN .
    FIELD ZPO_GATE-XBLNR .
    FIELD ZPO_GATE-BLDAT .
    FIELD ZPO_GATE-VEHNO .
    FIELD ZPO_GATE-TRANSPORTER .
    FIELD ZPO_GATE-REMARK .
    FIELD ZPO_GATE-CPUDT .
    FIELD ZPO_GATE-CPUTM .
    FIELD ZPO_GATE-USNAM .
    FIELD ZPO_GATE-STRY .
    FIELD ZPO_GATE-STRN .
    FIELD ZPO_GATE-STRTXT .
    FIELD ZPO_GATE-SCPUDT .
    FIELD ZPO_GATE-SCPUTM .
    FIELD ZPO_GATE-SUSNAM .
    FIELD ZPO_GATE-SPERNR .
    FIELD ZPO_GATE-REJCPUDT .
    FIELD ZPO_GATE-REJCPUTM .
    FIELD ZPO_GATE-REJUSNAM .
    FIELD ZPO_GATE-REJPERNR .
    FIELD ZPO_GATE-GIN .
    FIELD ZPO_GATE-GCPUDT .
    FIELD ZPO_GATE-GCPUTM .
    FIELD ZPO_GATE-GUSNAM .
    FIELD ZPO_GATE-GOUT .
    FIELD ZPO_GATE-GOCPUDT .
    FIELD ZPO_GATE-GOCPUTM .
    FIELD ZPO_GATE-GOUSNAM .
    FIELD ZPO_GATE-DELTXT .
    FIELD ZPO_GATE-DEL .
    FIELD ZPO_GATE-DELDT .
    FIELD ZPO_GATE-DELTM .
    FIELD ZPO_GATE-DELUSNAM .
    FIELD ZPO_GATE-DELPERNR .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZPO_GATE-VBELN .
    FIELD ZPO_GATE-MJAHR .
    FIELD ZPO_GATE-WERKS .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
