PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZPROD_STOCK CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZPROD_STOCK-ZMONTH .
    FIELD ZPROD_STOCK-ZYEAR .
    FIELD ZPROD_STOCK-MATNR .
    FIELD ZPROD_STOCK-WERKS .
    FIELD ZPROD_STOCK-FAC_STK .
    FIELD ZPROD_STOCK-CNF_STK .
    FIELD ZPROD_STOCK-TRAME .
    FIELD ZPROD_STOCK-BUDAT .
    FIELD ZPROD_STOCK-VENDOR_NAME1 .
    FIELD ZPROD_STOCK-BUDAT1 .
    FIELD ZPROD_STOCK-QTY1 .
    FIELD ZPROD_STOCK-RQTY1 .
    FIELD ZPROD_STOCK-BUDGET1 .
    FIELD ZPROD_STOCK-CL1 .
    FIELD ZPROD_STOCK-BUDAT2 .
    FIELD ZPROD_STOCK-QTY2 .
    FIELD ZPROD_STOCK-RQTY2 .
    FIELD ZPROD_STOCK-BUDGET2 .
    FIELD ZPROD_STOCK-CL2 .
    FIELD ZPROD_STOCK-BUDAT3 .
    FIELD ZPROD_STOCK-QTY3 .
    FIELD ZPROD_STOCK-RQTY3 .
    FIELD ZPROD_STOCK-BUDGET3 .
    FIELD ZPROD_STOCK-CL3 .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZPROD_STOCK-ZMONTH .
    FIELD ZPROD_STOCK-ZYEAR .
    FIELD ZPROD_STOCK-MATNR .
    FIELD ZPROD_STOCK-WERKS .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
