*&---------------------------------------------------------------------*
*& Report  ZSAMP_RANKING
*&
*&---------------------------------------------------------------------*
*&
*&
*&---------------------------------------------------------------------*

REPORT  ZSAMP_RANKING_A1.

TYPE-POOLS:  SLIS.

TABLES: ZRPQV, YTERRALLC,PA0001,PA0000, HRP1000, YSD_DIST_TARGT, MARA, ZDSMTER, ZSAMPPROCESS.
CONSTANTS : RBSELECTED TYPE C LENGTH 1 VALUE 'X'.


DATA :  RESULT      LIKE  ITCPP.
DATA : OPTIONS        TYPE ITCPO,
       L_OTF_DATA     LIKE ITCOO OCCURS 10,
       L_ASC_DATA     LIKE TLINE OCCURS 10,
       L_DOCS         LIKE DOCS  OCCURS 10,
       L_PDF_DATA     LIKE SOLISTI1 OCCURS 10,
       L_PDF_DATA1    LIKE SOLISTI1 OCCURS 10,
       L_BIN_FILESIZE TYPE I.

DATA: DOCDATA LIKE SOLISTI1  OCCURS  10,
      OBJHEAD LIKE SOLISTI1  OCCURS  1,
      OBJBIN1 LIKE SOLISTI1  OCCURS 10,
      OBJBIN  LIKE SOLISTI1  OCCURS 10.
DATA: LISTOBJECT LIKE ABAPLIST  OCCURS  1 .
DATA: DOC_CHNG LIKE SODOCCHGI1.
DATA RECLIST    LIKE SOMLRECI1  OCCURS  1 WITH HEADER LINE.
DATA MCOUNT TYPE I.

DATA RIGHE_ATTACHMENT TYPE I.
DATA RIGHE_TESTO TYPE I.
DATA TAB_LINES TYPE I.
DATA: LTX LIKE T247-LTX.


DATA  BEGIN OF OBJPACK OCCURS 0 .
        INCLUDE STRUCTURE  SOPCKLSTI1.
DATA END OF OBJPACK.

DATA BEGIN OF OBJTXT OCCURS 0.
        INCLUDE STRUCTURE SOLISTI1.
DATA END OF OBJTXT.


DATA: PDFTAB      TYPE TABLE OF TLINE WITH HEADER LINE,
      DATAB       TYPE TABLE OF ITCOO WITH HEADER LINE,
      BINFILESIZE TYPE I.

DATA: FILE_NAME TYPE STRING,
      FILE_PATH TYPE STRING,
      FULL_PATH TYPE STRING.






DATA: STRUCT TYPE ITCPO.
DATA  P_HEAD1.
*To specify Printer name*
STRUCT-TDDEST = 'LP01'.
*To specify no Print Preview*
STRUCT-TDNOPREV = 'X'.
*To access the SAP Script output in OTF format*
STRUCT-TDGETOTF = 'X'.


DATA: G_REPID     LIKE SY-REPID,
      FIELDCAT    TYPE SLIS_T_FIELDCAT_ALV,
      WA_FIELDCAT LIKE LINE OF FIELDCAT,
      MSAL(10)    TYPE P DECIMALS 2.


DATA : VF_RANK TYPE RS38L_FNAM,
       PERNO   TYPE PA0001-PERNR.

TYPES : BEGIN OF ITAB2,
          REG        TYPE ZDSMTER-ZDSM,
          RM         TYPE ZDSMTER-BZIRK,
          ZM         TYPE ZDSMTER-BZIRK,
          ZMONTH     TYPE ZRPQV-ZMONTH,
          ZYEAR      TYPE ZRPQV-ZYEAR,
          BZIRK      TYPE ZRPQV-BZIRK,
          JOIN_DT(7) TYPE C,
          TARGT      TYPE P,
          GS1        TYPE P,
          GS2        TYPE P,
          GS3        TYPE P,
          GS4        TYPE P,
          TGT1       TYPE P,
          TGT2       TYPE P,
          TGT3       TYPE P,
          TGT4       TYPE P,
          DIV(3)     TYPE C,
          ZZ_HQDESC  TYPE ZTHR_HEQ_DES-ZZ_HQDESC,
          ENAME      TYPE PA0001-ENAME,

        END OF ITAB2.

TYPES : BEGIN OF ITAC1,
          REG            TYPE ZDSMTER-ZDSM,
          SPART          TYPE ZDSMTER-SPART,
          ZM             TYPE ZDSMTER-BZIRK,
          RM             TYPE ZDSMTER-BZIRK,
          BZIRK          TYPE ZDSMTER-BZIRK,
          TEXT(9)        TYPE C,
          SVAL           TYPE P DECIMALS 2,
          ACN_VAL        TYPE P DECIMALS 2,
          OTH_VAL        TYPE P DECIMALS 2,
          NET            TYPE P DECIMALS 2,
          REG_PLANS      TYPE YTERRALLC-PLANS,
          REG_ENAME      TYPE PA0001-ENAME,
          RM_PLANS       TYPE YTERRALLC-PLANS,
          RM_ENAME       TYPE PA0001-ENAME,
          REG_HQDESC     TYPE ZTHR_HEQ_DES-ZZ_HQDESC,
          RM_HQDESC      TYPE ZTHR_HEQ_DES-ZZ_HQDESC,
          SHORT          TYPE HRP1000-SHORT,
          BEGDA          TYPE PA0302-BEGDA,
          REG_JOIN_DT(7) TYPE C,
          RM_JOIN_DT(7)  TYPE C,
        END OF ITAC1.



TYPES : BEGIN OF TYP_YTERALC,
          MANDT   TYPE YTERRALLC-MANDT,
          SPART   TYPE YTERRALLC-SPART,
          BZIRK   TYPE YTERRALLC-BZIRK,
          ENDDA   TYPE YTERRALLC-ENDDA,
          BEGDA   TYPE YTERRALLC-BEGDA,
          PLANS   TYPE YTERRALLC-PLANS,
          MDIV(3) TYPE  C,
          BZTXT   TYPE BZTXT,
        END OF TYP_YTERALC.

TYPES : BEGIN OF TYP_SAMPPROCESS,
          MANDT    TYPE ZSAMPPROCESS-MANDT,
          ZMONTH   TYPE ZSAMPPROCESS-ZMONTH,
          ZYEAR    TYPE ZSAMPPROCESS-ZYEAR,
          BZIRK    TYPE ZSAMPPROCESS-BZIRK,
          SAMPCODE TYPE ZSAMPPROCESS-SAMPCODE,
          SAMPQTY  TYPE ZSAMPPROCESS-SAMPQTY,
        END OF TYP_SAMPPROCESS.


TYPES : BEGIN OF TYP_TSAMP,
          MANDT  TYPE ZSAMPPROCESS-MANDT,
          ZMONTH TYPE ZSAMPPROCESS-ZMONTH,
          ZYEAR  TYPE ZSAMPPROCESS-ZYEAR,
          BZIRK  TYPE ZSAMPPROCESS-BZIRK,
          SAMPLE TYPE ZSAMPPROCESS-SAMPQTY,
          SPR    TYPE ZSAMPPROCESS-SAMPQTY,
        END OF TYP_TSAMP.




DATA :  BEGIN OF IT_TERMAST OCCURS 0.
          INCLUDE STRUCTURE YTERRALLC.
        DATA : END OF IT_TERMAST.



TYPES : BEGIN OF TYP_ZRPQV,
          MANDT    TYPE ZRPQV-MANDT,
          ZMONTH   TYPE ZRPQV-ZMONTH,
          ZYEAR    TYPE ZRPQV-ZYEAR,
          BZIRK    TYPE ZRPQV-BZIRK,
          MATNR    TYPE ZRPQV-MATNR,
          GROSSPTS TYPE ZRPQV-GROSSPTS,
          GROSSQTY TYPE ZRPQV-GROSSQTY,
          RVAL     TYPE ZRPQV-RVAL,
          RQTY     TYPE ZRPQV-RQTY,
          NEPVAL   TYPE ZRPQV-NEPVAL,
          NEPQTY   TYPE ZRPQV-NEPQTY,


        END OF TYP_ZRPQV.


TYPES : BEGIN OF TYP_ZRPQV1,
          BZIRK    TYPE ZRPQV-BZIRK,
          GROSSPTS TYPE ZRPQV-GROSSPTS,
          GROSSQTY TYPE ZRPQV-GROSSQTY,
          RVAL     TYPE ZRPQV-RVAL,
          RQTY     TYPE ZRPQV-RQTY,
          NEPVAL   TYPE ZRPQV-NEPVAL,
          NEPQTY   TYPE ZRPQV-NEPQTY,
        END OF TYP_ZRPQV1.



TYPES:
  TT_ZRPQV1 TYPE STANDARD TABLE OF TYP_ZRPQV1
    WITH KEY BZIRK.
DATA: DCOUNT TYPE I.

TYPES : BEGIN OF TYP_MRPQV1,
          BZIRK    TYPE ZRPQV-BZIRK,
          GROSSPTS TYPE ZRPQV-GROSSPTS,
          GROSSQTY TYPE ZRPQV-GROSSQTY,
          RVAL     TYPE ZRPQV-RVAL,
          RQTY     TYPE ZRPQV-RQTY,
          NEPVAL   TYPE ZRPQV-NEPVAL,
          NEPQTY   TYPE ZRPQV-NEPQTY,
        END OF TYP_MRPQV1.



TYPES:
  TT_MRPQV1 TYPE STANDARD TABLE OF TYP_MRPQV1
    WITH KEY BZIRK.





TYPES : BEGIN OF TYP_HRP1000,
          MANDT    TYPE HRP1000-MANDT,
          OTYPE    TYPE HRP1000-OTYPE,
          OBJID    TYPE HRP1000-OBJID,
          BEGDA    TYPE HRP1000-BEGDA,
          ENDDA    TYPE HRP1000-ENDDA,
          MC_SHORT TYPE HRP1000-MC_SHORT,
          MC_STEXT TYPE HRP1000-MC_STEXT,
        END OF TYP_HRP1000.

TYPES : BEGIN OF TYP_PA0001,
          MANDT     TYPE PA0001-MANDT,
          PERNR     TYPE PA0001-PERNR,
          BEGDA     TYPE PA0001-BEGDA,
          ENDDA     TYPE PA0001-ENDDA,
          ABKRS     TYPE PA0001-ABKRS,
          ANSVH     TYPE PA0001-ANSVH,
          PERSK     TYPE PA0001-PERSK,
          PLANS     TYPE PA0001-PLANS,
          ENAME     TYPE PA0001-ENAME,
          ZZ_HQCODE TYPE PA0001-ZZ_HQCODE,
        END OF TYP_PA0001.


TYPES : BEGIN OF TYP_T171,
          MANDT TYPE MANDT,
          BZIRK TYPE BZIRK,
          BZTXT TYPE BZTXT,
        END OF TYP_T171.


TYPES : BEGIN OF TYP_SESALE,
          BZIRK      TYPE BZIRK,
          SALES(10)  TYPE P DECIMALS 0,
          PSALES(10) TYPE P DECIMALS 0,
          QTY(10)    TYPE P DECIMALS 0,
          PQTY(10)   TYPE P DECIMALS 0,
        END OF TYP_SESALE.

TYPES:
  TT_SESALE TYPE STANDARD TABLE OF TYP_SESALE
    WITH KEY BZIRK.



TYPES : BEGIN OF TYP_SD_TARGET,
          MANDT   TYPE YSD_DIST_TARGT-MANDT,
          SPART   TYPE YSD_DIST_TARGT-SPART,
          BZIRK   TYPE YSD_DIST_TARGT-BZIRK,
          TRGYEAR TYPE YSD_DIST_TARGT-TRGYEAR,
          MONTH01 TYPE YSD_DIST_TARGT-MONTH01,
          MONTH02 TYPE YSD_DIST_TARGT-MONTH02,
          MONTH03 TYPE YSD_DIST_TARGT-MONTH03,
          MONTH04 TYPE YSD_DIST_TARGT-MONTH04,
          MONTH05 TYPE YSD_DIST_TARGT-MONTH05,
          MONTH06 TYPE YSD_DIST_TARGT-MONTH06,
          MONTH07 TYPE YSD_DIST_TARGT-MONTH07,
          MONTH08 TYPE YSD_DIST_TARGT-MONTH08,
          MONTH09 TYPE YSD_DIST_TARGT-MONTH09,
          MONTH10 TYPE YSD_DIST_TARGT-MONTH10,
          MONTH11 TYPE YSD_DIST_TARGT-MONTH11,
          MONTH12 TYPE YSD_DIST_TARGT-MONTH12,
        END OF TYP_SD_TARGET.








TYPES : BEGIN OF TYP_REPORT,
          SRLNO(5)      TYPE P  DECIMALS 0,
          PRNAME(20)    TYPE C,
          ZDSM          TYPE ZDSMTER-ZDSM,
          ZRSM          TYPE ZDSMTER-ZDSM,
          ZMNAME        TYPE PA0001-ENAME,
          RMNAME        TYPE PA0001-ENAME,
          PERNR         TYPE PA0001-PERNR,
          ENAME         TYPE PA0001-ENAME,
          BZIRK         TYPE BZIRK,
          ZZ_HQCODE     TYPE PA0001-ZZ_HQCODE,
          ZZ_HQDESC     TYPE ZDEHR_HQDESC,
          DES           TYPE HRP1000-MC_SHORT,
          DIV(3)        TYPE C,
          DOJ           TYPE PA0001-BEGDA,
          SALES(10)     TYPE P DECIMALS 0,
          SAMPLE(10)    TYPE P DECIMALS 0,
          SPR(10)       TYPE P DECIMALS 0,
          AVGSALES(10)  TYPE P DECIMALS 0,
          PSALES(10)    TYPE P DECIMALS 0,
          QTY(10)       TYPE P DECIMALS 0,
          AVGQTY(10)    TYPE P DECIMALS 0,
          PQTY(10)      TYPE P DECIMALS 0,
          GRTH          TYPE P DECIMALS 0,
          TARGET(10)    TYPE P DECIMALS 0,
          PERTGT(8)     TYPE P DECIMALS 2,
          AVGTARGET(10) TYPE P DECIMALS 0,

        END OF TYP_REPORT.

TYPES : BEGIN OF TYP_DSMTER,
          ZDSM      TYPE ZDSMTER-ZDSM,
          ZDSMSPART TYPE ZDSMTER-ZDSMSPART,
          ZMONTH    TYPE ZDSMTER-ZMONTH,
          ZYEAR     TYPE ZDSMTER-ZYEAR,
          BZIRK     TYPE ZDSMTER-BZIRK,
          SPART     TYPE ZDSMTER-SPART,
        END OF TYP_DSMTER.


TYPES : BEGIN OF ITPRD,
          MATNR TYPE MAKT-MATNR,
          MAKTX TYPE MAKT-MAKTX,
          MTART TYPE MARA-MTART,
        END OF ITPRD.




TYPES : BEGIN OF TYP_ITAB1,
          PERNR  TYPE PERSNO,
          DTJOIN TYPE BEGDA,
        END OF TYP_ITAB1.





TYPES : BEGIN OF TYP_ITAB7,
          PERNR TYPE PERNO,
          OBJID TYPE OBJID,
          STEXT TYPE STEXT,
        END OF TYP_ITAB7.



TYPES : BEGIN OF TYP_HRP1001,
          OBJID TYPE OBJID,
          SOBID TYPE SOBID,
          RSIGN TYPE RSIGN,
          RELAT TYPE RELAT,
        END OF TYP_HRP1001.

TYPES : BEGIN OF TYP_HQ ,
          OBJID    TYPE HRP1000-OBJID,
          MC_STEXT TYPE HRP1000-MC_STEXT,
        END OF TYP_HQ.



TYPES : BEGIN OF TYP_FSHQ ,
          PERNR    TYPE PA0001-PERNR,
          ABKRS    TYPE ABKRS,
          PLANS    TYPE HRP1000-OBJID,
          MC_STEXT TYPE HRP1000-MC_STEXT,
          HQ(15)   TYPE C,
          DIV(3)   TYPE C,
        END OF TYP_FSHQ.


TYPES : BEGIN OF TYP_T503T ,
          PERSK TYPE T503T-PERSK,
          PTEXT TYPE T503T-PTEXT,
        END OF TYP_T503T.

TYPES : BEGIN OF TYP_ZHQ ,
          ZZ_HQCODE TYPE ZDEHR_HQCODE,
          ZZ_HQDESC TYPE ZDEHR_HQDESC,
        END OF TYP_ZHQ.

TYPES : BEGIN OF TYP_MONTH_NAMES ,
          MNR TYPE T247-MNR,
          LTX TYPE T247-LTX,
        END OF TYP_MONTH_NAMES.






DATA: DT1         TYPE SY-DATUM,
      DT2         TYPE SY-DATUM,
      C_DATE      TYPE SY-DATUM,
      P_DATE1     TYPE SY-DATUM,
      P_DATE2     TYPE SY-DATUM,

      YMTH1(2)    TYPE P DECIMALS 0,
      YMTH2(2)    TYPE P DECIMALS 0,
      PYMTH1(2)   TYPE P DECIMALS 0,
      PYMTH2(2)   TYPE P DECIMALS 0,

      YYR1(4)     TYPE P DECIMALS 0,
      YYR2(4)     TYPE P DECIMALS 0,
      PYYR1(4)    TYPE P DECIMALS 0,
      PYYR2(4)    TYPE P DECIMALS 0,
      TRGYR(4)    TYPE P DECIMALS 0,
      DIV1(4)     TYPE C,
      CNT(4)      TYPE P DECIMALS 0,
      POS(4)      TYPE P DECIMALS 0,
      NPOS(4)     TYPE P DECIMALS 0,
      WPERNR(6)   TYPE P DECIMALS 0,
      TRGTVAL(12) TYPE P DECIMALS 0,
      P_HEAD2     TYPE SOMLRECI1-RECEIVER,

      i(2)        TYPE P DECIMALS 0,
      M_CNT(4)    TYPE P DECIMALS 0,

      T_CNT(3)    TYPE P DECIMALS 0,

      NAME(10)    TYPE C,

      MTH(3)      TYPE P DECIMALS 0,
      TOTNO(3)    TYPE P DECIMALS 0,
      MMYYYY(7)   TYPE C,
      CSTEXT(20)  TYPE C.





FIELD-SYMBOLS: <FS_YTERALC>  TYPE TYP_YTERALC,
               <FS_YTERALC1> TYPE TYP_YTERALC,
               <FS_YTERALC2> TYPE TYP_YTERALC,
               <FS_SAMP>     TYPE TYP_SAMPPROCESS,
               <FS_ZRPQV>    TYPE TYP_ZRPQV,
               <FS_ZRPQV1>   TYPE TYP_ZRPQV1,
               <FS_MRPQV>    TYPE TYP_ZRPQV,
               <FS_MRPQV1>   TYPE TYP_ZRPQV1,
               <FS_SESALE>   TYPE TYP_SESALE,
               <FS_TSAMP>    TYPE TYP_TSAMP,

               <FS_HRP1000>  TYPE TYP_HRP1000,
               <FS_PA0001>   TYPE TYP_PA0001,
               <FS_T171>     TYPE TYP_T171,
               <FS_DSMTER>   TYPE TYP_DSMTER,
               <FS_RMTER>    TYPE TYP_DSMTER,
               <FS_REPORT>   TYPE TYP_REPORT,
               <FS_T503T>    TYPE TYP_T503T,
               <FS_ZHQ>      TYPE TYP_ZHQ,
               <FS_ITAB1>    TYPE TYP_ITAB1.






DATA: WA_YTERALC    TYPE TYP_YTERALC,
      WA_YTERALC1   TYPE TYP_YTERALC,
      WA_YTERALC2   TYPE TYP_YTERALC,
      "wa_TERMAST type typ_TERMAST,

      WA_ZRPQV      TYPE TYP_ZRPQV,
      WA_ZRPQV1     TYPE   TYP_ZRPQV1,
      WA_ZRPQV2     TYPE TYP_ZRPQV1,
      WA_MRPQV      TYPE TYP_ZRPQV,
      WA_MRPQV1     TYPE TYP_MRPQV1,

      WA_T171       TYPE TYP_T171,
      WA_TAB2       TYPE ITAB2,
      WA_TAC5       TYPE ITAC1,

      WA_HRP1000    TYPE TYP_HRP1000,
      WA_PA0001     TYPE TYP_PA0001,
      WA_DSMTER     TYPE TYP_DSMTER,
      WA_RMTER      TYPE TYP_DSMTER,
      WA_T503T      TYPE TYP_T503T,
      WA_ZHQ        TYPE TYP_ZHQ,
      WA_REPORT     TYPE TYP_REPORT,
      WA_REPORT2    TYPE TYP_REPORT,
      WA_SESALE     TYPE TYP_SESALE,
      WA_PRD        TYPE ITPRD,
      WA_SAMP       TYPE TYP_SAMPPROCESS,
      WA_TSAMP      TYPE TYP_TSAMP,
      WA_SD_TARGET  TYPE TYP_SD_TARGET,

      WA_ZDSMTER1   TYPE TYP_DSMTER,
      WA_PSOTER     TYPE TYP_DSMTER,
      WA_PSOTER1    TYPE TYP_DSMTER,



      WA_ITAB1      TYPE TYP_ITAB1,
      WA_MONTH_NAME TYPE  TYP_MONTH_NAMES.





DATA: IT_YTERALC    TYPE TABLE OF  TYP_YTERALC,
      IT_YTERALC1   TYPE TABLE OF  TYP_YTERALC,
      IT_YTERALC2   TYPE TABLE OF  TYP_YTERALC,
      IT_SAMP       TYPE TABLE OF    TYP_SAMPPROCESS,
      IT_TSAMP      TYPE TABLE OF    TYP_TSAMP,

      IT_PRD        TYPE TABLE OF ITPRD,
      IT_SD_TARGET  TYPE TABLE OF TYP_SD_TARGET,
      LT_MONTH_NAME TYPE TABLE OF TYP_MONTH_NAMES,


      IT_ZRPQV      TYPE TABLE OF TYP_ZRPQV,
      "it_ZRPQV1 type table of typ_ZRPQV,
      IT_ZRPQV1     TYPE  TT_ZRPQV1,
      IT_MRPQV1     TYPE  TT_MRPQV1,
      IT_SESALE     TYPE  TT_SESALE,

      IT_ZRPQV2     TYPE TABLE OF TYP_ZRPQV,
      IT_MRPQV      TYPE TABLE OF TYP_ZRPQV,
      "it_MRPQV1 type table of typ_ZRPQV,

      IT_T171       TYPE TABLE OF TYP_T171,
      IT_TAB2       TYPE TABLE OF ITAB2,
      IT_TAC5       TYPE TABLE OF ITAC1,


      IT_HRP1000    TYPE TABLE OF TYP_HRP1000,
      IT_PA0001     TYPE TABLE OF TYP_PA0001,
*      it_sd_target type table of typ_sd_target,
      IT_ITAB1      TYPE TABLE OF TYP_ITAB1,


      ITAB_REPORT   TYPE TABLE OF TYP_REPORT,
      ITAB_REPORT1  TYPE TABLE OF TYP_REPORT,
      ITAB_REPORT2  TYPE TABLE OF TYP_REPORT,
      ITAB_REPORT3  TYPE TABLE OF TYP_REPORT,
      ITAB_REPORT4  TYPE TABLE OF TYP_REPORT,
      ITAB_REPORT5  TYPE TABLE OF TYP_REPORT WITH HEADER LINE,
      ITAB_REPORT6  TYPE TABLE OF TYP_REPORT WITH HEADER LINE,

      IT_RMTER      TYPE  TABLE OF TYP_DSMTER,



      ITAB_HQ       TYPE TABLE OF TYP_HQ,
      ITAB_HQ_1     TYPE TABLE OF TYP_FSHQ,
      ITAB_HQ_2     TYPE TABLE OF TYP_FSHQ,
      IT_HRP1001    TYPE TABLE OF TYP_HRP1001,
      ITAB_T503T    TYPE TABLE OF TYP_T503T,
*      IT_MAKT TYPE TABLE OF MAKT,
*      IT_MARA TYPE TABLE OF MARA,
      IT_MAKT       TYPE  MAKT,
      IT_MARA       TYPE  MARA,


      IT_ZDSMTER    TYPE TABLE OF TYP_DSMTER,
      IT_ZDSMTER1   TYPE TABLE OF  TYP_DSMTER,
      IT_PSOTER     TYPE TABLE OF TYP_DSMTER,
      IT_PSOTER1    TYPE TABLE OF TYP_DSMTER,




      ITAB_ZHQ      TYPE TABLE OF TYP_ZHQ.

DATA : MSG       TYPE STRING,
       WA_D1(10) TYPE C,
       WA_D2(10) TYPE C.




SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME TITLE TEXT-001.
PARAMETERS  : MMONTH LIKE  ZSAMPPROCESS-ZMONTH.
PARAMETERS  : MYEAR LIKE  ZSAMPPROCESS-ZYEAR.
SELECT-OPTIONS: S_BEGDA FOR PA0000-BEGDA NO-EXTENSION OBLIGATORY.

*PARAMETERS  : zone like  ZDSMTER-ZDSM matchcode object zsr9_1.
*PARAMETERS  : p_pso like  cnt.
SELECTION-SCREEN END OF BLOCK B1.

SELECTION-SCREEN BEGIN OF BLOCK B3 WITH FRAME TITLE TEXT-006.
SELECTION-SCREEN END OF BLOCK B3.

SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME TITLE TEXT-002.
SELECTION-SCREEN END OF BLOCK B2.


SELECTION-SCREEN BEGIN OF BLOCK B4 WITH FRAME TITLE TEXT-003.
PARAMETERS: P_RAD1 RADIOBUTTON GROUP R2,
            P_RAD2 RADIOBUTTON GROUP R2,
            P_RAD3 RADIOBUTTON GROUP R2,
            P_RAD4 RADIOBUTTON GROUP R2.


IF P_RAD2 = RBSELECTED .
  "   parameter: p_head3 like P_HEAD2 .
ENDIF.

SELECT MNR LTX FROM T247
INTO TABLE LT_MONTH_NAME
WHERE SPRAS = 'E'.

READ TABLE LT_MONTH_NAME  INTO WA_MONTH_NAME WITH KEY MNR = MMONTH.
IF SY-SUBRC = 0.
  NAME =  WA_MONTH_NAME-LTX.
ENDIF.


P_HEAD2  = 'SAMPLE ALLOCATION RANKING FOR '.
*   CONCATENATE P_HEAD2 '(VALUE WISE)' INTO P_HEAD2 SEPARATED BY SPACE .

WRITE S_BEGDA-LOW TO WA_D1 DD/MM/YY.
WRITE S_BEGDA-HIGH TO WA_D2 DD/MM/YY.
"TRANSLATE p_head3 to UPPER CASE.
CONCATENATE  P_HEAD2  'DESPATCH MONTH ' NAME MYEAR    INTO P_HEAD2 SEPARATED BY SPACE. "' FROM ' wa_d1 ' TO '  wa_d2
TRANSLATE P_HEAD2 TO UPPER CASE.

IF P_RAD4 = RBSELECTED .
  PARAMETER: P_EMAIL1 LIKE SOMLRECI1-RECEIVER .
ENDIF.
SELECTION-SCREEN END OF BLOCK B4.


INITIALIZATION.
  G_REPID = SY-REPID.

START-OF-SELECTION.
  DT1 = S_BEGDA-LOW.
  DT2 = S_BEGDA-HIGH.

  YYR1 = DT1+0(4).
  YYR2 = DT2+0(4).
  YMTH1 = DT1+4(2).
  YMTH2 = DT2+4(2).



  PYYR1 = YYR1 - 1.
  PYYR2 =  YYR2 - 1.
  PYMTH1 = YMTH1 .
  PYMTH2 = YMTH2 .



  IF YMTH2 < 4.
    TRGYR = YYR2 - 1.
  ELSE.
    TRGYR = YYR1.
  ENDIF.








  IF YMTH1 = YMTH2.
    M_CNT = 1.
  ELSEIF YMTH1 <> YMTH2 AND YYR1 = YYR2.
    M_CNT = YMTH2 -  YMTH1 + 1.
  ELSEIF YMTH1 <> YMTH2 AND YYR1 <> YYR2.
    M_CNT = 12 -  YMTH1 + 1.
    M_CNT = M_CNT + YMTH2.
  ENDIF.










  PERFORM GET-DATA.
  IF P_RAD1 = RBSELECTED .
    PERFORM GRD-DATA.

  ENDIF.

  IF P_RAD2 = RBSELECTED .
*perform PRINT-REPORT.

    PERFORM OPEN-FORM.

    LOOP AT ITAB_REPORT4 ASSIGNING <FS_REPORT>.
      WPERNR = <FS_REPORT>-PERNR.
      CONCATENATE  <FS_REPORT>-DOJ+4(2) '/' <FS_REPORT>-DOJ+2(2) INTO MMYYYY  .
      PERFORM WRITE-FORM  .
      AT LAST.

      ENDAT.

    ENDLOOP.

    PERFORM CLOSE-FORM.

  ENDIF.

  IF P_RAD3 = RBSELECTED .
*perform PRINT-REPORT.

    PERFORM OPEN-PDF-FORM.

    LOOP AT ITAB_REPORT4 ASSIGNING <FS_REPORT>.
      WPERNR = <FS_REPORT>-PERNR.
*      yyr1 = <FS_REPORT>-DOJ+0(4).
*      ymth1 = <FS_REPORT>-DOJ+4(2).
      CONCATENATE  <FS_REPORT>-DOJ+4(2) '/' <FS_REPORT>-DOJ+0(4) INTO MMYYYY  .
      PERFORM WRITE-FORM  .
      AT LAST.

      ENDAT.

    ENDLOOP.

    PERFORM CLOSE-PDF-FORM.

    PERFORM CONVERT-PDF.
    PERFORM SELECT-DIRECTORY-AND-SAVE.
    PERFORM DOWNLOAD.



  ENDIF.

  IF P_RAD4 = RBSELECTED .
    PERFORM ENFORM3.
  ENDIF.






FORM GET-DATA.

  SELECT  ZSAMPPROCESS~MANDT
  ZSAMPPROCESS~ZMONTH
  ZSAMPPROCESS~ZYEAR
  ZSAMPPROCESS~BZIRK
  ZSAMPPROCESS~SAMPCODE
  ZSAMPPROCESS~SAMPQTY FROM ZSAMPPROCESS
  INTO TABLE  IT_SAMP  WHERE ZSAMPPROCESS~ZMONTH = MMONTH AND ZSAMPPROCESS~ZYEAR = MYEAR  AND STATUS NE 'C' .

  SELECT YTERRALLC~MANDT YTERRALLC~SPART YTERRALLC~BZIRK YTERRALLC~ENDDA YTERRALLC~BEGDA
  YTERRALLC~PLANS  FROM YTERRALLC INTO TABLE  IT_YTERALC  WHERE YTERRALLC~ENDDA EQ '99991231'.

  SELECT YTERRALLC~MANDT YTERRALLC~SPART YTERRALLC~BZIRK YTERRALLC~ENDDA YTERRALLC~BEGDA
  YTERRALLC~PLANS  FROM YTERRALLC INTO TABLE  IT_YTERALC2  WHERE YTERRALLC~ENDDA EQ '99991231'.




  C_DATE = S_BEGDA-LOW.
  YMTH2 = C_DATE+4(2).
  YYR1 = C_DATE+0(4).

  WHILE  C_DATE LE S_BEGDA-HIGH.
    SELECT  ZRPQV~MANDT ZRPQV~ZMONTH ZRPQV~ZYEAR ZRPQV~BZIRK ZRPQV~MATNR ZRPQV~GROSSPTS ZRPQV~GROSSQTY
        ZRPQV~RVAL ZRPQV~RQTY ZRPQV~NEPVAL ZRPQV~NEPQTY FROM ZRPQV INTO WA_ZRPQV
        WHERE  ZRPQV~ZYEAR EQ YYR1 AND ZRPQV~ZMONTH EQ YMTH2.  "AND ZRPQV~MATNR IN MATERIAL .
      APPEND WA_ZRPQV TO IT_ZRPQV.
      CLEAR WA_ZRPQV.
    ENDSELECT.

*****    SELECT  ZSAMP_PQV1~MANDT ZSAMP_PQV1~ZMONTH ZSAMP_PQV1~ZYEAR ZSAMP_PQV1~BZIRK ZSAMP_PQV1~MATNR ZSAMP_PQV1~GROSSPTS ZSAMP_PQV1~GROSSQTY
*****       ZSAMP_PQV1~RVAL ZSAMP_PQV1~RQTY ZSAMP_PQV1~NEPPTS ZSAMP_PQV1~NEPQTY FROM ZSAMP_PQV1 INTO WA_ZRPQV
*****       WHERE  ZSAMP_PQV1~ZYEAR EQ YYR1 AND ZSAMP_PQV1~ZMONTH EQ YMTH2.  "AND ZSAMP_PQV1~MATNR IN MATERIAL .
*****      APPEND WA_ZRPQV TO IT_ZRPQV.
*****      CLEAR WA_ZRPQV.
*****    ENDSELECT.


    CALL FUNCTION 'RE_ADD_MONTH_TO_DATE'
      EXPORTING
        MONTHS  = '1'
        OLDDATE = C_DATE
      IMPORTING
        NEWDATE = C_DATE.
    YMTH2 = C_DATE+4(2).
    YYR1 = C_DATE+0(4).

  ENDWHILE.

  C_DATE = S_BEGDA-LOW.
  CALL FUNCTION 'RE_ADD_MONTH_TO_DATE'
    EXPORTING
      MONTHS  = '-12'
      OLDDATE = C_DATE
    IMPORTING
      NEWDATE = C_DATE.
  YMTH2 = C_DATE+4(2).
  YYR1 = C_DATE+0(4).

  P_DATE1 = C_DATE .

  C_DATE = S_BEGDA-HIGH.
  CALL FUNCTION 'RE_ADD_MONTH_TO_DATE'
    EXPORTING
      MONTHS  = '-12'
      OLDDATE = C_DATE
    IMPORTING
      NEWDATE = C_DATE.

  P_DATE2 = C_DATE .

  WHILE P_DATE1 LE P_DATE2.
    SELECT  ZRPQV~MANDT ZRPQV~ZMONTH ZRPQV~ZYEAR ZRPQV~BZIRK ZRPQV~MATNR ZRPQV~GROSSPTS ZRPQV~GROSSQTY
            ZRPQV~RVAL ZRPQV~RQTY ZRPQV~NEPVAL ZRPQV~NEPQTY FROM ZRPQV INTO WA_MRPQV
            WHERE  ZRPQV~ZYEAR EQ YYR1  AND ZRPQV~ZMONTH  EQ YMTH2.
*                 AND ZRPQV~MATNR IN MATERIAL .
      APPEND WA_MRPQV TO IT_MRPQV.
      CLEAR WA_MRPQV.
    ENDSELECT.
*****    SELECT  ZSAMP_PQV1~MANDT ZSAMP_PQV1~ZMONTH ZSAMP_PQV1~ZYEAR ZSAMP_PQV1~BZIRK ZSAMP_PQV1~MATNR ZSAMP_PQV1~GROSSPTS ZSAMP_PQV1~GROSSQTY
*****            ZSAMP_PQV1~RVAL ZSAMP_PQV1~RQTY ZSAMP_PQV1~NEPPTS ZSAMP_PQV1~NEPQTY FROM ZSAMP_PQV1 INTO WA_MRPQV
*****            WHERE  ZSAMP_PQV1~ZYEAR EQ YYR1  AND ZSAMP_PQV1~ZMONTH  EQ YMTH2.
******                 AND ZSAMP_PQV1~MATNR IN MATERIAL .
*****      APPEND WA_MRPQV TO IT_MRPQV.
*****      CLEAR WA_MRPQV.
*****    ENDSELECT.
    CALL FUNCTION 'RE_ADD_MONTH_TO_DATE'
      EXPORTING
        MONTHS  = '1'
        OLDDATE = P_DATE1
      IMPORTING
        NEWDATE = P_DATE1.
    YMTH2 = P_DATE1+4(2).
    YYR1 = P_DATE1+0(4).
  ENDWHILE.




  SELECT  HRP1000~MANDT HRP1000~OTYPE HRP1000~OBJID HRP1000~BEGDA HRP1000~ENDDA HRP1000~MC_SHORT
  HRP1000~MC_STEXT FROM HRP1000 INTO TABLE  IT_HRP1000 WHERE HRP1000~OTYPE EQ 'S'  AND HRP1000~ENDDA EQ '99991231'.

  SELECT PA0001~MANDT PA0001~PERNR PA0001~BEGDA PA0001~ENDDA PA0001~ABKRS PA0001~ANSVH PA0001~PERSK
  PA0001~PLANS PA0001~ENAME PA0001~ZZ_HQCODE FROM PA0001 INTO TABLE IT_PA0001 WHERE PA0001~ENDDA EQ '99991231'.

  SELECT ZTHR_HEQ_DES~ZZ_HQCODE ZTHR_HEQ_DES~ZZ_HQDESC  FROM  ZTHR_HEQ_DES INTO TABLE ITAB_ZHQ.

  SELECT PA0000~PERNR PA0000~BEGDA FROM PA0000 INTO TABLE IT_ITAB1 WHERE MASSN = '01'.

  SELECT T171T~MANDT T171T~BZIRK T171T~BZTXT  FROM T171T INTO TABLE IT_T171 .


  SELECT ZDSMTER~ZDSM ZDSMTER~ZDSMSPART ZDSMTER~ZMONTH ZDSMTER~ZYEAR ZDSMTER~BZIRK ZDSMTER~SPART
  FROM ZDSMTER INTO  TABLE IT_ZDSMTER WHERE ZDSM LIKE 'D-%'
  AND ZMONTH EQ MMONTH AND ZYEAR EQ MYEAR   ORDER BY ZDSM BZIRK .
  DELETE ADJACENT DUPLICATES FROM IT_ZDSMTER COMPARING ZDSM BZIRK.

  SELECT ZDSMTER~ZDSM ZDSMTER~ZDSMSPART ZDSMTER~ZMONTH ZDSMTER~ZYEAR ZDSMTER~BZIRK ZDSMTER~SPART
  FROM ZDSMTER INTO  TABLE IT_RMTER WHERE ZDSM LIKE 'R-%'
  AND ZMONTH EQ MMONTH AND ZYEAR EQ MYEAR  ORDER BY ZDSM  SPART BZIRK .
  DELETE ADJACENT DUPLICATES FROM IT_RMTER COMPARING ZDSM  SPART BZIRK.




  SELECT    ZDSMTER~ZDSM  ZDSMTER~ZDSMSPART  ZDSMTER~ZMONTH ZDSMTER~ZYEAR  ZDSMTER~BZIRK
  ZDSMTER~SPART FROM ZDSMTER INTO TABLE  IT_ZDSMTER
  WHERE  ZMONTH = MMONTH AND ZYEAR = MYEAR.

  SELECT ZDSMTER~ZDSM ZDSMTER~ZDSMSPART ZDSMTER~ZMONTH ZDSMTER~ZYEAR ZDSMTER~BZIRK ZDSMTER~SPART
  FROM ZDSMTER   INTO TABLE  IT_PSOTER
  WHERE ZMONTH = MMONTH AND ZYEAR = MYEAR. " and bzirk not in ('D-*', 'Z-*', 'G-*', 'R-*') .

  SELECT ZDSMTER~ZDSM ZDSMTER~ZDSMSPART ZDSMTER~ZMONTH ZDSMTER~ZYEAR ZDSMTER~BZIRK ZDSMTER~SPART
  FROM ZDSMTER   INTO TABLE  IT_PSOTER1
  WHERE ZMONTH = MMONTH AND ZYEAR = MYEAR.  " and   bzirk not in ('D-*', 'Z-*', 'G-*','R-*') .

  SORT IT_PSOTER1 BY BZIRK SPART.

  DELETE ADJACENT DUPLICATES FROM IT_PSOTER1 COMPARING BZIRK SPART.









  SELECT YSD_DIST_TARGT~MANDT YSD_DIST_TARGT~SPART YSD_DIST_TARGT~BZIRK YSD_DIST_TARGT~TRGYEAR
   YSD_DIST_TARGT~MONTH01 YSD_DIST_TARGT~MONTH02 YSD_DIST_TARGT~MONTH03 YSD_DIST_TARGT~MONTH04
   YSD_DIST_TARGT~MONTH05 YSD_DIST_TARGT~MONTH06 YSD_DIST_TARGT~MONTH07 YSD_DIST_TARGT~MONTH08
   YSD_DIST_TARGT~MONTH09 YSD_DIST_TARGT~MONTH10 YSD_DIST_TARGT~MONTH11 YSD_DIST_TARGT~MONTH12
   FROM YSD_DIST_TARGT  INTO TABLE IT_SD_TARGET WHERE  YSD_DIST_TARGT~TRGYEAR EQ TRGYR.


  C_DATE = S_BEGDA-LOW.
  YMTH2 = C_DATE+4(2).
  YYR1 = C_DATE+0(4).


  SORT IT_T171 BY BZIRK.
  SORT IT_YTERALC BY BZIRK.










  LOOP AT IT_T171  ASSIGNING <FS_T171>.
    CNT = 0.
    READ TABLE  IT_YTERALC  INTO  WA_YTERALC  WITH KEY  BZIRK =   <FS_T171>-BZIRK .
    IF SY-SUBRC = 0.
      WA_YTERALC1-MANDT = WA_YTERALC-MANDT.
      WA_YTERALC1-SPART = WA_YTERALC-SPART.
      WA_YTERALC1-BZIRK = WA_YTERALC-BZIRK.
      WA_YTERALC1-ENDDA = WA_YTERALC-ENDDA.
      WA_YTERALC1-BEGDA = WA_YTERALC-BEGDA.
      WA_YTERALC1-PLANS = WA_YTERALC-PLANS.
      CNT = CNT + 1.
      POS = 0.
      NPOS = 0.
      SEARCH <FS_T171>-BZTXT FOR '-'.
      IF SY-SUBRC = 0.
        POS = SY-FDPOS .
*                if <fs_t171>-BZTXT+pos(1) = ' '.
*                   pos = pos + 1.
*                endif.
      ENDIF.
      IF POS > 0  .
        WA_YTERALC1-BZTXT = <FS_T171>-BZTXT(POS).
      ELSE .
        WA_YTERALC1-BZTXT = <FS_T171>-BZTXT.
      ENDIF.
      "endloop.
*          read table  it_psoter into wa_psoter with key  bzirk =  <fs_t171>-bzirk.
*
*          if wa_psoter-spart = '50'.
*             read table  it_psoter into wa_psoter1 with key  bzirk =  <fs_t171>-bzirk   spart = '60'.
*             if sy-subrc = 0.
*                wa_yteralc1-mdiv = 'BCL'.
*             else.
*                wa_yteralc1-mdiv = 'BC'.
*             endif.
*         elseif wa_psoter-spart = '60'.
*             read table  it_psoter into wa_psoter1 with key  bzirk =  <fs_t171>-bzirk  spart = '50'.
*             if sy-subrc = 0.
*                wa_yteralc1-mdiv = 'BCL'.
*             else.
*                wa_yteralc1-mdiv = 'EXL'.
*             endif.
*         endif.
      CLEAR :  DCOUNT.
      READ TABLE  IT_PSOTER INTO WA_PSOTER WITH KEY  BZIRK =  <FS_T171>-BZIRK SPART = '50'.
      IF SY-SUBRC EQ 0.
        DCOUNT = DCOUNT + 1.
        WA_YTERALC1-MDIV = 'BC'.
      ENDIF.
      READ TABLE  IT_PSOTER INTO WA_PSOTER WITH KEY  BZIRK =  <FS_T171>-BZIRK SPART = '60'.
      IF SY-SUBRC EQ 0.
        DCOUNT = DCOUNT + 1.
        WA_YTERALC1-MDIV = 'EXL'.
      ENDIF.
      READ TABLE  IT_PSOTER INTO WA_PSOTER WITH KEY  BZIRK =  <FS_T171>-BZIRK SPART = '70'.
      IF SY-SUBRC EQ 0.
        DCOUNT = DCOUNT + 1.
        WA_YTERALC1-MDIV = 'LS'.
      ENDIF.
      IF DCOUNT GT 1.
        WA_YTERALC1-MDIV = 'BCL'.
      ENDIF.

      APPEND WA_YTERALC1 TO IT_YTERALC1.
    ENDIF.
  ENDLOOP.
  CLEAR WA_YTERALC1.


  LOOP AT IT_SAMP INTO WA_SAMP.
    WA_PRD-MATNR =  WA_SAMP-SAMPCODE.

    SELECT SINGLE * FROM  MAKT INTO  IT_MAKT WHERE MATNR = WA_SAMP-SAMPCODE.
    WA_PRD-MAKTX =  IT_MAKT-MAKTX.

    SELECT SINGLE * FROM MARA  INTO IT_MARA WHERE MATNR = WA_SAMP-SAMPCODE.
    WA_PRD-MTART =  IT_MARA-MTART.
    COLLECT WA_PRD INTO IT_PRD.
    CLEAR WA_PRD.
  ENDLOOP.

  SORT IT_PRD BY MATNR.
  DELETE ADJACENT DUPLICATES FROM IT_PRD COMPARING MATNR.



  LOOP AT IT_SAMP INTO WA_SAMP.
    IF WA_SAMP-BZIRK+0(2) <> 'D-' AND WA_SAMP-BZIRK+0(2) <> 'R-' AND  WA_SAMP-BZIRK+0(2) <> 'Z-'..
      WA_TSAMP-ZMONTH  =  WA_SAMP-ZMONTH.
      WA_TSAMP-ZYEAR =  WA_SAMP-ZYEAR.
      WA_TSAMP-BZIRK =  WA_SAMP-BZIRK.
      READ TABLE IT_PRD INTO WA_PRD WITH KEY  MATNR = WA_SAMP-SAMPCODE.
      IF SY-SUBRC = 0.
        IF WA_PRD-MTART = 'ZDSM'.
          WA_TSAMP-SAMPLE =  WA_SAMP-SAMPQTY .
        ELSEIF WA_PRD-MTART = 'ZDSI'.
          WA_TSAMP-SPR = WA_SAMP-SAMPQTY.
        ENDIF.
      ENDIF.



      COLLECT WA_TSAMP INTO IT_TSAMP.
      CLEAR WA_TSAMP.
    ENDIF.
  ENDLOOP.









  LOOP AT IT_ZRPQV ASSIGNING <FS_ZRPQV>.
    WA_ZRPQV1-BZIRK = <FS_ZRPQV>-BZIRK.
    WA_ZRPQV1-GROSSPTS = <FS_ZRPQV>-GROSSPTS.
    WA_ZRPQV1-GROSSQTY = <FS_ZRPQV>-GROSSQTY.
    WA_ZRPQV1-RVAL = <FS_ZRPQV>-RVAL.
    WA_ZRPQV1-RQTY = <FS_ZRPQV>-RQTY.
    WA_ZRPQV1-NEPVAL = <FS_ZRPQV>-NEPVAL.
    WA_ZRPQV1-NEPQTY = <FS_ZRPQV>-NEPQTY.
    COLLECT WA_ZRPQV1 INTO IT_ZRPQV1.
    CLEAR  WA_ZRPQV1.
  ENDLOOP.
  LOOP AT IT_MRPQV ASSIGNING <FS_MRPQV>.
    WA_MRPQV1-BZIRK = <FS_MRPQV>-BZIRK.
    WA_MRPQV1-GROSSPTS = <FS_MRPQV>-GROSSPTS.
    WA_MRPQV1-GROSSQTY = <FS_MRPQV>-GROSSQTY.
    WA_MRPQV1-RVAL = <FS_MRPQV>-RVAL.
    WA_MRPQV1-RQTY = <FS_MRPQV>-RQTY.
    WA_MRPQV1-NEPVAL = <FS_MRPQV>-NEPVAL.
    WA_MRPQV1-NEPQTY = <FS_MRPQV>-NEPQTY.
    COLLECT WA_MRPQV1 INTO IT_MRPQV1.
    CLEAR  WA_ZRPQV1.

  ENDLOOP.

  LOOP AT IT_ZRPQV1 ASSIGNING <FS_ZRPQV1>.
    WA_SESALE-BZIRK = <FS_ZRPQV1>-BZIRK.
    WA_SESALE-SALES = <FS_ZRPQV1>-GROSSPTS .
    WA_SESALE-QTY = <FS_ZRPQV1>-GROSSQTY .
    COLLECT WA_SESALE INTO IT_SESALE.
    CLEAR  WA_SESALE.
  ENDLOOP.
  LOOP AT IT_MRPQV1 ASSIGNING <FS_MRPQV1>.
    WA_SESALE-BZIRK = <FS_MRPQV1>-BZIRK.
    WA_SESALE-PSALES = <FS_MRPQV1>-GROSSPTS .
    WA_SESALE-PQTY = <FS_MRPQV1>-GROSSQTY .
    COLLECT WA_SESALE INTO IT_SESALE.
    CLEAR  WA_SESALE.
  ENDLOOP.








  LOOP AT IT_TSAMP ASSIGNING <FS_TSAMP> .

    LOOP AT IT_SESALE ASSIGNING <FS_SESALE> WHERE BZIRK = <FS_TSAMP>-BZIRK.
      WA_REPORT-BZIRK = <FS_SESALE>-BZIRK.
      WA_REPORT-SALES = <FS_SESALE>-SALES.
      WA_REPORT-QTY = <FS_SESALE>-QTY .
      WA_REPORT-PSALES = <FS_SESALE>-PSALES.
      WA_REPORT-PQTY = <FS_SESALE>-PQTY .
    ENDLOOP.

    WA_REPORT-SAMPLE =   <FS_TSAMP>-SAMPLE .
    WA_REPORT-SPR =     <FS_TSAMP>-SPR .

    READ  TABLE IT_YTERALC1  INTO WA_YTERALC WITH KEY  BZIRK = <FS_TSAMP>-BZIRK.
    IF SY-SUBRC = 0.
      WA_REPORT-DIV = WA_YTERALC-MDIV.
      CNT = 0.
      LOOP AT  IT_PA0001  ASSIGNING <FS_PA0001> WHERE PLANS  =  WA_YTERALC-PLANS .
        WA_REPORT-PERNR =  <FS_PA0001>-PERNR.
        WA_REPORT-ENAME =  <FS_PA0001>-ENAME.
        READ TABLE ITAB_ZHQ  INTO  WA_ZHQ  WITH KEY  ZZ_HQCODE =   <FS_PA0001>-ZZ_HQCODE.
        IF SY-SUBRC = 0.
          WA_REPORT-ZZ_HQDESC =  WA_ZHQ-ZZ_HQDESC.
        ENDIF.
        CNT = CNT + 1.
      ENDLOOP.
      IF CNT = 0.
        WA_REPORT-ENAME =  'VACANT'.
        WA_REPORT-ZZ_HQDESC =   WA_YTERALC-BZTXT.
      ENDIF.
      READ TABLE  IT_HRP1000  INTO  WA_HRP1000 WITH KEY  OBJID   = WA_YTERALC-PLANS .
      IF SY-SUBRC = 0.
        WA_REPORT-DES =  WA_HRP1000-MC_SHORT.
      ENDIF.
    ENDIF.




    READ TABLE  IT_RMTER INTO  WA_RMTER  WITH KEY  BZIRK = WA_YTERALC-BZIRK.
    IF SY-SUBRC = 0.
      WA_REPORT-ZRSM = WA_RMTER-ZDSM.
      READ TABLE  IT_ZDSMTER INTO  WA_DSMTER WITH KEY  BZIRK =  WA_RMTER-ZDSM.
      IF SY-SUBRC = 0.
        WA_REPORT-ZDSM = WA_DSMTER-ZDSM.
      ENDIF.
    ENDIF.

    APPEND WA_REPORT TO ITAB_REPORT1.
    CLEAR WA_REPORT.

  ENDLOOP.
  CLEAR WA_REPORT.



  LOOP AT ITAB_REPORT1 ASSIGNING <FS_REPORT>.
    IF <FS_REPORT>-DIV = 'BC'.
      WA_REPORT-PERNR = <FS_REPORT>-PERNR.
      WA_REPORT-BZIRK = <FS_REPORT>-BZIRK.
      WA_REPORT-DES = <FS_REPORT>-DES.
      WA_REPORT-DIV = <FS_REPORT>-DIV.
      WA_REPORT-ENAME = <FS_REPORT>-ENAME.
      WA_REPORT-SALES = <FS_REPORT>-SALES.
      WA_REPORT-SAMPLE = <FS_REPORT>-SAMPLE.
      WA_REPORT-SPR = <FS_REPORT>-SPR.
      WA_REPORT-QTY = <FS_REPORT>-QTY.
      WA_REPORT-PSALES = <FS_REPORT>-PSALES.
      WA_REPORT-PQTY = <FS_REPORT>-PQTY.

      WA_REPORT-ZZ_HQCODE = <FS_REPORT>-ZZ_HQCODE.
      WA_REPORT-ZZ_HQDESC = <FS_REPORT>-ZZ_HQDESC.
      WA_REPORT-ZDSM = <FS_REPORT>-ZDSM.
      WA_REPORT-ZRSM = <FS_REPORT>-ZRSM.


      LOOP AT IT_ITAB1 ASSIGNING <FS_ITAB1> WHERE  PERNR = <FS_REPORT>-PERNR  .
        WA_REPORT-DOJ = <FS_ITAB1>-DTJOIN.
      ENDLOOP.
      APPEND WA_REPORT TO ITAB_REPORT2.
      CLEAR WA_REPORT.
    ENDIF.
    IF <FS_REPORT>-DIV = 'BCL'.
      WA_REPORT-PERNR = <FS_REPORT>-PERNR.
      WA_REPORT-BZIRK = <FS_REPORT>-BZIRK.
      WA_REPORT-DES = <FS_REPORT>-DES.
      WA_REPORT-DIV = <FS_REPORT>-DIV.
      WA_REPORT-ENAME = <FS_REPORT>-ENAME.
      WA_REPORT-SALES = <FS_REPORT>-SALES.
      WA_REPORT-SAMPLE = <FS_REPORT>-SAMPLE.
      WA_REPORT-SPR = <FS_REPORT>-SPR.
      WA_REPORT-QTY = <FS_REPORT>-QTY.
      WA_REPORT-PSALES = <FS_REPORT>-PSALES.
      WA_REPORT-PQTY = <FS_REPORT>-PQTY.

      WA_REPORT-ZZ_HQCODE = <FS_REPORT>-ZZ_HQCODE.
      WA_REPORT-ZZ_HQDESC = <FS_REPORT>-ZZ_HQDESC.
      WA_REPORT-ZDSM = <FS_REPORT>-ZDSM.
      WA_REPORT-ZRSM = <FS_REPORT>-ZRSM.

      LOOP AT IT_ITAB1 ASSIGNING <FS_ITAB1> WHERE  PERNR = <FS_REPORT>-PERNR  .
        WA_REPORT-DOJ = <FS_ITAB1>-DTJOIN.
      ENDLOOP.
      APPEND WA_REPORT TO ITAB_REPORT2.
      CLEAR WA_REPORT.
    ENDIF.
    IF <FS_REPORT>-DIV = 'EXL'.
      WA_REPORT-PERNR = <FS_REPORT>-PERNR.
      WA_REPORT-BZIRK = <FS_REPORT>-BZIRK.
      WA_REPORT-DES = <FS_REPORT>-DES.
      WA_REPORT-DIV = <FS_REPORT>-DIV.
      WA_REPORT-ENAME = <FS_REPORT>-ENAME.
      WA_REPORT-SALES = <FS_REPORT>-SALES.
      WA_REPORT-SAMPLE = <FS_REPORT>-SAMPLE.
      WA_REPORT-SPR = <FS_REPORT>-SPR.
      WA_REPORT-QTY = <FS_REPORT>-QTY.
      WA_REPORT-PSALES = <FS_REPORT>-PSALES.
      WA_REPORT-PQTY = <FS_REPORT>-PQTY.

      WA_REPORT-ZZ_HQCODE = <FS_REPORT>-ZZ_HQCODE.
      WA_REPORT-ZZ_HQDESC = <FS_REPORT>-ZZ_HQDESC.
      WA_REPORT-ZDSM = <FS_REPORT>-ZDSM.
      WA_REPORT-ZRSM = <FS_REPORT>-ZRSM.

      LOOP AT IT_ITAB1 ASSIGNING <FS_ITAB1> WHERE  PERNR = <FS_REPORT>-PERNR  .
        WA_REPORT-DOJ = <FS_ITAB1>-DTJOIN.
      ENDLOOP.
      APPEND WA_REPORT TO ITAB_REPORT2.
      CLEAR WA_REPORT.
    ENDIF.

    IF <FS_REPORT>-DIV = 'LS'.
      WA_REPORT-PERNR = <FS_REPORT>-PERNR.
      WA_REPORT-BZIRK = <FS_REPORT>-BZIRK.
      WA_REPORT-DES = <FS_REPORT>-DES.
      WA_REPORT-DIV = <FS_REPORT>-DIV.
      WA_REPORT-ENAME = <FS_REPORT>-ENAME.
      WA_REPORT-SALES = <FS_REPORT>-SALES.
      WA_REPORT-SAMPLE = <FS_REPORT>-SAMPLE.
      WA_REPORT-SPR = <FS_REPORT>-SPR.
      WA_REPORT-QTY = <FS_REPORT>-QTY.
      WA_REPORT-PSALES = <FS_REPORT>-PSALES.
      WA_REPORT-PQTY = <FS_REPORT>-PQTY.

      WA_REPORT-ZZ_HQCODE = <FS_REPORT>-ZZ_HQCODE.
      WA_REPORT-ZZ_HQDESC = <FS_REPORT>-ZZ_HQDESC.
      WA_REPORT-ZDSM = <FS_REPORT>-ZDSM.
      WA_REPORT-ZRSM = <FS_REPORT>-ZRSM.


      LOOP AT IT_ITAB1 ASSIGNING <FS_ITAB1> WHERE  PERNR = <FS_REPORT>-PERNR  .
        WA_REPORT-DOJ = <FS_ITAB1>-DTJOIN.
      ENDLOOP.
      APPEND WA_REPORT TO ITAB_REPORT2.
      CLEAR WA_REPORT.
    ENDIF.

  ENDLOOP.

  LOOP AT ITAB_REPORT2 ASSIGNING <FS_REPORT>.
    WA_REPORT-ZDSM = <FS_REPORT>-ZDSM.
    WA_REPORT-ZRSM = <FS_REPORT>-ZRSM.
    WA_REPORT-PERNR = <FS_REPORT>-PERNR.
    WA_REPORT-BZIRK = <FS_REPORT>-BZIRK.
    WA_REPORT-DES = <FS_REPORT>-DES.
    WA_REPORT-DIV = <FS_REPORT>-DIV.
    WA_REPORT-ENAME = <FS_REPORT>-ENAME.
    WA_REPORT-SALES = <FS_REPORT>-SALES.
    WA_REPORT-SAMPLE = <FS_REPORT>-SAMPLE.
    WA_REPORT-SPR = <FS_REPORT>-SPR.
    WA_REPORT-QTY = <FS_REPORT>-QTY.
    WA_REPORT-PSALES = <FS_REPORT>-PSALES.
    WA_REPORT-PQTY = <FS_REPORT>-PQTY.
    WA_REPORT-ZZ_HQCODE = <FS_REPORT>-ZZ_HQCODE.
    WA_REPORT-DOJ = <FS_REPORT>-DOJ.
    WA_REPORT-ZZ_HQDESC = <FS_REPORT>-ZZ_HQDESC.
    APPEND WA_REPORT TO ITAB_REPORT3.
    CLEAR WA_REPORT.
  ENDLOOP.



*if p_val = rbselected.
*   sort itab_report3 by sales DESCENDING.
*elseif p_qty = rbselected.
*   sort itab_report3 by qty DESCENDING.
*endif.



  T_CNT = 1.

  SORT ITAB_REPORT3 BY SAMPLE  DESCENDING.
  LOOP AT ITAB_REPORT3 ASSIGNING <FS_REPORT>.
    WA_REPORT-SRLNO = T_CNT.
    "WA_REPORT-PRNAME = P_HEAD3.
    WA_REPORT-ZDSM = <FS_REPORT>-ZDSM.
    WA_REPORT-ZRSM = <FS_REPORT>-ZRSM.
    WA_REPORT-PERNR = <FS_REPORT>-PERNR.
    WA_REPORT-BZIRK = <FS_REPORT>-BZIRK.
    WA_REPORT-DES = <FS_REPORT>-DES.
    WA_REPORT-DIV = <FS_REPORT>-DIV.
    WA_REPORT-ENAME = <FS_REPORT>-ENAME.
    WA_REPORT-SALES = <FS_REPORT>-SALES.
    WA_REPORT-SAMPLE = <FS_REPORT>-SAMPLE.
    WA_REPORT-SPR = <FS_REPORT>-SPR.
    WA_REPORT-AVGSALES = <FS_REPORT>-SALES / M_CNT .
    WA_REPORT-PSALES = <FS_REPORT>-PSALES.
    WA_REPORT-PQTY = <FS_REPORT>-PQTY.

    WA_REPORT-QTY = <FS_REPORT>-QTY.
    WA_REPORT-AVGQTY = <FS_REPORT>-QTY / M_CNT.
    WA_REPORT-ZZ_HQCODE = <FS_REPORT>-ZZ_HQCODE.
    WA_REPORT-DOJ = <FS_REPORT>-DOJ.
    WA_REPORT-ZZ_HQDESC = <FS_REPORT>-ZZ_HQDESC.
    READ TABLE IT_YTERALC1  INTO  WA_YTERALC  WITH KEY BZIRK = <FS_REPORT>-ZDSM.
    IF SY-SUBRC = 0.
      READ  TABLE IT_PA0001  INTO WA_PA0001 WITH KEY  PLANS   = WA_YTERALC-PLANS .
      IF SY-SUBRC = 0.
        WA_REPORT-ZMNAME =  WA_PA0001-ENAME.
      ELSE.
        WA_REPORT-ZMNAME =  'VACANT'.
      ENDIF.
    ENDIF.

    READ TABLE IT_YTERALC1  INTO  WA_YTERALC  WITH KEY BZIRK = <FS_REPORT>-ZRSM.
    IF SY-SUBRC = 0.
      READ  TABLE IT_PA0001  INTO WA_PA0001 WITH KEY  PLANS   = WA_YTERALC-PLANS .
      IF SY-SUBRC = 0.
        WA_REPORT-RMNAME =  WA_PA0001-ENAME.
      ELSE.
        WA_REPORT-RMNAME =  'VACANT'.
      ENDIF.

    ENDIF.

    IF WA_REPORT-PSALES NE 0 .
      WA_REPORT-GRTH = ( WA_REPORT-SALES - WA_REPORT-PSALES ) /  WA_REPORT-PSALES * 100.
    ELSE.
      WA_REPORT-GRTH = 100 .

    ENDIF.


    "===================================

    READ TABLE  IT_SD_TARGET INTO  WA_SD_TARGET  WITH KEY  BZIRK = <FS_REPORT>-BZIRK .

    IF SY-SUBRC =  0.


      C_DATE = S_BEGDA-LOW.
      YMTH2 = C_DATE+4(2).
      YYR1 = C_DATE+0(4).

      WHILE  C_DATE LE S_BEGDA-HIGH.

        YMTH2 = C_DATE+4(2).
        YYR1 = C_DATE+0(4).
        IF YMTH2 = 4.
          TRGTVAL = TRGTVAL + WA_SD_TARGET-MONTH01.
        ELSEIF YMTH2 = 5.
          TRGTVAL = TRGTVAL + WA_SD_TARGET-MONTH02.
        ELSEIF YMTH2 = 6.
          TRGTVAL = TRGTVAL + WA_SD_TARGET-MONTH03.
        ELSEIF YMTH2 = 7.
          TRGTVAL = TRGTVAL + WA_SD_TARGET-MONTH04.
        ELSEIF YMTH2 = 8.
          TRGTVAL = TRGTVAL + WA_SD_TARGET-MONTH05.
        ELSEIF YMTH2 = 9.
          TRGTVAL = TRGTVAL + WA_SD_TARGET-MONTH06.
        ELSEIF YMTH2 = 10.
          TRGTVAL = TRGTVAL + WA_SD_TARGET-MONTH07.
        ELSEIF YMTH2 = 11.
          TRGTVAL = TRGTVAL + WA_SD_TARGET-MONTH08.
        ELSEIF YMTH2 = 12.
          TRGTVAL = TRGTVAL + WA_SD_TARGET-MONTH09.
        ELSEIF YMTH2 = 1.
          TRGTVAL = TRGTVAL + WA_SD_TARGET-MONTH10.
        ELSEIF YMTH2 = 2.
          TRGTVAL = TRGTVAL + WA_SD_TARGET-MONTH11.
        ELSEIF YMTH2 = 3.
          TRGTVAL = TRGTVAL + WA_SD_TARGET-MONTH12.
        ENDIF.


        CALL FUNCTION 'RE_ADD_MONTH_TO_DATE'
          EXPORTING
            MONTHS  = '1'
            OLDDATE = C_DATE
          IMPORTING
            NEWDATE = C_DATE.
        YMTH2 = C_DATE+4(2).
        YYR1 = C_DATE+0(4).
      ENDWHILE.
      WA_REPORT-TARGET = TRGTVAL.
      WA_REPORT-AVGTARGET = TRGTVAL / M_CNT.
      IF TRGTVAL NE 0 .
        WA_REPORT-PERTGT = ( WA_REPORT-SALES - TRGTVAL ) / TRGTVAL * 100.
      ELSE.
        WA_REPORT-PERTGT = 100 .
      ENDIF.
      TRGTVAL = 0.
    ENDIF.



    "===================================



    APPEND WA_REPORT TO ITAB_REPORT4.
    CLEAR WA_REPORT.
    T_CNT = T_CNT + 1.
  ENDLOOP.



ENDFORM.






FORM GRD-DATA.
  WA_FIELDCAT-FIELDNAME = 'SRLNO'.
  WA_FIELDCAT-SELTEXT_L = 'SRL'.
  WA_FIELDCAT-SELTEXT_M = 'SRL'.
  WA_FIELDCAT-SELTEXT_S = 'SRL'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'PRNAME'.
  WA_FIELDCAT-SELTEXT_L = 'PR. NAME'.
  WA_FIELDCAT-SELTEXT_M = 'PR. NAME'.
  WA_FIELDCAT-SELTEXT_S = 'PR. NAME'.
  APPEND WA_FIELDCAT TO FIELDCAT.


  WA_FIELDCAT-FIELDNAME = 'ZDSM'.
  WA_FIELDCAT-SELTEXT_L = 'ZDSM'.
  WA_FIELDCAT-SELTEXT_M = 'ZDSM'.
  WA_FIELDCAT-SELTEXT_S = 'ZDSM'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'ZMNAME'.
  WA_FIELDCAT-SELTEXT_L = 'ZMNAME'.
  WA_FIELDCAT-SELTEXT_M = 'ZMNAME'.
  WA_FIELDCAT-SELTEXT_S = 'ZMNAME'.
  APPEND WA_FIELDCAT TO FIELDCAT.


  WA_FIELDCAT-FIELDNAME = 'ZRSM'.
  WA_FIELDCAT-SELTEXT_L = 'ZRSM'.
  WA_FIELDCAT-SELTEXT_M = 'ZRSM'.
  WA_FIELDCAT-SELTEXT_S = 'ZRSM'.
  APPEND WA_FIELDCAT TO FIELDCAT.


  WA_FIELDCAT-FIELDNAME = 'RMNAME'.
  WA_FIELDCAT-SELTEXT_L = 'RMNAME'.
  WA_FIELDCAT-SELTEXT_M = 'RMNAME'.
  WA_FIELDCAT-SELTEXT_S = 'RMNAME'.
  APPEND WA_FIELDCAT TO FIELDCAT.



  WA_FIELDCAT-FIELDNAME = 'PERNR'.
  WA_FIELDCAT-SELTEXT_L = 'PERNR'.
  WA_FIELDCAT-SELTEXT_M = 'PERNR'.
  WA_FIELDCAT-SELTEXT_S = 'PERNR'.
  APPEND WA_FIELDCAT TO FIELDCAT.


  WA_FIELDCAT-FIELDNAME = 'ENAME'.
  WA_FIELDCAT-SELTEXT_L = 'EMP NAME'.
  WA_FIELDCAT-SELTEXT_M = 'EMP NAME'.
  WA_FIELDCAT-SELTEXT_S = 'EMP NAME'.
  APPEND WA_FIELDCAT TO FIELDCAT.


  WA_FIELDCAT-FIELDNAME = 'BZIRK'.
  WA_FIELDCAT-SELTEXT_L = 'BZIRK'.
  WA_FIELDCAT-SELTEXT_M = 'BZIRK'.
  WA_FIELDCAT-SELTEXT_S = 'BZIRK'.
  APPEND WA_FIELDCAT TO FIELDCAT.




  WA_FIELDCAT-FIELDNAME = 'DIV'.
  WA_FIELDCAT-SELTEXT_L = 'DIVISION'.
  WA_FIELDCAT-SELTEXT_M = 'DIVISION'.
  WA_FIELDCAT-SELTEXT_S = 'DIVISION'.
  APPEND WA_FIELDCAT TO FIELDCAT.


  WA_FIELDCAT-FIELDNAME = 'DES'.
  WA_FIELDCAT-SELTEXT_L = 'DES'.
  WA_FIELDCAT-SELTEXT_M = 'DES'.
  WA_FIELDCAT-SELTEXT_S = 'DES'.
  APPEND WA_FIELDCAT TO FIELDCAT.


  WA_FIELDCAT-FIELDNAME = 'DOJ'.
  WA_FIELDCAT-SELTEXT_L = 'DT.OF.JOIN'.
  WA_FIELDCAT-SELTEXT_M = 'DT.OF JOIN'.
  WA_FIELDCAT-SELTEXT_S = 'DT.OF JOIN'.
  APPEND WA_FIELDCAT TO FIELDCAT.



  WA_FIELDCAT-FIELDNAME = 'ZZ_HQDESC'.
  WA_FIELDCAT-SELTEXT_L = 'H Q'.
  WA_FIELDCAT-SELTEXT_M = 'H Q'.
  WA_FIELDCAT-SELTEXT_S = 'H Q'.
  APPEND WA_FIELDCAT TO FIELDCAT.


*  wa_fieldcat-fieldname = 'SALES'.
*  wa_fieldcat-seltext_l = 'SALES'.
*  wa_fieldcat-seltext_m = 'SALES'.
*  wa_fieldcat-seltext_s = 'SALES'.
*  append wa_fieldcat to fieldcat.

  WA_FIELDCAT-FIELDNAME = 'AVGSALES'.
  WA_FIELDCAT-SELTEXT_L = 'AVG SALES'.
  WA_FIELDCAT-SELTEXT_M = 'AVG SALES'.
  WA_FIELDCAT-SELTEXT_S = 'AVG SALES'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'AVGTARGET'.
  WA_FIELDCAT-SELTEXT_L = 'AVG TARGET'.
  WA_FIELDCAT-SELTEXT_M = 'AVG TARGET'.
  WA_FIELDCAT-SELTEXT_S = 'AVG TARGET'.
  APPEND WA_FIELDCAT TO FIELDCAT.


  WA_FIELDCAT-FIELDNAME = 'PERTGT'.
  WA_FIELDCAT-SELTEXT_L = 'PER TO TGT'.
  WA_FIELDCAT-SELTEXT_M = 'PER TO TGT'.
  WA_FIELDCAT-SELTEXT_S = 'PER TO TGT'.
  APPEND WA_FIELDCAT TO FIELDCAT.



*  wa_fieldcat-fieldname = 'QTY'.
*  wa_fieldcat-seltext_l = 'QTY'.
*  wa_fieldcat-seltext_m = 'QTY'.
*  wa_fieldcat-seltext_s = 'QTY'.
*  append wa_fieldcat to fieldcat.
*
*
*
*
*  wa_fieldcat-fieldname = 'AVGQTY'.
*  wa_fieldcat-seltext_l = 'AVG QTY'.
*  wa_fieldcat-seltext_m = 'AVG QTY'.
*  wa_fieldcat-seltext_s = 'AVG QTY'.
*  append wa_fieldcat to fieldcat.
*
*  wa_fieldcat-fieldname = 'PQTY'.
*  wa_fieldcat-seltext_l = 'PQTY'.
*  wa_fieldcat-seltext_m = 'PQTY'.
*  wa_fieldcat-seltext_s = 'PQTY'.
*  append wa_fieldcat to fieldcat.
*
*  wa_fieldcat-fieldname = 'PSALES'.
*  wa_fieldcat-seltext_l = 'PSALES'.
*  wa_fieldcat-seltext_m = 'PSALES'.
*  wa_fieldcat-seltext_s = 'PSALES'.
*  append wa_fieldcat to fieldcat.

  WA_FIELDCAT-FIELDNAME = 'GRTH'.
  WA_FIELDCAT-SELTEXT_L = 'GROWTH'.
  WA_FIELDCAT-SELTEXT_M = 'GROWTH'.
  WA_FIELDCAT-SELTEXT_S = 'GROWTH'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'SAMPLE'.
  WA_FIELDCAT-SELTEXT_L = 'SAMPLE'.
  WA_FIELDCAT-SELTEXT_M = 'SAMPLE'.
  WA_FIELDCAT-SELTEXT_S = 'SAMPLE'.
  APPEND WA_FIELDCAT TO FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'SPR'.
  WA_FIELDCAT-SELTEXT_L = 'SPR'.
  WA_FIELDCAT-SELTEXT_M = 'SPR'.
  WA_FIELDCAT-SELTEXT_S = 'SPR'.
  APPEND WA_FIELDCAT TO FIELDCAT.




  CALL FUNCTION 'REUSE_ALV_GRID_DISPLAY'
    EXPORTING
*     I_INTERFACE_CHECK  = ' '
*     I_BYPASSING_BUFFER = ' '
*     I_BUFFER_ACTIVE    = ' '
      I_CALLBACK_PROGRAM = G_REPID
*     I_CALLBACK_PF_STATUS_SET          = ' '
*     I_CALLBACK_USER_COMMAND           = ' '
*     I_CALLBACK_TOP_OF_PAGE            = ' '
*     I_CALLBACK_HTML_TOP_OF_PAGE       = ' '
*     I_CALLBACK_HTML_END_OF_LIST       = ' '
*     I_STRUCTURE_NAME   =
*     I_BACKGROUND_ID    = ' '
*     I_GRID_TITLE       =
*     I_GRID_SETTINGS    =
*     IS_LAYOUT          =
      IT_FIELDCAT        = FIELDCAT
*     IT_EXCLUDING       =
*     IT_SPECIAL_GROUPS  =
*     IT_SORT            =
*     IT_FILTER          =
*     IS_SEL_HIDE        =
*     I_DEFAULT          = 'X'
*     I_SAVE             = ' '
*     IS_VARIANT         =
*     IT_EVENTS          =
*     IT_EVENT_EXIT      =
*     IS_PRINT           =
*     IS_REPREP_ID       =
*     I_SCREEN_START_COLUMN             = 0
*     I_SCREEN_START_LINE               = 0
*     I_SCREEN_END_COLUMN               = 0
*     I_SCREEN_END_LINE  = 0
*     I_HTML_HEIGHT_TOP  = 0
*     I_HTML_HEIGHT_END  = 0
**   IT_ALV_GRAPHICS                   =
*     IT_HYPERLINK       =
*     IT_ADD_FIELDCAT    =
*     IT_EXCEPT_QINFO    =
*     IR_SALV_FULLSCREEN_ADAPTER        =
* IMPORTING
*     E_EXIT_CAUSED_BY_CALLER           =
*     ES_EXIT_CAUSED_BY_USER            =
    TABLES
      T_OUTTAB           = ITAB_REPORT4
    EXCEPTIONS
      PROGRAM_ERROR      = 1
      OTHERS             = 2.
  IF SY-SUBRC <> 0.
  ENDIF.
ENDFORM.

*
FORM  OPEN-FORM.
  CALL FUNCTION 'OPEN_FORM'
    EXPORTING
*     APPLICATION                 = 'TX'
*     ARCHIVE_INDEX               =
*     ARCHIVE_PARAMS              =
*     DEVICE                      = 'PRINTER'
*     DIALOG                      = 'X'
      FORM                        = 'ZSAMP_RANK'
*     LANGUAGE                    = SY-LANGU
*     OPTIONS                     =
*     MAIL_SENDER                 =
*     MAIL_RECIPIENT              =
*     MAIL_APPL_OBJECT            =
*     RAW_DATA_INTERFACE          = '*'
*     SPONUMIV                    =
*   IMPORTING
*     LANGUAGE                    =
*     NEW_ARCHIVE_PARAMS          =
*     RESULT                      =
    EXCEPTIONS
      CANCELED                    = 1
      DEVICE                      = 2
      FORM                        = 3
      OPTIONS                     = 4
      UNCLOSED                    = 5
      MAIL_OPTIONS                = 6
      ARCHIVE_ERROR               = 7
      INVALID_FAX_NUMBER          = 8
      MORE_PARAMS_NEEDED_IN_BATCH = 9
      SPOOL_ERROR                 = 10
      CODEPAGE                    = 11
      OTHERS                      = 12.
  IF SY-SUBRC <> 0.
* MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO
*         WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4.
  ENDIF.




ENDFORM    .
*
FORM START-FORM.
  CALL FUNCTION 'START_FORM'
    EXPORTING
*     ARCHIVE_INDEX          =
      FORM        = 'ZSAMP_RANK'
*     LANGUAGE    = ' '
*     STARTPAGE   = ' '
*     PROGRAM     = ' '
*     MAIL_APPL_OBJECT       =
* IMPORTING
*     LANGUAGE    =
    EXCEPTIONS
      FORM        = 1
      FORMAT      = 2
      UNENDED     = 3
      UNOPENED    = 4
      UNUSED      = 5
      SPOOL_ERROR = 6
      CODEPAGE    = 7
      OTHERS      = 8.
  IF SY-SUBRC <> 0.
    MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO
            WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4.
  ENDIF.


ENDFORM.

FORM WRITE-FORM.

  CALL FUNCTION 'WRITE_FORM'
    EXPORTING
      ELEMENT                  = 'E1'
*     FUNCTION                 = 'SET'
*     TYPE                     = 'BODY'
      WINDOW                   = 'MAIN'
* IMPORTING
*     PENDING_LINES            =
    EXCEPTIONS
      ELEMENT                  = 1
      FUNCTION                 = 2
      TYPE                     = 3
      UNOPENED                 = 4
      UNSTARTED                = 5
      WINDOW                   = 6
      BAD_PAGEFORMAT_FOR_PRINT = 7
      SPOOL_ERROR              = 8
      CODEPAGE                 = 9
      OTHERS                   = 10.



  IF SY-SUBRC <> 0.
    MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO
            WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4.
  ENDIF.

ENDFORM.                    " WRITE_FORM


FORM END-FORM.
  CALL FUNCTION 'END_FORM'
* IMPORTING
*   RESULT                         =
    EXCEPTIONS
      UNOPENED                 = 1
      BAD_PAGEFORMAT_FOR_PRINT = 2
      SPOOL_ERROR              = 3
      CODEPAGE                 = 4
      OTHERS                   = 5.
  IF SY-SUBRC <> 0.
    MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO
            WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4.
  ENDIF.



ENDFORM.
*
FORM CLOSE-FORM.
  CALL FUNCTION 'CLOSE_FORM'
* IMPORTING
*   RESULT                         =
    EXCEPTIONS
      UNOPENED                 = 1
      BAD_PAGEFORMAT_FOR_PRINT = 2
      SEND_ERROR               = 3
      SPOOL_ERROR              = 4
      CODEPAGE                 = 5
      OTHERS                   = 6.
  IF SY-SUBRC <> 0.
    MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO
            WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4.
  ENDIF.

ENDFORM.


FORM OPEN-PDF-FORM.
  CALL FUNCTION 'OPEN_FORM'
    EXPORTING
*     APPLICATION                 = 'TX'
*     ARCHIVE_INDEX               =
*     ARCHIVE_PARAMS              =
      DEVICE                      = 'PRINTER'
      DIALOG                      = SPACE
      FORM                        = 'ZSAMP_RANK'
*     LANGUAGE                    = SY-LANGU
      OPTIONS                     = STRUCT
*     MAIL_SENDER                 =
*     MAIL_RECIPIENT              =
*     MAIL_APPL_OBJECT            =
*     RAW_DATA_INTERFACE          = '*'
*     SPONUMIV                    =
*   IMPORTING
*     LANGUAGE                    =
*     NEW_ARCHIVE_PARAMS          =
*     RESULT                      =
    EXCEPTIONS
      CANCELED                    = 1
      DEVICE                      = 2
      FORM                        = 3
      OPTIONS                     = 4
      UNCLOSED                    = 5
      MAIL_OPTIONS                = 6
      ARCHIVE_ERROR               = 7
      INVALID_FAX_NUMBER          = 8
      MORE_PARAMS_NEEDED_IN_BATCH = 9
      SPOOL_ERROR                 = 10
      CODEPAGE                    = 11
      OTHERS                      = 12.
  IF SY-SUBRC <> 0.
* MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO
*         WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4.
  ENDIF.


ENDFORM.


FORM CLOSE-PDF-FORM.
  CALL FUNCTION 'CLOSE_FORM'
* IMPORTING
*   RESULT                         =
    TABLES
      OTFDATA                  = DATAB[]
    EXCEPTIONS
      UNOPENED                 = 1
      BAD_PAGEFORMAT_FOR_PRINT = 2
      SEND_ERROR               = 3
      SPOOL_ERROR              = 4
      CODEPAGE                 = 5
      OTHERS                   = 6.
  IF SY-SUBRC <> 0.
    MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO
            WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4.
  ENDIF.

ENDFORM.




FORM CONVERT-PDF.

  CALL FUNCTION 'CONVERT_OTF'
    EXPORTING
      FORMAT                = 'PDF'
*     MAX_LINEWIDTH         = 132
*     ARCHIVE_INDEX         = ' '
*     COPYNUMBER            = 0
*     ASCII_BIDI_VIS2LOG    = ' '
*     PDF_DELETE_OTFTAB     = ' '
*     PDF_USERNAME          = ' '
*     PDF_PREVIEW           = ' '
*     USE_CASCADING         = ' '
    IMPORTING
      BIN_FILESIZE          = BINFILESIZE
*     BIN_FILE              =
    TABLES
      OTF                   = DATAB[]
      LINES                 = PDFTAB[]
    EXCEPTIONS
      ERR_MAX_LINEWIDTH     = 1
      ERR_FORMAT            = 2
      ERR_CONV_NOT_POSSIBLE = 3
      ERR_BAD_OTF           = 4
      OTHERS                = 5.
  IF SY-SUBRC <> 0.
* MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO
*         WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4.
  ENDIF.

ENDFORM.

FORM SELECT-DIRECTORY-AND-SAVE.

  CALL METHOD CL_GUI_FRONTEND_SERVICES=>FILE_SAVE_DIALOG
* EXPORTING
* WINDOW_TITLE =
* DEFAULT_EXTENSION =
* DEFAULT_FILE_NAME =
* FILE_FILTER =
* INITIAL_DIRECTORY =
* WITH_ENCODING =
* PROMPT_ON_OVERWRITE = 'X'
    CHANGING
      FILENAME = FILE_NAME
      PATH     = FILE_PATH
      FULLPATH = FULL_PATH
*     USER_ACTION =
*     FILE_ENCODING =
* EXCEPTIONS
*     CNTL_ERROR = 1
*     ERROR_NO_GUI = 2
*     NOT_SUPPORTED_BY_GUI = 3
*     others   = 4
    .
  IF SY-SUBRC <> 0.
* MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO
* WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4.
  ENDIF.
**********************


ENDFORM.

FORM DOWNLOAD.
  CALL FUNCTION 'GUI_DOWNLOAD'
    EXPORTING
      BIN_FILESIZE            = BINFILESIZE
      FILENAME                = FULL_PATH
      FILETYPE                = 'BIN'
*     APPEND                  = ' '
*     WRITE_FIELD_SEPARATOR   = ' '
*     HEADER                  = '00'
*     TRUNC_TRAILING_BLANKS   = ' '
*     WRITE_LF                = 'X'
*     COL_SELECT              = ' '
*     COL_SELECT_MASK         = ' '
*     DAT_MODE                = ' '
*     CONFIRM_OVERWRITE       = ' '
*     NO_AUTH_CHECK           = ' '
*     CODEPAGE                = ' '
*     IGNORE_CERR             = ABAP_TRUE
*     REPLACEMENT             = '#'
*     WRITE_BOM               = ' '
*     TRUNC_TRAILING_BLANKS_EOL       = 'X'
*     WK1_N_FORMAT            = ' '
*     WK1_N_SIZE              = ' '
*     WK1_T_FORMAT            = ' '
*     WK1_T_SIZE              = ' '
*     WRITE_LF_AFTER_LAST_LINE        = ABAP_TRUE
*     SHOW_TRANSFER_STATUS    = ABAP_TRUE
*     VIRUS_SCAN_PROFILE      = '/SCET/GUI_DOWNLOAD'
* IMPORTING
*     FILELENGTH              =
    TABLES
      DATA_TAB                = PDFTAB[]
*     FIELDNAMES              =
    EXCEPTIONS
      FILE_WRITE_ERROR        = 1
      NO_BATCH                = 2
      GUI_REFUSE_FILETRANSFER = 3
      INVALID_TYPE            = 4
      NO_AUTHORITY            = 5
      UNKNOWN_ERROR           = 6
      HEADER_NOT_ALLOWED      = 7
      SEPARATOR_NOT_ALLOWED   = 8
      FILESIZE_NOT_ALLOWED    = 9
      HEADER_TOO_LONG         = 10
      DP_ERROR_CREATE         = 11
      DP_ERROR_SEND           = 12
      DP_ERROR_WRITE          = 13
      UNKNOWN_DP_ERROR        = 14
      ACCESS_DENIED           = 15
      DP_OUT_OF_MEMORY        = 16
      DISK_FULL               = 17
      DP_TIMEOUT              = 18
      FILE_NOT_FOUND          = 19
      DATAPROVIDER_EXCEPTION  = 20
      CONTROL_FLUSH_ERROR     = 21
      OTHERS                  = 22.
  IF SY-SUBRC <> 0.
* MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO
*         WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4.
  ENDIF.

ENDFORM.



FORM ENFORM3.
  OPTIONS-TDGETOTF = 'X'.
  CALL FUNCTION 'OPEN_FORM'
    EXPORTING
*     device                      = 'PRINTER'
      DIALOG                      = ''
*     form                        = 'ZSR9_1'
      LANGUAGE                    = SY-LANGU
      OPTIONS                     = OPTIONS
    EXCEPTIONS
      CANCELED                    = 1
      DEVICE                      = 2
      FORM                        = 3
      OPTIONS                     = 4
      UNCLOSED                    = 5
      MAIL_OPTIONS                = 6
      ARCHIVE_ERROR               = 7
      INVALID_FAX_NUMBER          = 8
      MORE_PARAMS_NEEDED_IN_BATCH = 9
      SPOOL_ERROR                 = 10
      CODEPAGE                    = 11
      OTHERS                      = 12.
  IF SY-SUBRC <> 0.
* MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO
*         WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4.
  ENDIF.
  CALL FUNCTION 'START_FORM'
    EXPORTING
      FORM        = 'ZSAMP_RANK'
      LANGUAGE    = SY-LANGU
    EXCEPTIONS
      FORM        = 1
      FORMAT      = 2
      UNENDED     = 3
      UNOPENED    = 4
      UNUSED      = 5
      SPOOL_ERROR = 6
      CODEPAGE    = 7
      OTHERS      = 8.
  IF SY-SUBRC <> 0.
    MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO
            WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4.
  ENDIF.

  LOOP AT ITAB_REPORT4 ASSIGNING <FS_REPORT>.
    WPERNR = <FS_REPORT>-PERNR.
    CALL FUNCTION 'WRITE_FORM'
      EXPORTING
        ELEMENT                  = 'E1'
*       FUNCTION                 = 'SET'
*       TYPE                     = 'BODY'
        WINDOW                   = 'MAIN'
*   IMPORTING
*       PENDING_LINES            =
      EXCEPTIONS
        ELEMENT                  = 1
        FUNCTION                 = 2
        TYPE                     = 3
        UNOPENED                 = 4
        UNSTARTED                = 5
        WINDOW                   = 6
        BAD_PAGEFORMAT_FOR_PRINT = 7
        SPOOL_ERROR              = 8
        CODEPAGE                 = 9
        OTHERS                   = 10.
    IF SY-SUBRC <> 0.
      MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO
           WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4.
    ENDIF.


  ENDLOOP.






  CALL FUNCTION 'END_FORM'
    EXCEPTIONS
      UNOPENED                 = 1
      BAD_PAGEFORMAT_FOR_PRINT = 2
      SPOOL_ERROR              = 3
      CODEPAGE                 = 4
      OTHERS                   = 5.
  IF SY-SUBRC <> 0.
    MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO
            WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4.
  ENDIF.


  CALL FUNCTION 'CLOSE_FORM'
    IMPORTING
      RESULT  = RESULT
    TABLES
      OTFDATA = L_OTF_DATA.


  CALL FUNCTION 'CONVERT_OTF'
    EXPORTING
      FORMAT       = 'PDF'
    IMPORTING
      BIN_FILESIZE = L_BIN_FILESIZE
    TABLES
      OTF          = L_OTF_DATA
      LINES        = L_ASC_DATA.

  CALL FUNCTION 'SX_TABLE_LINE_WIDTH_CHANGE'
    EXPORTING
      LINE_WIDTH_DST = '255'
    TABLES
      CONTENT_IN     = L_ASC_DATA
      CONTENT_OUT    = OBJBIN.




  DESCRIBE TABLE OBJBIN LINES RIGHE_ATTACHMENT.
  OBJTXT = 'This eMail is meant for information only. Please DO NOT REPLY'.APPEND OBJTXT.
  OBJTXT = '                                 '.APPEND OBJTXT.
  OBJTXT = 'BLUE CROSS LABORATORIES LTD.'.APPEND OBJTXT.
  DESCRIBE TABLE OBJTXT LINES RIGHE_TESTO.
  DOC_CHNG-OBJ_NAME = 'URGENT'.
  DOC_CHNG-EXPIRY_DAT = SY-DATUM + 10.
  CONDENSE LTX.
  CONDENSE OBJTXT.

  WRITE S_BEGDA-LOW TO WA_D1 DD/MM/YY.
  WRITE S_BEGDA-HIGH TO WA_D2 DD/MM/YY.

*      CONCATENATE 'SR9 for the period' ltx '-' INTO doc_chng-obj_descr SEPARATED BY space.
  CONCATENATE 'SAMPLE RANKING' P_HEAD2  '(' WA_D1 'TO'  WA_D2 ')'  INTO DOC_CHNG-OBJ_DESCR SEPARATED BY SPACE. "' FROM ' wa_d1 ' TO '  wa_d2
  DOC_CHNG-SENSITIVTY = 'F'.
  DOC_CHNG-DOC_SIZE = RIGHE_TESTO * 255 .

  CLEAR OBJPACK-TRANSF_BIN.

  OBJPACK-HEAD_START = 1.
  OBJPACK-HEAD_NUM = 0.
  OBJPACK-BODY_START = 1.
  OBJPACK-BODY_NUM = 4.
  OBJPACK-DOC_TYPE = 'TXT'.
  APPEND OBJPACK.

  OBJPACK-TRANSF_BIN = 'X'.
  OBJPACK-HEAD_START = 1.
  OBJPACK-HEAD_NUM = 0.
  OBJPACK-BODY_START = 1.
  OBJPACK-BODY_NUM = RIGHE_ATTACHMENT.
  OBJPACK-DOC_TYPE = 'PDF'.
  OBJPACK-OBJ_NAME = 'TEST'.
  CONDENSE LTX.
  CONCATENATE 'SAMPLE-RANKING ' P_HEAD2     INTO OBJPACK-OBJ_DESCR SEPARATED BY SPACE.
*  concatenate 'SR-9 NET' '.' into objpack-obj_descr separated by space.
*  objpack-doc_size = righe_attachment * 255.
  APPEND OBJPACK.
  CLEAR OBJPACK.

  RECLIST-RECEIVER =   P_EMAIL1.
  RECLIST-EXPRESS = 'X'.
  RECLIST-REC_TYPE = 'U'.
  RECLIST-NOTIF_DEL = 'X'. " request delivery notification
  RECLIST-NOTIF_NDEL = 'X'. " request not delivered notification
  APPEND RECLIST.
  CLEAR RECLIST.

  DESCRIBE TABLE RECLIST LINES MCOUNT.
  IF MCOUNT > 0.
    DATA: SENDER LIKE SOEXTRECI1-RECEIVER.
***ADDED BY SATHISH.B
    TYPES: BEGIN OF T_USR21,
             BNAME      TYPE USR21-BNAME,
             PERSNUMBER TYPE USR21-PERSNUMBER,
             ADDRNUMBER TYPE USR21-ADDRNUMBER,
           END OF T_USR21.

    TYPES: BEGIN OF T_ADR6,
             ADDRNUMBER TYPE USR21-ADDRNUMBER,
             PERSNUMBER TYPE USR21-PERSNUMBER,
             SMTP_ADDR  TYPE ADR6-SMTP_ADDR,
           END OF T_ADR6.

    DATA: IT_USR21 TYPE TABLE OF T_USR21,
          WA_USR21 TYPE T_USR21,
          IT_ADR6  TYPE TABLE OF T_ADR6,
          WA_ADR6  TYPE T_ADR6.

    SELECT  BNAME PERSNUMBER ADDRNUMBER FROM USR21 INTO TABLE IT_USR21
        WHERE BNAME = SY-UNAME.
    IF SY-SUBRC = 0.
      SELECT ADDRNUMBER PERSNUMBER SMTP_ADDR FROM ADR6 INTO TABLE IT_ADR6
        FOR ALL ENTRIES IN IT_USR21 WHERE ADDRNUMBER = IT_USR21-ADDRNUMBER
                                    AND   PERSNUMBER = IT_USR21-PERSNUMBER.
    ENDIF.
    LOOP AT IT_USR21 INTO WA_USR21.
      READ TABLE IT_ADR6 INTO WA_ADR6 WITH KEY ADDRNUMBER = WA_USR21-ADDRNUMBER.
      IF SY-SUBRC = 0.
        SENDER = WA_ADR6-SMTP_ADDR.
      ENDIF.
    ENDLOOP.

    CALL FUNCTION 'SO_DOCUMENT_SEND_API1'
      EXPORTING
        DOCUMENT_DATA              = DOC_CHNG
        PUT_IN_OUTBOX              = 'X'
        SENDER_ADDRESS             = SENDER
        SENDER_ADDRESS_TYPE        = 'SMTP'
*       COMMIT_WORK                = ' '
*   IMPORTING
*       SENT_TO_ALL                =
*       NEW_OBJECT_ID              =
*       SENDER_ID                  =
      TABLES
        PACKING_LIST               = OBJPACK
*       OBJECT_HEADER              =
        CONTENTS_BIN               = OBJBIN
        CONTENTS_TXT               = OBJTXT
*       CONTENTS_HEX               =
*       OBJECT_PARA                =
*       OBJECT_PARB                =
        RECEIVERS                  = RECLIST
      EXCEPTIONS
        TOO_MANY_RECEIVERS         = 1
        DOCUMENT_NOT_SENT          = 2
        DOCUMENT_TYPE_NOT_EXIST    = 3
        OPERATION_NO_AUTHORIZATION = 4
        PARAMETER_ERROR            = 5
        X_ERROR                    = 6
        ENQUEUE_ERROR              = 7
        OTHERS                     = 8.
    IF SY-SUBRC <> 0.
      MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO
              WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4.
    ENDIF.

    COMMIT WORK.
    IF SY-SUBRC EQ 0.
      WRITE : / 'EMAIL SENT ON ',P_EMAIL1.
    ENDIF.

    CLEAR   : OBJPACK,
              OBJHEAD,
              OBJTXT,
              OBJBIN,
              RECLIST.

    REFRESH : OBJPACK,
              OBJHEAD,
              OBJTXT,
              OBJBIN,
              RECLIST.

  ENDIF.




ENDFORM.
