*&---------------------------------------------------------------------*
*& Report  ZSR8_REPORT1
*& Developed by Jyotsna on 5.6.24
*&---------------------------------------------------------------------*
*&
*&
*&---------------------------------------------------------------------*
REPORT ZSR8_REPORT2 NO STANDARD PAGE HEADING LINE-SIZE 600.
TABLES : ZSALES_TAB1,
         MAKT,
         MKPF,
         TVM4T,
         MARA,
         ZPRDGROUP,
         TVM5T,
         T247 .

DATA : V_FM TYPE RS38L_FNAM.


DATA:IT_ZSALES_TAB1 TYPE TABLE OF ZSALES_TAB1,
     WA_ZSALES_TAB1 TYPE ZSALES_TAB1,
     IT_MAKT        TYPE TABLE OF MAKT,
     WA_MAKT        TYPE MAKT,
     IT_MVKE        TYPE TABLE OF MVKE,
     WA_MVKE        TYPE MVKE.

TYPES: BEGIN OF ITAB1,

         MATNR   TYPE ZSALES_TAB1-MATNR,
         C_QTY1  TYPE P,
         C_QTY2  TYPE P,
         C_QTY3  TYPE P,
         C_QTY4  TYPE P,
         C_QTY5  TYPE P,
         C_QTY6  TYPE P,
         C_QTY7  TYPE P,
         C_QTY8  TYPE P,
         C_QTY9  TYPE P,
         C_QTY10 TYPE P,
         C_QTY11 TYPE P,
         C_QTY12 TYPE P,
         NET1    TYPE P DECIMALS 2,
         NET2    TYPE P DECIMALS 2,
         NET3    TYPE P DECIMALS 2,
         NET4    TYPE P DECIMALS 2,
         NET5    TYPE P DECIMALS 2,
         NET6    TYPE P DECIMALS 2,
         NET7    TYPE P DECIMALS 2,
         NET8    TYPE P DECIMALS 2,
         NET9    TYPE P DECIMALS 2,
         NET10   TYPE P DECIMALS 2,
         NET11   TYPE P DECIMALS 2,
         NET12   TYPE P DECIMALS 2,

*         ZMONTH1(2) TYPE C,
*         ZYEAR1     TYPE MKPF-MJAHR,
*         ZMONTH2(2) TYPE C,
*         ZYEAR2     TYPE MKPF-MJAHR,
*         ZMONTH3(2) TYPE C,
*         ZYEAR3     TYPE MKPF-MJAHR,
*         ZMONTH4(2) TYPE C,
*         ZYEAR4     TYPE MKPF-MJAHR,
*         ZMONTH5(2) TYPE C,
*         ZYEAR5     TYPE MKPF-MJAHR,
*         ZMONTH6(2) TYPE C,
*         ZYEAR6     TYPE MKPF-MJAHR,

*         NET1       TYPE ZSALES_TAB1-NET,
*         C_QTY1     TYPE ZSALES_TAB1-C_QTY,
*         F_QTY1     TYPE ZSALES_TAB1-F_QTY,
*         NEP_PTS1   TYPE ZSALES_TAB1-NEP_PTS,
*         NEP_C_QTY1 TYPE ZSALES_TAB1-NEP_C_QTY,
*         NEP_F_QTY1 TYPE ZSALES_TAB1-NEP_F_QTY,
*
*         NET2       TYPE ZSALES_TAB1-NET,
*         C_QTY2     TYPE ZSALES_TAB1-C_QTY,
*         F_QTY2     TYPE ZSALES_TAB1-F_QTY,
*         NEP_PTS2   TYPE ZSALES_TAB1-NEP_PTS,
*         NEP_C_QTY2 TYPE ZSALES_TAB1-NEP_C_QTY,
*         NEP_F_QTY2 TYPE ZSALES_TAB1-NEP_F_QTY,
*
*
*         NET3       TYPE ZSALES_TAB1-NET,
*         C_QTY3     TYPE ZSALES_TAB1-C_QTY,
*         F_QTY3     TYPE ZSALES_TAB1-F_QTY,
*         NEP_PTS3   TYPE ZSALES_TAB1-NEP_PTS,
*         NEP_C_QTY3 TYPE ZSALES_TAB1-NEP_C_QTY,
*         NEP_F_QTY3 TYPE ZSALES_TAB1-NEP_F_QTY,
*
*
*         NET4       TYPE ZSALES_TAB1-NET,
*         C_QTY4     TYPE ZSALES_TAB1-C_QTY,
*         F_QTY4     TYPE ZSALES_TAB1-F_QTY,
*         NEP_PTS4   TYPE ZSALES_TAB1-NEP_PTS,
*         NEP_C_QTY4 TYPE ZSALES_TAB1-NEP_C_QTY,
*         NEP_F_QTY4 TYPE ZSALES_TAB1-NEP_F_QTY,
*
*         NET5       TYPE ZSALES_TAB1-NET,
*         C_QTY5     TYPE ZSALES_TAB1-C_QTY,
*         F_QTY5     TYPE ZSALES_TAB1-F_QTY,
*         NEP_PTS5   TYPE ZSALES_TAB1-NEP_PTS,
*         NEP_C_QTY5 TYPE ZSALES_TAB1-NEP_C_QTY,
*         NEP_F_QTY5 TYPE ZSALES_TAB1-NEP_F_QTY,
*
*         NET6       TYPE ZSALES_TAB1-NET,
*         C_QTY6     TYPE ZSALES_TAB1-C_QTY,
*         F_QTY6     TYPE ZSALES_TAB1-F_QTY,
*         NEP_PTS6   TYPE ZSALES_TAB1-NEP_PTS,
*         NEP_C_QTY6 TYPE ZSALES_TAB1-NEP_C_QTY,
*         NEP_F_QTY6 TYPE ZSALES_TAB1-NEP_F_QTY,


       END OF ITAB1.

TYPES: BEGIN OF ITAB2,
         SPART    TYPE MARA-SPART,
         PRN_SEQ  TYPE  ZPRDGROUP-PRN_SEQ,
         GRP_NAME TYPE ZPRDGROUP-GRP_NAME,
         PRD_NAME TYPE ZPRDGROUP-PRD_NAME,
         BEZEI    TYPE TVM4T-BEZEI,
         PACK     TYPE TVM5T-BEZEI,
         C_QTY1   TYPE P,
         C_QTY2   TYPE P,
         C_QTY3   TYPE P,
         C_QTY4   TYPE P,
         C_QTY5   TYPE P,
         C_QTY6   TYPE P,
         C_QTY7   TYPE P,
         C_QTY8   TYPE P,
         C_QTY9   TYPE P,
         C_QTY10  TYPE P,
         C_QTY11  TYPE P,
         C_QTY12  TYPE P,

         NET1     TYPE P DECIMALS 2,
         NET2     TYPE P DECIMALS 2,
         NET3     TYPE P DECIMALS 2,
         NET4     TYPE P DECIMALS 2,
         NET5     TYPE P DECIMALS 2,
         NET6     TYPE P DECIMALS 2,
         NET7     TYPE P DECIMALS 2,
         NET8     TYPE P DECIMALS 2,
         NET9     TYPE P DECIMALS 2,
         NET10    TYPE P DECIMALS 2,
         NET11    TYPE P DECIMALS 2,
         NET12    TYPE P DECIMALS 2,

*         ZMONTH(2) TYPE C,
*         ZYEAR     TYPE MKPF-MJAHR,
*         MATNR     TYPE ZSALES_TAB1-MATNR,
*         MAKTX     TYPE MAKT-MAKTX,
*         NET1       TYPE ZSALES_TAB1-NET,
*         C_QTY1     TYPE ZSALES_TAB1-C_QTY,
*         F_QTY1     TYPE ZSALES_TAB1-F_QTY,
*         NEP_PTS1   TYPE ZSALES_TAB1-NEP_PTS,
*         NEP_C_QTY1 TYPE ZSALES_TAB1-NEP_C_QTY,
*         NEP_F_QTY1 TYPE ZSALES_TAB1-NEP_F_QTY,
*
*         NET2       TYPE ZSALES_TAB1-NET,
*         C_QTY2     TYPE ZSALES_TAB1-C_QTY,
*         F_QTY2     TYPE ZSALES_TAB1-F_QTY,
*         NEP_PTS2   TYPE ZSALES_TAB1-NEP_PTS,
*         NEP_C_QTY2 TYPE ZSALES_TAB1-NEP_C_QTY,
*         NEP_F_QTY2 TYPE ZSALES_TAB1-NEP_F_QTY,
*
*
*         NET3       TYPE ZSALES_TAB1-NET,
*         C_QTY3     TYPE ZSALES_TAB1-C_QTY,
*         F_QTY3     TYPE ZSALES_TAB1-F_QTY,
*         NEP_PTS3   TYPE ZSALES_TAB1-NEP_PTS,
*         NEP_C_QTY3 TYPE ZSALES_TAB1-NEP_C_QTY,
*         NEP_F_QTY3 TYPE ZSALES_TAB1-NEP_F_QTY,
*
*
*         NET4       TYPE ZSALES_TAB1-NET,
*         C_QTY4     TYPE ZSALES_TAB1-C_QTY,
*         F_QTY4     TYPE ZSALES_TAB1-F_QTY,
*         NEP_PTS4   TYPE ZSALES_TAB1-NEP_PTS,
*         NEP_C_QTY4 TYPE ZSALES_TAB1-NEP_C_QTY,
*         NEP_F_QTY4 TYPE ZSALES_TAB1-NEP_F_QTY,
*
*         NET5       TYPE ZSALES_TAB1-NET,
*         C_QTY5     TYPE ZSALES_TAB1-C_QTY,
*         F_QTY5     TYPE ZSALES_TAB1-F_QTY,
*         NEP_PTS5   TYPE ZSALES_TAB1-NEP_PTS,
*         NEP_C_QTY5 TYPE ZSALES_TAB1-NEP_C_QTY,
*         NEP_F_QTY5 TYPE ZSALES_TAB1-NEP_F_QTY,
*
*         NET6       TYPE ZSALES_TAB1-NET,
*         C_QTY6     TYPE ZSALES_TAB1-C_QTY,
*         F_QTY6     TYPE ZSALES_TAB1-F_QTY,
*         NEP_PTS6   TYPE ZSALES_TAB1-NEP_PTS,
*         NEP_C_QTY6 TYPE ZSALES_TAB1-NEP_C_QTY,
*         NEP_F_QTY6 TYPE ZSALES_TAB1-NEP_F_QTY,
*
*         C_QTY7     TYPE ZSALES_TAB1-C_QTY,
*         C_QTY8     TYPE ZSALES_TAB1-C_QTY,
*         C_QTY9     TYPE ZSALES_TAB1-C_QTY,
*         C_QTY10    TYPE ZSALES_TAB1-C_QTY,
*         C_QTY11    TYPE ZSALES_TAB1-C_QTY,
*         C_QTY12    TYPE ZSALES_TAB1-C_QTY,
       END OF ITAB2.

*TYPES: BEGIN OF ITAB3,
*         SPART   TYPE MARA-SPART,
*         PRN_SEQ TYPE  ZPRDGROUP-PRN_SEQ,
*         BEZEI   TYPE TVM4T-BEZEI,
*         PACK    TYPE TVM5T-BEZEI,
*         C_QTY1  TYPE P,
*         C_QTY2  TYPE P,
*         C_QTY3  TYPE P,
*         C_QTY4  TYPE P,
*         C_QTY5  TYPE P,
*         C_QTY6  TYPE P,
*         C_QTY7  TYPE P,
*         C_QTY8  TYPE P,
*         C_QTY9  TYPE P,
*         C_QTY10 TYPE P,
*         C_QTY11 TYPE P,
*         C_QTY12 TYPE P,
*       END OF ITAB3.

TYPES: BEGIN OF MAT1,
         MATNR TYPE MARA-MATNR,
       END OF MAT1.
DATA: IT_TAB1 TYPE TABLE OF ITAB1,
      WA_TAB1 TYPE ITAB1,
      IT_TAB2 TYPE TABLE OF ITAB2,
      WA_TAB2 TYPE ITAB2,
      IT_TAB3 TYPE TABLE OF ZSR8,
      WA_TAB3 TYPE ZSR8,
      IT_MAT1 TYPE TABLE OF MAT1,
      WA_MAT1 TYPE MAT1.
DATA: MVGR4 TYPE TVM4T-MVGR4,
      MVGR5 TYPE TVM5T-MVGR5.
DATA: DATE1  TYPE SY-DATUM,
      DATE2  TYPE SY-DATUM,
      DATE3  TYPE SY-DATUM,
      DATE4  TYPE SY-DATUM,
      DATE5  TYPE SY-DATUM,
      DATE6  TYPE SY-DATUM,
      DATE7  TYPE SY-DATUM,
      DATE8  TYPE SY-DATUM,
      DATE9  TYPE SY-DATUM,
      DATE10 TYPE SY-DATUM,
      DATE11 TYPE SY-DATUM,
      DATE12 TYPE SY-DATUM.
DATA: LDATE TYPE SY-DATUM.

DATA: TQTY1  TYPE P,
      TQTY2  TYPE P,
      TQTY3  TYPE P,
      TQTY4  TYPE P,
      TQTY5  TYPE P,
      TQTY6  TYPE P,
      TQTY7  TYPE P,
      TQTY8  TYPE P,
      TQTY9  TYPE P,
      TQTY10 TYPE P,
      TQTY11 TYPE P,
      TQTY12 TYPE P.
DATA: VQTY1 TYPE P,
      VNET1 TYPE P DECIMALS 2,
      VQTY2 TYPE P,
      VNET2 TYPE P DECIMALS 2,
      VQTY3 TYPE P,
      VNET3 TYPE P DECIMALS 2.

DATA: TNET1  TYPE P DECIMALS 2,
      TNET2  TYPE P DECIMALS 2,
      TNET3  TYPE P DECIMALS 2,
      TNET4  TYPE P DECIMALS 2,
      TNET5  TYPE P DECIMALS 2,
      TNET6  TYPE P DECIMALS 2,
      TNET7  TYPE P DECIMALS 2,
      TNET8  TYPE P DECIMALS 2,
      TNET9  TYPE P DECIMALS 2,
      TNET10 TYPE P DECIMALS 2,
      TNET11 TYPE P DECIMALS 2,
      TNET12 TYPE P DECIMALS 2.

DATA: TOQTY1  TYPE P,
      TOQTY2  TYPE P,
      TOQTY3  TYPE P,
      TOQTY4  TYPE P,
      TOQTY5  TYPE P,
      TOQTY6  TYPE P,
      TOQTY7  TYPE P,
      TOQTY8  TYPE P,
      TOQTY9  TYPE P,
      TOQTY10 TYPE P,
      TOQTY11 TYPE P,
      TOQTY12 TYPE P.

DATA: TONET1  TYPE P DECIMALS 2,
      TONET2  TYPE P DECIMALS 2,
      TONET3  TYPE P DECIMALS 2,
      TONET4  TYPE P DECIMALS 2,
      TONET5  TYPE P DECIMALS 2,
      TONET6  TYPE P DECIMALS 2,
      TONET7  TYPE P DECIMALS 2,
      TONET8  TYPE P DECIMALS 2,
      TONET9  TYPE P DECIMALS 2,
      TONET10 TYPE P DECIMALS 2,
      TONET11 TYPE P DECIMALS 2,
      TONET12 TYPE P DECIMALS 2.

DATA: FROM_DT TYPE SY-DATUM,
      TO_DT   TYPE SY-DATUM.
DATA: MON12(10) TYPE C,
      MON11(10) TYPE C,
      MON10(10) TYPE C,
      MON9(10)  TYPE C,
      MON8(10)  TYPE C,
      MON7(10)  TYPE C,
      MON6(10)  TYPE C,
      MON5(10)  TYPE C,
      MON4(10)  TYPE C,
      MON3(10)  TYPE C,
      MON2(10)  TYPE C,
      MON1(10)  TYPE C.

DATA : W_RETURN    TYPE SSFCRESCL.
DATA: I_OTF       TYPE ITCOO    OCCURS 0 WITH HEADER LINE,
      I_TLINE     LIKE TLINE    OCCURS 0 WITH HEADER LINE,
      I_RECORD    LIKE SOLISTI1 OCCURS 0 WITH HEADER LINE,
      I_XSTRING   TYPE XSTRING,
* Objects to send mail.
      I_OBJPACK   LIKE SOPCKLSTI1 OCCURS 0 WITH HEADER LINE,
      I_OBJTXT    LIKE SOLISTI1   OCCURS 0 WITH HEADER LINE,
      I_OBJBIN    LIKE SOLIX      OCCURS 0 WITH HEADER LINE,
      I_RECLIST   LIKE SOMLRECI1  OCCURS 0 WITH HEADER LINE,
* Work Area declarations
      WA_OBJHEAD  TYPE SOLI_TAB,
      W_CTRLOP    TYPE SSFCTRLOP,
      W_COMPOP    TYPE SSFCOMPOP,
*      w_return    TYPE ssfcrescl,
      WA_BUFFER   TYPE STRING,
* Variables declarations
      V_FORM_NAME TYPE RS38L_FNAM,
      V_LEN_IN    LIKE SOOD-OBJLEN.
DATA: IN_MAILID TYPE AD_SMTPADR.
DATA: TYP1(2) TYPE C.

SELECTION-SCREEN BEGIN OF BLOCK MERKMALE1 WITH FRAME TITLE TEXT-001.
SELECT-OPTIONS :  SDATE1 FOR SY-DATUM.
PARAMETERS : R2 RADIOBUTTON GROUP R1,
             R1 RADIOBUTTON GROUP R1.
SELECTION-SCREEN END OF BLOCK MERKMALE1 .

SELECTION-SCREEN BEGIN OF BLOCK MERKMALE2 WITH FRAME TITLE TEXT-001.

PARAMETERS : L1 RADIOBUTTON GROUP R2,
             L2 RADIOBUTTON GROUP R2.
PARAMETERS EMAIL(70) TYPE C.
SELECTION-SCREEN END OF BLOCK MERKMALE2 .

START-OF-SELECTION.

  IF L2 EQ 'X'.
    IF EMAIL IS INITIAL.
      MESSAGE 'ENTER EMAIL ID' TYPE 'E'.
    ENDIF.
     IF sy-host EQ 'SAPQLT' OR sy-host EQ 'SAPDEV'.
       exit.
     endif.
  ENDIF.

  IF SDATE1-LOW+6(2) NE '01'.
    MESSAGE 'ENTER START DATE OF THE MONTH' TYPE 'E'.
  ENDIF.

  DATE1 = SDATE1-LOW.
  CALL FUNCTION 'RE_ADD_MONTH_TO_DATE'
    EXPORTING
      MONTHS  = '1'
      OLDDATE = DATE1
    IMPORTING
      NEWDATE = DATE2.
  CALL FUNCTION 'RE_ADD_MONTH_TO_DATE'
    EXPORTING
      MONTHS  = '1'
      OLDDATE = DATE2
    IMPORTING
      NEWDATE = DATE3.
  CALL FUNCTION 'RE_ADD_MONTH_TO_DATE'
    EXPORTING
      MONTHS  = '1'
      OLDDATE = DATE3
    IMPORTING
      NEWDATE = DATE4.
  CALL FUNCTION 'RE_ADD_MONTH_TO_DATE'
    EXPORTING
      MONTHS  = '1'
      OLDDATE = DATE4
    IMPORTING
      NEWDATE = DATE5.
  CALL FUNCTION 'RE_ADD_MONTH_TO_DATE'
    EXPORTING
      MONTHS  = '1'
      OLDDATE = DATE5
    IMPORTING
      NEWDATE = DATE6.

  CALL FUNCTION 'RE_ADD_MONTH_TO_DATE'
    EXPORTING
      MONTHS  = '1'
      OLDDATE = DATE6
    IMPORTING
      NEWDATE = DATE7.

  CALL FUNCTION 'RE_ADD_MONTH_TO_DATE'
    EXPORTING
      MONTHS  = '1'
      OLDDATE = DATE7
    IMPORTING
      NEWDATE = DATE8.

  CALL FUNCTION 'RE_ADD_MONTH_TO_DATE'
    EXPORTING
      MONTHS  = '1'
      OLDDATE = DATE8
    IMPORTING
      NEWDATE = DATE9.

  CALL FUNCTION 'RE_ADD_MONTH_TO_DATE'
    EXPORTING
      MONTHS  = '1'
      OLDDATE = DATE9
    IMPORTING
      NEWDATE = DATE10.

  CALL FUNCTION 'RE_ADD_MONTH_TO_DATE'
    EXPORTING
      MONTHS  = '1'
      OLDDATE = DATE10
    IMPORTING
      NEWDATE = DATE11.

  CALL FUNCTION 'RE_ADD_MONTH_TO_DATE'
    EXPORTING
      MONTHS  = '1'
      OLDDATE = DATE11
    IMPORTING
      NEWDATE = DATE12.

*  WRITE : / 'month',DATE1,DATE2,DATE3,DATE4,DATE5,DATE6,DATE7,DATE8,DATE9,DATE10,DATE11,DATE12.

  CALL FUNCTION 'HR_JP_MONTH_BEGIN_END_DATE'
    EXPORTING
      IV_DATE           = DATE12
    IMPORTING
*     EV_MONTH_BEGIN_DATE       =
      EV_MONTH_END_DATE = LDATE.

  IF LDATE NE SDATE1-HIGH.
    MESSAGE 'ENTER 12th MONTH END DATE ' TYPE 'E'.
  ENDIF.


  PERFORM SALESDATA.


  SORT IT_MAT1 BY MATNR.
  DELETE ADJACENT DUPLICATES FROM IT_MAT1 COMPARING MATNR.
  IF IT_MAT1 IS NOT INITIAL.
    SELECT * FROM MAKT INTO TABLE IT_MAKT FOR ALL ENTRIES IN IT_MAT1 WHERE MATNR EQ IT_MAT1-MATNR.
    SELECT * FROM MVKE INTO TABLE IT_MVKE FOR ALL ENTRIES IN IT_MAT1 WHERE MATNR EQ IT_MAT1-MATNR AND MVGR4 NE SPACE AND MVGR5 NE SPACE.
  ENDIF.


  LOOP AT IT_TAB1 INTO WA_TAB1.
*  WA_TAB2-MATNR = WA_TAB1-MATNR.
    CLEAR : MVGR4,MVGR5.
    READ TABLE IT_MVKE INTO WA_MVKE WITH KEY MATNR = WA_TAB1-MATNR VKORG = '1000' VTWEG = '10'.
    IF SY-SUBRC EQ 0.
      MVGR4 = WA_MVKE-MVGR4.
      MVGR5 = WA_MVKE-MVGR5.
    ENDIF.
    IF MVGR4 EQ SPACE.
      READ TABLE IT_MVKE INTO WA_MVKE WITH KEY MATNR = WA_TAB1-MATNR .
      IF SY-SUBRC EQ 0.
        MVGR4 = WA_MVKE-MVGR4.
      ENDIF.
    ENDIF.
    IF MVGR5 EQ SPACE.
      READ TABLE IT_MVKE INTO WA_MVKE WITH KEY MATNR = WA_TAB1-MATNR .
      IF SY-SUBRC EQ 0.
        MVGR5 = WA_MVKE-MVGR4.
      ENDIF.
    ENDIF.
    SELECT SINGLE * FROM TVM4T WHERE SPRAS EQ 'EN' AND MVGR4 EQ MVGR4.
    IF SY-SUBRC EQ 0.
      WA_TAB2-BEZEI = TVM4T-BEZEI.
    ENDIF.
    SELECT SINGLE * FROM TVM5T WHERE SPRAS EQ 'EN' AND MVGR5 EQ MVGR5.
    IF SY-SUBRC EQ 0.
      WA_TAB2-PACK = TVM5T-BEZEI.
    ENDIF.
    SELECT SINGLE * FROM MARA WHERE MATNR EQ WA_TAB1-MATNR.
    IF SY-SUBRC EQ 0.
      WA_TAB2-SPART = MARA-SPART.
    ENDIF.
    SELECT SINGLE * FROM ZPRDGROUP WHERE PRD_CODE  EQ WA_TAB1-MATNR AND REP_TYPE = 'SR2'.
    IF SY-SUBRC EQ 0.
      WA_TAB2-PRN_SEQ = ZPRDGROUP-PRN_SEQ.
      WA_TAB2-GRP_NAME = ZPRDGROUP-GRP_NAME.
      WA_TAB2-PRD_NAME = ZPRDGROUP-PRD_NAME.
    ENDIF.

    WA_TAB2-C_QTY1 = WA_TAB1-C_QTY1.
    WA_TAB2-C_QTY2 = WA_TAB1-C_QTY2.
    WA_TAB2-C_QTY3 = WA_TAB1-C_QTY3.
    WA_TAB2-C_QTY4 = WA_TAB1-C_QTY4.
    WA_TAB2-C_QTY5 = WA_TAB1-C_QTY5.
    WA_TAB2-C_QTY6 = WA_TAB1-C_QTY6.
    WA_TAB2-C_QTY7 = WA_TAB1-C_QTY7.
    WA_TAB2-C_QTY8 = WA_TAB1-C_QTY8.
    WA_TAB2-C_QTY9 = WA_TAB1-C_QTY9.
    WA_TAB2-C_QTY10 = WA_TAB1-C_QTY10.
    WA_TAB2-C_QTY11 = WA_TAB1-C_QTY11.
    WA_TAB2-C_QTY12 = WA_TAB1-C_QTY12.


    WA_TAB2-NET1 = WA_TAB1-NET1 / 100000.
    WA_TAB2-NET2 = WA_TAB1-NET2 / 100000.
    WA_TAB2-NET3 = WA_TAB1-NET3 / 100000.
    WA_TAB2-NET4 = WA_TAB1-NET4 / 100000.
    WA_TAB2-NET5 = WA_TAB1-NET5 / 100000.
    WA_TAB2-NET6 = WA_TAB1-NET6 / 100000.
    WA_TAB2-NET7 = WA_TAB1-NET7 / 100000.
    WA_TAB2-NET8 = WA_TAB1-NET8 / 100000.
    WA_TAB2-NET9 = WA_TAB1-NET9 / 100000.
    WA_TAB2-NET10 = WA_TAB1-NET10 / 100000.
    WA_TAB2-NET11 = WA_TAB1-NET11 / 100000.
    WA_TAB2-NET12 = WA_TAB1-NET12 / 100000.

    COLLECT WA_TAB2 INTO IT_TAB2.
    CLEAR WA_TAB2.
  ENDLOOP.

*  SORT it_tab2 BY spart prn_seq bezei.
*  *  SORT IT_TAB2 BY SPART PRN_SEQ BEZEI.  "deactivated on 29.7.24
  SORT IT_TAB2 BY SPART GRP_NAME PRD_NAME. "activated on 29.7.24

*  LOOP AT IT_TAB2 INTO WA_TAB2.
*
*    WRITE: / '12', WA_TAB2-SPART,WA_TAB2-PRN_SEQ,WA_TAB2-BEZEI,WA_TAB2-PACK,WA_TAB2-C_QTY12,WA_TAB2-C_QTY11,WA_TAB2-C_QTY10,WA_TAB2-C_QTY9,
*    WA_TAB2-C_QTY8,WA_TAB2-C_QTY7,WA_TAB2-C_QTY6,WA_TAB2-C_QTY5,WA_TAB2-C_QTY4,WA_TAB2-C_QTY3,WA_TAB2-C_QTY2,WA_TAB2-C_QTY1.
*  ENDLOOP.
  LOOP AT IT_TAB2 INTO WA_TAB2.
    AT NEW SPART.
      IF WA_TAB2-SPART EQ '50'.
        WA_TAB3-BEZEI = 'BC DIVISION'.
      ELSEIF WA_TAB2-SPART EQ '60'.
        WA_TAB3-BEZEI = 'XL DIVISION'.
      ELSEIF WA_TAB2-SPART EQ '70'.
        WA_TAB3-BEZEI = 'LS DIVISION'.
      ENDIF.
      WA_TAB3-TYP = 'DNEW'.
      APPEND WA_TAB3 TO IT_TAB3.
    ENDAT.

    WA_TAB3-SPART = WA_TAB2-SPART.
    WA_TAB3-PRN_SEQ = WA_TAB2-PRN_SEQ.
    WA_TAB3-BEZEI = WA_TAB2-BEZEI.
    WA_TAB3-PACK = WA_TAB2-PACK.
    WA_TAB3-CQTY12 = WA_TAB2-C_QTY12.
    WA_TAB3-CQTY11 = WA_TAB2-C_QTY11.
    WA_TAB3-CQTY10 = WA_TAB2-C_QTY10.
    WA_TAB3-CQTY9 = WA_TAB2-C_QTY9.
    WA_TAB3-CQTY8 = WA_TAB2-C_QTY8.
    WA_TAB3-CQTY7 = WA_TAB2-C_QTY7.
    WA_TAB3-CQTY6 = WA_TAB2-C_QTY6.
    WA_TAB3-CQTY5 = WA_TAB2-C_QTY5.
    WA_TAB3-CQTY4 = WA_TAB2-C_QTY4.
    WA_TAB3-CQTY3 = WA_TAB2-C_QTY3.
    WA_TAB3-CQTY2 = WA_TAB2-C_QTY2.
    WA_TAB3-CQTY1 = WA_TAB2-C_QTY1.
    CLEAR : VQTY1.
    VQTY1 = WA_TAB2-C_QTY1 + WA_TAB2-C_QTY2 + WA_TAB2-C_QTY3 + WA_TAB2-C_QTY4 + WA_TAB2-C_QTY5 + WA_TAB2-C_QTY6 + WA_TAB2-C_QTY7
    + WA_TAB2-C_QTY8 + WA_TAB2-C_QTY9 + WA_TAB2-C_QTY10 + WA_TAB2-C_QTY11 + WA_TAB2-C_QTY12.
    WA_TAB3-TQTY = VQTY1.

    WA_TAB3-NET12 = WA_TAB2-NET12 .
    WA_TAB3-NET11 = WA_TAB2-NET11 .
    WA_TAB3-NET10 = WA_TAB2-NET10 .
    WA_TAB3-NET9 = WA_TAB2-NET9 .
    WA_TAB3-NET8 = WA_TAB2-NET8 .
    WA_TAB3-NET7 = WA_TAB2-NET7 .
    WA_TAB3-NET6 = WA_TAB2-NET6 .
    WA_TAB3-NET5 = WA_TAB2-NET5 .
    WA_TAB3-NET4 = WA_TAB2-NET4 .
    WA_TAB3-NET3 = WA_TAB2-NET3 .
    WA_TAB3-NET2 = WA_TAB2-NET2 .
    WA_TAB3-NET1 = WA_TAB2-NET1 .
    CLEAR : VNET1.
    VNET1 = WA_TAB2-NET1 + WA_TAB2-NET2 + WA_TAB2-NET3 + WA_TAB2-NET4 + WA_TAB2-NET5 + WA_TAB2-NET6 + WA_TAB2-NET7 + WA_TAB2-NET8
    + WA_TAB2-NET9 + WA_TAB2-NET10 + WA_TAB2-NET11 + WA_TAB2-NET12.
    WA_TAB3-TNET = VNET1.


    TQTY12 = TQTY12 + WA_TAB2-C_QTY12.
    TQTY11 = TQTY11 + WA_TAB2-C_QTY11.
    TQTY10 = TQTY10 + WA_TAB2-C_QTY10.
    TQTY9 = TQTY9 + WA_TAB2-C_QTY9.
    TQTY8 = TQTY8 + WA_TAB2-C_QTY8.
    TQTY7 = TQTY7 + WA_TAB2-C_QTY7.
    TQTY6 = TQTY6 + WA_TAB2-C_QTY6.
    TQTY5 = TQTY5 + WA_TAB2-C_QTY5.
    TQTY4 = TQTY4 + WA_TAB2-C_QTY4.
    TQTY3 = TQTY3 + WA_TAB2-C_QTY3.
    TQTY2 = TQTY2 + WA_TAB2-C_QTY2.
    TQTY1 = TQTY1 + WA_TAB2-C_QTY1.

    TOQTY12 = TOQTY12 + WA_TAB2-C_QTY12.
    TOQTY11 = TOQTY11 + WA_TAB2-C_QTY11.
    TOQTY10 = TOQTY10 + WA_TAB2-C_QTY10.
    TOQTY9 = TOQTY9 + WA_TAB2-C_QTY9.
    TOQTY8 = TOQTY8 + WA_TAB2-C_QTY8.
    TOQTY7 = TOQTY7 + WA_TAB2-C_QTY7.
    TOQTY6 = TOQTY6 + WA_TAB2-C_QTY6.
    TOQTY5 = TOQTY5 + WA_TAB2-C_QTY5.
    TOQTY4 = TOQTY4 + WA_TAB2-C_QTY4.
    TOQTY3 = TOQTY3 + WA_TAB2-C_QTY3.
    TOQTY2 = TOQTY2 + WA_TAB2-C_QTY2.
    TOQTY1 = TOQTY1 + WA_TAB2-C_QTY1.

***************************
    TNET12 = TNET12 + WA_TAB2-NET12.
    TNET11 = TNET11 + WA_TAB2-NET11.
    TNET10 = TNET10 + WA_TAB2-NET10.
    TNET9 = TNET9 + WA_TAB2-NET9.
    TNET8 = TNET8 + WA_TAB2-NET8.
    TNET7 = TNET7 + WA_TAB2-NET7.
    TNET6 = TNET6 + WA_TAB2-NET6.
    TNET5 = TNET5 + WA_TAB2-NET5.
    TNET4 = TNET4 + WA_TAB2-NET4.
    TNET3 = TNET3 + WA_TAB2-NET3.
    TNET2 = TNET2 + WA_TAB2-NET2.
    TNET1 = TNET1 + WA_TAB2-NET1.

    TONET12 = TONET12 + WA_TAB2-NET12.
    TONET11 = TONET11 + WA_TAB2-NET11.
    TONET10 = TONET10 + WA_TAB2-NET10.
    TONET9 = TONET9 + WA_TAB2-NET9.
    TONET8 = TONET8 + WA_TAB2-NET8.
    TONET7 = TONET7 + WA_TAB2-NET7.
    TONET6 = TONET6 + WA_TAB2-NET6.
    TONET5 = TONET5 + WA_TAB2-NET5.
    TONET4 = TONET4 + WA_TAB2-NET4.
    TONET3 = TONET3 + WA_TAB2-NET3.
    TONET2 = TONET2 + WA_TAB2-NET2.
    TONET1 = TONET1 + WA_TAB2-NET1.
*****************************

    CONDENSE: WA_TAB3-CQTY12,WA_TAB3-CQTY11,WA_TAB3-CQTY10,WA_TAB3-CQTY9,WA_TAB3-CQTY8,WA_TAB3-CQTY7,WA_TAB3-CQTY6,WA_TAB3-CQTY5,WA_TAB3-CQTY4,
    WA_TAB3-CQTY3,WA_TAB3-CQTY2,WA_TAB3-CQTY1,WA_TAB3-TQTY.
    CONDENSE : WA_TAB3-NET12,WA_TAB3-NET11,WA_TAB3-NET10,WA_TAB3-NET9,WA_TAB3-NET8,WA_TAB3-NET7,WA_TAB3-NET6,WA_TAB3-NET5,WA_TAB3-NET4,
    WA_TAB3-NET3,WA_TAB3-NET2,WA_TAB3-NET1,WA_TAB3-TNET.

    WA_TAB3-TYP = SPACE.
    COLLECT WA_TAB3 INTO IT_TAB3.

    AT END OF SPART.
      IF WA_TAB2-SPART EQ 50.
        WA_TAB3-BEZEI = 'BC DIV TOTAL'.
      ELSEIF WA_TAB2-SPART EQ 60.
        WA_TAB3-BEZEI = 'XL DIV TOTAL'.
      ELSEIF WA_TAB2-SPART EQ 70.
        WA_TAB3-BEZEI = 'LS DIV TOTAL'.
      ENDIF.
      WA_TAB3-SPART = SPACE.
      WA_TAB3-PRN_SEQ = SPACE.
      WA_TAB3-PACK = SPACE.
      WA_TAB3-CQTY12 = TQTY12.
      WA_TAB3-CQTY11 = TQTY11.
      WA_TAB3-CQTY10 = TQTY10.
      WA_TAB3-CQTY9 = TQTY9.
      WA_TAB3-CQTY8 = TQTY8.
      WA_TAB3-CQTY7 = TQTY7.
      WA_TAB3-CQTY6 = TQTY6.
      WA_TAB3-CQTY5 = TQTY5.
      WA_TAB3-CQTY4 = TQTY4.
      WA_TAB3-CQTY3 = TQTY3.
      WA_TAB3-CQTY2 = TQTY2.
      WA_TAB3-CQTY1 = TQTY1.
      CLEAR : VQTY2.
      VQTY2 = TQTY1 + TQTY2 + TQTY3 + TQTY4 + TQTY5 + TQTY6 + TQTY7 + TQTY8 + TQTY9 + TQTY10 + TQTY11 + TQTY12.
      WA_TAB3-TQTY = VQTY2.

*********************
      WA_TAB3-NET12 = TNET12.
      WA_TAB3-NET11 = TNET11.
      WA_TAB3-NET10 = TNET10.
      WA_TAB3-NET9 = TNET9.
      WA_TAB3-NET8 = TNET8.
      WA_TAB3-NET7 = TNET7.
      WA_TAB3-NET6 = TNET6.
      WA_TAB3-NET5 = TNET5.
      WA_TAB3-NET4 = TNET4.
      WA_TAB3-NET3 = TNET3.
      WA_TAB3-NET2 = TNET2.
      WA_TAB3-NET1 = TNET1.
      CLEAR : VNET2.
      VNET2 = TNET1 + TNET2 + TNET3 + TNET4 + TNET5 + TNET6 + TNET7 + TNET8 + TNET9 + TNET10 + TNET11 + TNET12.
      WA_TAB3-TNET = VNET2.

      CONDENSE: WA_TAB3-CQTY12,WA_TAB3-CQTY11,WA_TAB3-CQTY10,WA_TAB3-CQTY9,WA_TAB3-CQTY8,WA_TAB3-CQTY7,WA_TAB3-CQTY6,WA_TAB3-CQTY5,WA_TAB3-CQTY4,
      WA_TAB3-CQTY3,WA_TAB3-CQTY2,WA_TAB3-CQTY1,WA_TAB3-TQTY.
      CONDENSE: WA_TAB3-NET12,WA_TAB3-NET11,WA_TAB3-NET10,WA_TAB3-NET9,WA_TAB3-NET8,WA_TAB3-NET7,WA_TAB3-NET6,WA_TAB3-NET5,WA_TAB3-NET4,
     WA_TAB3-NET3,WA_TAB3-NET2,WA_TAB3-NET1,WA_TAB3-TNET.
      WA_TAB3-TYP = 'DTOT'.
      COLLECT WA_TAB3 INTO IT_TAB3.

      TQTY12 = 0.
      TQTY11 = 0.
      TQTY10 = 0.
      TQTY9 = 0.
      TQTY8 = 0.
      TQTY7 = 0.
      TQTY6 = 0.
      TQTY5 = 0.
      TQTY4 = 0.
      TQTY3 = 0.
      TQTY2 = 0.
      TQTY1 = 0.

      TNET12 = 0.
      TNET11 = 0.
      TNET10 = 0.
      TNET9 = 0.
      TNET8 = 0.
      TNET7 = 0.
      TNET6 = 0.
      TNET5 = 0.
      TNET4 = 0.
      TNET3 = 0.
      TNET2 = 0.
      TNET1 = 0.

    ENDAT.

    AT LAST.


      WA_TAB3-BEZEI = 'ALL TOTAL'.
      WA_TAB3-SPART = SPACE.
      WA_TAB3-PRN_SEQ = SPACE.
      WA_TAB3-PACK = SPACE.
      WA_TAB3-CQTY12 = TOQTY12.
      WA_TAB3-CQTY11 = TOQTY11.
      WA_TAB3-CQTY10 = TOQTY10.
      WA_TAB3-CQTY9 = TOQTY9.
      WA_TAB3-CQTY8 = TOQTY8.
      WA_TAB3-CQTY7 = TOQTY7.
      WA_TAB3-CQTY6 = TOQTY6.
      WA_TAB3-CQTY5 = TOQTY5.
      WA_TAB3-CQTY4 = TOQTY4.
      WA_TAB3-CQTY3 = TOQTY3.
      WA_TAB3-CQTY2 = TOQTY2.
      WA_TAB3-CQTY1 = TOQTY1.
      CLEAR : VQTY3.
      VQTY3 = TOQTY1 + TOQTY2 + TOQTY3 + TOQTY4 + TOQTY5 + TOQTY6 + TOQTY7 + TOQTY8 + TOQTY9 + TOQTY10 + TOQTY11 + TOQTY12.
      WA_TAB3-TQTY = VQTY3.
**********************
      WA_TAB3-NET12 = TONET12.
      WA_TAB3-NET11 = TONET11.
      WA_TAB3-NET10 = TONET10.
      WA_TAB3-NET9 = TONET9.
      WA_TAB3-NET8 = TONET8.
      WA_TAB3-NET7 = TONET7.
      WA_TAB3-NET6 = TONET6.
      WA_TAB3-NET5 = TONET5.
      WA_TAB3-NET4 = TONET4.
      WA_TAB3-NET3 = TONET3.
      WA_TAB3-NET2 = TONET2.
      WA_TAB3-NET1 = TONET1.

      CLEAR : VNET3.
      VNET3 = TONET1 + TONET2 + TONET3 + TONET4 + TONET5 + TONET6 + TONET7 + TONET8 + TONET9 + TONET10 + TONET11 + TONET12.
      WA_TAB3-TNET = VNET3.


      CONDENSE: WA_TAB3-CQTY12,WA_TAB3-CQTY11,WA_TAB3-CQTY10,WA_TAB3-CQTY9,WA_TAB3-CQTY8,WA_TAB3-CQTY7,WA_TAB3-CQTY6,WA_TAB3-CQTY5,WA_TAB3-CQTY4,
      WA_TAB3-CQTY3,WA_TAB3-CQTY2,WA_TAB3-CQTY1,WA_TAB3-TQTY.

      CONDENSE: WA_TAB3-NET12,WA_TAB3-NET11,WA_TAB3-NET10,WA_TAB3-NET9,WA_TAB3-NET8,WA_TAB3-NET7,WA_TAB3-NET6,WA_TAB3-NET5,WA_TAB3-NET4,
    WA_TAB3-NET3,WA_TAB3-NET2,WA_TAB3-NET1,WA_TAB3-TNET..

      WA_TAB3-TYP = 'DTOT'.
      COLLECT WA_TAB3 INTO IT_TAB3.

    ENDAT.

    CLEAR WA_TAB3.

  ENDLOOP.

  FROM_DT = SDATE1-LOW.
  TO_DT = SDATE1-HIGH.

  SELECT SINGLE * FROM T247 WHERE SPRAS EQ 'EN' AND MNR EQ DATE12+4(2).
  IF SY-SUBRC EQ 0.
    CONCATENATE T247-LTX+0(3) '''' DATE12+0(4) INTO MON12.
  ENDIF.
  SELECT SINGLE * FROM T247 WHERE SPRAS EQ 'EN' AND MNR EQ DATE11+4(2).
  IF SY-SUBRC EQ 0.
    CONCATENATE T247-LTX+0(3) '''' DATE11+0(4) INTO MON11.
  ENDIF.
  SELECT SINGLE * FROM T247 WHERE SPRAS EQ 'EN' AND MNR EQ DATE10+4(2).
  IF SY-SUBRC EQ 0.
    CONCATENATE T247-LTX+0(3) '''' DATE10+0(4) INTO MON10.
  ENDIF.
  SELECT SINGLE * FROM T247 WHERE SPRAS EQ 'EN' AND MNR EQ DATE9+4(2).
  IF SY-SUBRC EQ 0.
    CONCATENATE T247-LTX+0(3) '''' DATE9+0(4) INTO MON9.
  ENDIF.
  SELECT SINGLE * FROM T247 WHERE SPRAS EQ 'EN' AND MNR EQ DATE8+4(2).
  IF SY-SUBRC EQ 0.
    CONCATENATE T247-LTX+0(3) '''' DATE8+0(4) INTO MON8.
  ENDIF.
  SELECT SINGLE * FROM T247 WHERE SPRAS EQ 'EN' AND MNR EQ DATE7+4(2).
  IF SY-SUBRC EQ 0.
    CONCATENATE T247-LTX+0(3) '''' DATE7+0(4) INTO MON7.
  ENDIF.
  SELECT SINGLE * FROM T247 WHERE SPRAS EQ 'EN' AND MNR EQ DATE6+4(2).
  IF SY-SUBRC EQ 0.
    CONCATENATE T247-LTX+0(3) '''' DATE6+0(4) INTO MON6.
  ENDIF.
  SELECT SINGLE * FROM T247 WHERE SPRAS EQ 'EN' AND MNR EQ DATE5+4(2).
  IF SY-SUBRC EQ 0.
    CONCATENATE T247-LTX+0(3) '''' DATE5+0(4) INTO MON5.
  ENDIF.
  SELECT SINGLE * FROM T247 WHERE SPRAS EQ 'EN' AND MNR EQ DATE4+4(2).
  IF SY-SUBRC EQ 0.
    CONCATENATE T247-LTX+0(3) '''' DATE4+0(4) INTO MON4.
  ENDIF.
  SELECT SINGLE * FROM T247 WHERE SPRAS EQ 'EN' AND MNR EQ DATE3+4(2).
  IF SY-SUBRC EQ 0.
    CONCATENATE T247-LTX+0(3) '''' DATE3+0(4) INTO MON3.
  ENDIF.
  SELECT SINGLE * FROM T247 WHERE SPRAS EQ 'EN' AND MNR EQ DATE2+4(2).
  IF SY-SUBRC EQ 0.
    CONCATENATE T247-LTX+0(3) '''' DATE2+0(4) INTO MON2.
  ENDIF.
  SELECT SINGLE * FROM T247 WHERE SPRAS EQ 'EN' AND MNR EQ DATE1+4(2).
  IF SY-SUBRC EQ 0.
    CONCATENATE T247-LTX+0(3) '''' DATE1+0(4) INTO MON1.
  ENDIF.

  IF R1 EQ 'X' .
    TYP1 = 'R1'.
  ELSEIF R2 EQ 'X'.
    TYP1 = 'R3'.
  ENDIF.
  IF R1 EQ 'X' .
    CALL FUNCTION 'SSF_FUNCTION_MODULE_NAME'
      EXPORTING
        FORMNAME           = 'ZSR8_A21'
*       VARIANT            = ' '
*       DIRECT_CALL        = ' '
      IMPORTING
        FM_NAME            = V_FM
      EXCEPTIONS
        NO_FORM            = 1
        NO_FUNCTION_MODULE = 2
        OTHERS             = 3.
  ELSE.

    CALL FUNCTION 'SSF_FUNCTION_MODULE_NAME'
      EXPORTING
        FORMNAME           = 'ZSR8_A31'
*       VARIANT            = ' '
*       DIRECT_CALL        = ' '
      IMPORTING
        FM_NAME            = V_FM
      EXCEPTIONS
        NO_FORM            = 1
        NO_FUNCTION_MODULE = 2
        OTHERS             = 3.
  ENDIF.

  IF L1 EQ 'X'.

    CALL FUNCTION V_FM
      EXPORTING
        FROM_DT          = FROM_DT
        TO_DT            = TO_DT
        MON12            = MON12
        MON11            = MON11
        MON10            = MON10
        MON9             = MON9
        MON8             = MON8
        MON7             = MON7
        MON6             = MON6
        MON5             = MON5
        MON4             = MON4
        MON3             = MON3
        MON2             = MON2
        MON1             = MON1
        TYP1             = TYP1
      TABLES
        IT_TAB1          = IT_TAB3
      EXCEPTIONS
        FORMATTING_ERROR = 1
        INTERNAL_ERROR   = 2
        SEND_ERROR       = 3
        USER_CANCELED    = 4
        OTHERS           = 5.

  ELSEIF L2 EQ 'X'.


*    *  *   * Set the control parameter
    W_CTRLOP-GETOTF = ABAP_TRUE.
    W_CTRLOP-NO_DIALOG = ABAP_TRUE.
    W_COMPOP-TDNOPREV = ABAP_TRUE.
    W_CTRLOP-PREVIEW = SPACE.
    W_COMPOP-TDDEST = 'LOCL'.




    CALL FUNCTION V_FM
      EXPORTING
        CONTROL_PARAMETERS = W_CTRLOP
        OUTPUT_OPTIONS     = W_COMPOP
        USER_SETTINGS      = ABAP_TRUE
        FROM_DT            = FROM_DT
        TO_DT              = TO_DT
        MON12              = MON12
        MON11              = MON11
        MON10              = MON10
        MON9               = MON9
        MON8               = MON8
        MON7               = MON7
        MON6               = MON6
        MON5               = MON5
        MON4               = MON4
        MON3               = MON3
        MON2               = MON2
        MON1               = MON1
      IMPORTING
        JOB_OUTPUT_INFO    = W_RETURN " This will have all output
      TABLES
        IT_TAB1            = IT_TAB3
      EXCEPTIONS
        FORMATTING_ERROR   = 1
        INTERNAL_ERROR     = 2
        SEND_ERROR         = 3
        USER_CANCELED      = 4
        OTHERS             = 5.

    I_OTF[] = W_RETURN-OTFDATA[].

* Import Binary file and filesize
    CALL FUNCTION 'CONVERT_OTF'
      EXPORTING
        FORMAT                = 'PDF'
        MAX_LINEWIDTH         = 132
      IMPORTING
        BIN_FILESIZE          = V_LEN_IN
        BIN_FILE              = I_XSTRING   " This is NOT Binary. This is Hexa
      TABLES
        OTF                   = I_OTF
        LINES                 = I_TLINE
      EXCEPTIONS
        ERR_MAX_LINEWIDTH     = 1
        ERR_FORMAT            = 2
        ERR_CONV_NOT_POSSIBLE = 3
        OTHERS                = 4.
* Sy-subrc check not checked



*  * Convert Hexa String to Binary format
    CALL FUNCTION 'SCMS_XSTRING_TO_BINARY'
      EXPORTING
        BUFFER     = I_XSTRING
      TABLES
        BINARY_TAB = I_OBJBIN[].
    IN_MAILID = EMAIL.
    PERFORM SEND_MAIL USING IN_MAILID .


  ENDIF.
*&---------------------------------------------------------------------*
*&      Form  SALESDATA
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*  -->  p1        text
*  <--  p2        text
*----------------------------------------------------------------------*
FORM SALESDATA .
  CLEAR : IT_ZSALES_TAB1,WA_ZSALES_TAB1.
  SELECT * FROM ZSALES_TAB1 INTO TABLE IT_ZSALES_TAB1 WHERE DATAB EQ DATE1.
  LOOP AT IT_ZSALES_TAB1 INTO WA_ZSALES_TAB1.
*    WA_TAB1-ZMONTH1 = WA_ZSALES_TAB1-DATAB+4(2).
*    WA_TAB1-ZYEAR1 = WA_ZSALES_TAB1-DATAB+0(4).
    WA_TAB1-MATNR = WA_ZSALES_TAB1-MATNR.
    WA_TAB1-NET1 = WA_ZSALES_TAB1-NET.
    WA_TAB1-C_QTY1 = WA_ZSALES_TAB1-C_QTY.
*    WA_TAB1-C_QTY2 = 0.
*    WA_TAB1-C_QTY3 = 0.
*    WA_TAB1-C_QTY4 = 0.
*    WA_TAB1-C_QTY5 = 0.
*    WA_TAB1-C_QTY6 = 0.

    COLLECT WA_TAB1 INTO IT_TAB1.
    CLEAR WA_TAB1.
    WA_MAT1-MATNR =  WA_ZSALES_TAB1-MATNR.
    COLLECT WA_MAT1 INTO IT_MAT1.
    CLEAR WA_MAT1.
  ENDLOOP.

  CLEAR : IT_ZSALES_TAB1,WA_ZSALES_TAB1.
  SELECT * FROM ZSALES_TAB1 INTO TABLE IT_ZSALES_TAB1 WHERE DATAB EQ DATE2.
  LOOP AT IT_ZSALES_TAB1 INTO WA_ZSALES_TAB1.
*    WA_TAB1-ZMONTH2 = WA_ZSALES_TAB1-DATAB+4(2).
*    WA_TAB1-ZYEAR2 = WA_ZSALES_TAB1-DATAB+0(4).
    WA_TAB1-MATNR = WA_ZSALES_TAB1-MATNR.
*    WA_TAB1-C_QTY1 = 0.
    WA_TAB1-NET2 = WA_ZSALES_TAB1-NET.
    WA_TAB1-C_QTY2 = WA_ZSALES_TAB1-C_QTY.
*    WA_TAB1-C_QTY3 = 0.
*    WA_TAB1-C_QTY4 = 0.
*    WA_TAB1-C_QTY5 = 0.
*    WA_TAB1-C_QTY6 = 0.
    COLLECT WA_TAB1 INTO IT_TAB1.
    CLEAR WA_TAB1.
    WA_MAT1-MATNR =  WA_ZSALES_TAB1-MATNR.
    COLLECT WA_MAT1 INTO IT_MAT1.
    CLEAR WA_MAT1.
  ENDLOOP.

  CLEAR : IT_ZSALES_TAB1,WA_ZSALES_TAB1.
  SELECT * FROM ZSALES_TAB1 INTO TABLE IT_ZSALES_TAB1 WHERE DATAB EQ DATE3.
  LOOP AT IT_ZSALES_TAB1 INTO WA_ZSALES_TAB1.
*    WA_TAB1-ZMONTH3 = WA_ZSALES_TAB1-DATAB+4(2).
*    WA_TAB1-ZYEAR3 = WA_ZSALES_TAB1-DATAB+0(4).
    WA_TAB1-MATNR = WA_ZSALES_TAB1-MATNR.
*    WA_TAB1-C_QTY1 = 0.
*    WA_TAB1-C_QTY2 = 0.
    WA_TAB1-NET3 = WA_ZSALES_TAB1-NET.
    WA_TAB1-C_QTY3 = WA_ZSALES_TAB1-C_QTY.
*    WA_TAB1-C_QTY4 = 0.
*    WA_TAB1-C_QTY5 = 0.
*    WA_TAB1-C_QTY6 = 0.
    COLLECT WA_TAB1 INTO IT_TAB1.
    CLEAR WA_TAB1.
    WA_MAT1-MATNR =  WA_ZSALES_TAB1-MATNR.
    COLLECT WA_MAT1 INTO IT_MAT1.
    CLEAR WA_MAT1.
  ENDLOOP.

  CLEAR : IT_ZSALES_TAB1,WA_ZSALES_TAB1.
  SELECT * FROM ZSALES_TAB1 INTO TABLE IT_ZSALES_TAB1 WHERE DATAB EQ DATE4.
  LOOP AT IT_ZSALES_TAB1 INTO WA_ZSALES_TAB1.
*    WA_TAB1-ZMONTH4 = WA_ZSALES_TAB1-DATAB+4(2).
*    WA_TAB1-ZYEAR4 = WA_ZSALES_TAB1-DATAB+0(4).
    WA_TAB1-MATNR = WA_ZSALES_TAB1-MATNR.
*    WA_TAB1-C_QTY1 = 0.
*    WA_TAB1-C_QTY2 = 0.
*    WA_TAB1-C_QTY3 = 0.
    WA_TAB1-C_QTY4 = WA_ZSALES_TAB1-C_QTY.
    WA_TAB1-NET4 = WA_ZSALES_TAB1-NET.
*    WA_TAB1-C_QTY5 = 0.
*    WA_TAB1-C_QTY6 = 0.
    COLLECT WA_TAB1 INTO IT_TAB1.
    CLEAR WA_TAB1.
    WA_MAT1-MATNR =  WA_ZSALES_TAB1-MATNR.
    COLLECT WA_MAT1 INTO IT_MAT1.
    CLEAR WA_MAT1.
  ENDLOOP.

  CLEAR : IT_ZSALES_TAB1,WA_ZSALES_TAB1.
  SELECT * FROM ZSALES_TAB1 INTO TABLE IT_ZSALES_TAB1 WHERE DATAB EQ DATE5.
  LOOP AT IT_ZSALES_TAB1 INTO WA_ZSALES_TAB1.
*    WA_TAB1-ZMONTH5 = WA_ZSALES_TAB1-DATAB+4(2).
*    WA_TAB1-ZYEAR5 = WA_ZSALES_TAB1-DATAB+0(4).
    WA_TAB1-MATNR = WA_ZSALES_TAB1-MATNR.
*    WA_TAB1-C_QTY1 = 0.
*    WA_TAB1-C_QTY2 = 0.
*    WA_TAB1-C_QTY3 = 0.
*    WA_TAB1-C_QTY4 = 0.
    WA_TAB1-C_QTY5 = WA_ZSALES_TAB1-C_QTY.
    WA_TAB1-NET5 = WA_ZSALES_TAB1-NET.
*    WA_TAB1-C_QTY6 = 0.
    COLLECT WA_TAB1 INTO IT_TAB1.
    CLEAR WA_TAB1.
    WA_MAT1-MATNR =  WA_ZSALES_TAB1-MATNR.
    COLLECT WA_MAT1 INTO IT_MAT1.
    CLEAR WA_MAT1.
  ENDLOOP.

  CLEAR : IT_ZSALES_TAB1,WA_ZSALES_TAB1.
  SELECT * FROM ZSALES_TAB1 INTO TABLE IT_ZSALES_TAB1 WHERE DATAB EQ DATE6.
  LOOP AT IT_ZSALES_TAB1 INTO WA_ZSALES_TAB1.
*    WA_TAB1-ZMONTH6 = WA_ZSALES_TAB1-DATAB+4(2).
*    WA_TAB1-ZYEAR6 = WA_ZSALES_TAB1-DATAB+0(4).
    WA_TAB1-MATNR = WA_ZSALES_TAB1-MATNR.
*    WA_TAB1-C_QTY1 = 0.
*    WA_TAB1-C_QTY2 = 0.
*    WA_TAB1-C_QTY3 = 0.
*    WA_TAB1-C_QTY4 = 0.
*    WA_TAB1-C_QTY5 = 0.
    WA_TAB1-C_QTY6 = WA_ZSALES_TAB1-C_QTY.
    WA_TAB1-NET6 = WA_ZSALES_TAB1-NET.
    COLLECT WA_TAB1 INTO IT_TAB1.
    CLEAR WA_TAB1.
    WA_MAT1-MATNR =  WA_ZSALES_TAB1-MATNR.
    COLLECT WA_MAT1 INTO IT_MAT1.
    CLEAR WA_MAT1.
  ENDLOOP.

  CLEAR : IT_ZSALES_TAB1,WA_ZSALES_TAB1.
  SELECT * FROM ZSALES_TAB1 INTO TABLE IT_ZSALES_TAB1 WHERE DATAB EQ DATE7.
  LOOP AT IT_ZSALES_TAB1 INTO WA_ZSALES_TAB1.
*    WA_TAB1-ZMONTH6 = WA_ZSALES_TAB1-DATAB+4(2).
*    WA_TAB1-ZYEAR6 = WA_ZSALES_TAB1-DATAB+0(4).
    WA_TAB1-MATNR = WA_ZSALES_TAB1-MATNR.
*    WA_TAB1-C_QTY1 = 0.
*    WA_TAB1-C_QTY2 = 0.
*    WA_TAB1-C_QTY3 = 0.
*    WA_TAB1-C_QTY4 = 0.
*    WA_TAB1-C_QTY5 = 0.
    WA_TAB1-C_QTY7 = WA_ZSALES_TAB1-C_QTY.
    WA_TAB1-NET7 = WA_ZSALES_TAB1-NET.
    COLLECT WA_TAB1 INTO IT_TAB1.
    CLEAR WA_TAB1.
    WA_MAT1-MATNR =  WA_ZSALES_TAB1-MATNR.
    COLLECT WA_MAT1 INTO IT_MAT1.
    CLEAR WA_MAT1.
  ENDLOOP.

  CLEAR : IT_ZSALES_TAB1,WA_ZSALES_TAB1.
  SELECT * FROM ZSALES_TAB1 INTO TABLE IT_ZSALES_TAB1 WHERE DATAB EQ DATE8.
  LOOP AT IT_ZSALES_TAB1 INTO WA_ZSALES_TAB1.
*    WA_TAB1-ZMONTH6 = WA_ZSALES_TAB1-DATAB+4(2).
*    WA_TAB1-ZYEAR6 = WA_ZSALES_TAB1-DATAB+0(4).
    WA_TAB1-MATNR = WA_ZSALES_TAB1-MATNR.
*    WA_TAB1-C_QTY1 = 0.
*    WA_TAB1-C_QTY2 = 0.
*    WA_TAB1-C_QTY3 = 0.
*    WA_TAB1-C_QTY4 = 0.
*    WA_TAB1-C_QTY5 = 0.
    WA_TAB1-C_QTY8 = WA_ZSALES_TAB1-C_QTY.
    WA_TAB1-NET8 = WA_ZSALES_TAB1-NET.
    COLLECT WA_TAB1 INTO IT_TAB1.
    CLEAR WA_TAB1.
    WA_MAT1-MATNR =  WA_ZSALES_TAB1-MATNR.
    COLLECT WA_MAT1 INTO IT_MAT1.
    CLEAR WA_MAT1.
  ENDLOOP.

  CLEAR : IT_ZSALES_TAB1,WA_ZSALES_TAB1.
  SELECT * FROM ZSALES_TAB1 INTO TABLE IT_ZSALES_TAB1 WHERE DATAB EQ DATE9.
  LOOP AT IT_ZSALES_TAB1 INTO WA_ZSALES_TAB1.
*    WA_TAB1-ZMONTH6 = WA_ZSALES_TAB1-DATAB+4(2).
*    WA_TAB1-ZYEAR6 = WA_ZSALES_TAB1-DATAB+0(4).
    WA_TAB1-MATNR = WA_ZSALES_TAB1-MATNR.
*    WA_TAB1-C_QTY1 = 0.
*    WA_TAB1-C_QTY2 = 0.
*    WA_TAB1-C_QTY3 = 0.
*    WA_TAB1-C_QTY4 = 0.
*    WA_TAB1-C_QTY5 = 0.
    WA_TAB1-C_QTY9 = WA_ZSALES_TAB1-C_QTY.
    WA_TAB1-NET9 = WA_ZSALES_TAB1-NET.
    COLLECT WA_TAB1 INTO IT_TAB1.
    CLEAR WA_TAB1.
    WA_MAT1-MATNR =  WA_ZSALES_TAB1-MATNR.
    COLLECT WA_MAT1 INTO IT_MAT1.
    CLEAR WA_MAT1.
  ENDLOOP.

  CLEAR : IT_ZSALES_TAB1,WA_ZSALES_TAB1.
  SELECT * FROM ZSALES_TAB1 INTO TABLE IT_ZSALES_TAB1 WHERE DATAB EQ DATE10.
  LOOP AT IT_ZSALES_TAB1 INTO WA_ZSALES_TAB1.
*    WA_TAB1-ZMONTH6 = WA_ZSALES_TAB1-DATAB+4(2).
*    WA_TAB1-ZYEAR6 = WA_ZSALES_TAB1-DATAB+0(4).
    WA_TAB1-MATNR = WA_ZSALES_TAB1-MATNR.
*    WA_TAB1-C_QTY1 = 0.
*    WA_TAB1-C_QTY2 = 0.
*    WA_TAB1-C_QTY3 = 0.
*    WA_TAB1-C_QTY4 = 0.
*    WA_TAB1-C_QTY5 = 0.
    WA_TAB1-C_QTY10 = WA_ZSALES_TAB1-C_QTY.
    WA_TAB1-NET10 = WA_ZSALES_TAB1-NET.
    COLLECT WA_TAB1 INTO IT_TAB1.
    CLEAR WA_TAB1.
    WA_MAT1-MATNR =  WA_ZSALES_TAB1-MATNR.
    COLLECT WA_MAT1 INTO IT_MAT1.
    CLEAR WA_MAT1.
  ENDLOOP.

  CLEAR : IT_ZSALES_TAB1,WA_ZSALES_TAB1.
  SELECT * FROM ZSALES_TAB1 INTO TABLE IT_ZSALES_TAB1 WHERE DATAB EQ DATE11.
  LOOP AT IT_ZSALES_TAB1 INTO WA_ZSALES_TAB1.
*    WA_TAB1-ZMONTH6 = WA_ZSALES_TAB1-DATAB+4(2).
*    WA_TAB1-ZYEAR6 = WA_ZSALES_TAB1-DATAB+0(4).
    WA_TAB1-MATNR = WA_ZSALES_TAB1-MATNR.
*    WA_TAB1-C_QTY1 = 0.
*    WA_TAB1-C_QTY2 = 0.
*    WA_TAB1-C_QTY3 = 0.
*    WA_TAB1-C_QTY4 = 0.
*    WA_TAB1-C_QTY5 = 0.
    WA_TAB1-C_QTY11 = WA_ZSALES_TAB1-C_QTY.
    WA_TAB1-NET11 = WA_ZSALES_TAB1-NET.
    COLLECT WA_TAB1 INTO IT_TAB1.
    CLEAR WA_TAB1.
    WA_MAT1-MATNR =  WA_ZSALES_TAB1-MATNR.
    COLLECT WA_MAT1 INTO IT_MAT1.
    CLEAR WA_MAT1.
  ENDLOOP.

  CLEAR : IT_ZSALES_TAB1,WA_ZSALES_TAB1.
  SELECT * FROM ZSALES_TAB1 INTO TABLE IT_ZSALES_TAB1 WHERE DATAB EQ DATE12.
  LOOP AT IT_ZSALES_TAB1 INTO WA_ZSALES_TAB1.
*    WA_TAB1-ZMONTH6 = WA_ZSALES_TAB1-DATAB+4(2).
*    WA_TAB1-ZYEAR6 = WA_ZSALES_TAB1-DATAB+0(4).
    WA_TAB1-MATNR = WA_ZSALES_TAB1-MATNR.
*    WA_TAB1-C_QTY1 = 0.
*    WA_TAB1-C_QTY2 = 0.
*    WA_TAB1-C_QTY3 = 0.
*    WA_TAB1-C_QTY4 = 0.
*    WA_TAB1-C_QTY5 = 0.
    WA_TAB1-C_QTY12 = WA_ZSALES_TAB1-C_QTY.
    WA_TAB1-NET12 = WA_ZSALES_TAB1-NET.
    COLLECT WA_TAB1 INTO IT_TAB1.
    CLEAR WA_TAB1.
    WA_MAT1-MATNR =  WA_ZSALES_TAB1-MATNR.
    COLLECT WA_MAT1 INTO IT_MAT1.
    CLEAR WA_MAT1.
  ENDLOOP.

ENDFORM.
*&---------------------------------------------------------------------*
*&      Form  SEND_MAIL
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*      -->P_IN_MAILID  text
*----------------------------------------------------------------------*
FORM SEND_MAIL  USING    P_IN_MAILID.
  DATA: SALUTATION TYPE STRING.
  DATA: BODY TYPE STRING.
  DATA: FOOTER TYPE STRING.

  DATA: LO_SEND_REQUEST TYPE REF TO CL_BCS,
        LO_DOCUMENT     TYPE REF TO CL_DOCUMENT_BCS,
        LO_SENDER       TYPE REF TO IF_SENDER_BCS,
        LO_RECIPIENT    TYPE REF TO IF_RECIPIENT_BCS VALUE IS INITIAL,LT_MESSAGE_BODY TYPE BCSY_TEXT,
        LX_DOCUMENT_BCS TYPE REF TO CX_DOCUMENT_BCS,
        LV_SENT_TO_ALL  TYPE OS_BOOLEAN.

  "create send request
  LO_SEND_REQUEST = CL_BCS=>CREATE_PERSISTENT( ).

  "create message body and subject
  SALUTATION ='Dear Sir/Madam,'.
  APPEND SALUTATION TO LT_MESSAGE_BODY.
  APPEND INITIAL LINE TO LT_MESSAGE_BODY.

  BODY = 'Please find the attached SR2 REPORT in PDF format.'.

  APPEND BODY TO LT_MESSAGE_BODY.
  APPEND INITIAL LINE TO LT_MESSAGE_BODY.

  FOOTER = 'With Regards,'.
  APPEND FOOTER TO LT_MESSAGE_BODY.
  FOOTER = 'BLUE CROSS LABORATORIES PVT LTD.'.
  APPEND FOOTER TO LT_MESSAGE_BODY.

*  IF r4 EQ 'X'.
*    ntext1 = 'HALB LYING FOR MORE THAN 20 DAYS'.
*  ELSEIF r6 EQ 'X'.
*    ntext1 = 'REJECTION DONE BY QUALITY CONTROL'.
*  ELSE.
*    ntext1 = 'INSPECTION PLAN NOT ATTACHED'.
*  ENDIF.
*  "put your text into the document


  LO_DOCUMENT = CL_DOCUMENT_BCS=>CREATE_DOCUMENT(
I_TYPE = 'RAW'
I_TEXT = LT_MESSAGE_BODY
I_SUBJECT = 'SR8 REPORT' ).

*DATA: l_size TYPE sood-objlen. " Size of Attachment
*l_size = l_lines * 255.
  TRY.

      LO_DOCUMENT->ADD_ATTACHMENT(
      EXPORTING
      I_ATTACHMENT_TYPE = 'PDF'
      I_ATTACHMENT_SUBJECT = 'SR8 REPORT'
      I_ATT_CONTENT_HEX = I_OBJBIN[] ).
    CATCH CX_DOCUMENT_BCS INTO LX_DOCUMENT_BCS.

  ENDTRY.


* Add attachment
* Pass the document to send request
  LO_SEND_REQUEST->SET_DOCUMENT( LO_DOCUMENT ).

  "Create sender
  LO_SENDER = CL_SAPUSER_BCS=>CREATE( SY-UNAME ).

  LO_SENDER     = CL_CAM_ADDRESS_BCS=>CREATE_INTERNET_ADDRESS(

        I_ADDRESS_STRING = 'sales@bluecrosslabs.com'

        I_ADDRESS_NAME   = 'sales@bluecrosslabs.com' ).


  "Set sender
  LO_SEND_REQUEST->SET_SENDER( LO_SENDER ).

  "Create recipient
  LO_RECIPIENT = CL_CAM_ADDRESS_BCS=>CREATE_INTERNET_ADDRESS( IN_MAILID ).

*Set recipient
  LO_SEND_REQUEST->ADD_RECIPIENT(
  EXPORTING
  I_RECIPIENT = LO_RECIPIENT
  I_EXPRESS = ABAP_TRUE
  ).

  LO_SEND_REQUEST->ADD_RECIPIENT( LO_RECIPIENT ).

* Send email
  LO_SEND_REQUEST->SEND(
  EXPORTING
  I_WITH_ERROR_SCREEN = ABAP_TRUE
  RECEIVING
  RESULT = LV_SENT_TO_ALL ).

  CONCATENATE 'Email sent to' IN_MAILID INTO DATA(LV_MSG) SEPARATED BY SPACE.
  WRITE:/ LV_MSG COLOR COL_POSITIVE.
  SKIP.
* Commit Work to send the email
  COMMIT WORK.
ENDFORM.
