
**** RM-wise total ***********
GV_RM_SALE_TOT = GV_RM_SALE_TOT + GW_SR9_DTLS-SALE.
GV_RM_TARGET_TOT = GV_RM_TARGET_TOT + GW_SR9_DTLS-TARGET.
GV_RM_BGT_TOT = GV_RM_BGT_TOT + GW_SR9_DTLS-PER.

**** ZM-wise total ***********
GV_ZM_SALE_TOT = GV_ZM_SALE_TOT + GW_SR9_DTLS-SALE.
GV_ZM_TARGET_TOT = GV_ZM_TARGET_TOT + GW_SR9_DTLS-TARGET.
GV_ZM_BGT_TOT = GV_ZM_BGT_TOT + GW_SR9_DTLS-PER.

********* DZM-wise total *********
IF GW_SR9_DTLS-zdsm+0(2) = 'Z-'.
*****  IF GW_SR9_DTLS-RM = GW_SR9_RM-RM.
*****    GW_SR9_DZM-DIV = GW_SR9_DTLS-DIV.
*****    GW_SR9_DZM-ZDSM = GW_SR9_RM-ZDSM.
*****    GW_SR9_DZM-GM = GW_SR9_RM-GM.
*****    GW_SR9_DZM-SPART = GW_SR9_RM-SPART.
*****    GW_SR9_DZM-ZMONTH = GW_SR9_RM-ZMONTH.
*****    GW_SR9_DZM-ZYEAR = GW_SR9_RM-ZYEAR.
*****    GW_SR9_DZM-ZM = GW_SR9_RM-ZM.
*****    GW_SR9_DZM-RM = GW_SR9_RM-RM.
*****    GW_SR9_DZM-RM_DOJ = GW_SR9_RM-RM_DOJ.
*****    GW_SR9_DZM-RM_SHORT = GW_SR9_RM-RM_SHORT.
*****    GW_SR9_DZM-RM_HQ = GW_SR9_RM-RM_HQ.
*****
    GV_DZM_SALE_TOT = GV_DZM_SALE_TOT + GW_SR9_DTLS-SALE.
    GV_DZM_TARGET_TOT = GV_DZM_TARGET_TOT + GW_SR9_DTLS-TARGET.
    GV_DZM_BGT_TOT = GV_DZM_BGT_TOT + GW_SR9_DTLS-PER.
*****
  ENDIF.
*****
*****ENDIF.








