PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZTRANSP_D CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZTRANSP_D-ZBILL_NO .
    FIELD ZTRANSP_D-ZTRANS_N .
    FIELD ZTRANSP_D-ZTRANS_M .
    FIELD ZTRANSP_D-ZLR_NO .
    FIELD ZTRANSP_D-ZLR_DATE .
    FIELD ZTRANSP_D-ZVEHICAL .
    FIELD ZTRANSP_D-ZVEHICAL_E .
    FIELD ZTRANSP_D-ZCOL_INV .
    FIELD ZTRANSP_D-ZPRE_CAR .
    FIELD ZTRANSP_D-ZPLACE .
    FIELD ZTRANSP_D-ZVESSEL .
    FIELD ZTRANSP_D-ZPORT_LO .
    FIELD ZTRANSP_D-ZPORT_D .
    FIELD ZTRANSP_D-ZSHIP_N .
    FIELD ZTRANSP_D-ZSHIP_D .
    FIELD ZTRANSP_D-ZBILL_N .
    FIELD ZTRANSP_D-ZBILL_D .
    FIELD ZTRANSP_D-ZFLIGHT .
    FIELD ZTRANSP_D-ZADV_LIC .
    FIELD ZTRANSP_D-ZCONTAINER .
    FIELD ZTRANSP_D-ZH_ZCONTAINER .
    FIELD ZTRANSP_D-ZSEAL_N .
    FIELD ZTRANSP_D-ZRF_SEAL .
    FIELD ZTRANSP_D-ZSELF_N .
    FIELD ZTRANSP_D-ZSELF_D .
    FIELD ZTRANSP_D-ZSELP_N .
    FIELD ZTRANSP_D-ZSELP_D .
    FIELD ZTRANSP_D-ZSHIP_M .
    FIELD ZTRANSP_D-ZCUST_D .
    FIELD ZTRANSP_D-ERDAT .
    FIELD ZTRANSP_D-ERZET .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZTRANSP_D-ZBILL_NO .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
